/* AUTO-GENERATED by runtime/tools/generate_wild_diffs.py.
 * Source: pret/pokered (Red/Blue ROM).
 * Do not edit by hand. Re-run the script if pret
 * sources change. */

#ifndef GEN1_WILD_DIFFS_RB_GEN_H
#define GEN1_WILD_DIFFS_RB_GEN_H

#include <stdint.h>

#ifndef GBGEN1_WILDDIFF_STRUCT_DEFINED
#define GBGEN1_WILDDIFF_STRUCT_DEFINED
typedef struct {
    uint32_t rom_offset;
    uint8_t  count;          /* 2 or 3 candidate species */
    uint8_t  species[3];
} GBGen1WildDiff;
#endif

#define GEN1_WILD_DIFFS_RB_COUNT  432

static const GBGen1WildDiff GEN1_WILD_DIFFS_RB[GEN1_WILD_DIFFS_RB_COUNT] = {
    { 0x00D505, 2, { 129, 130,   0 } },  /* CeruleanCave1F grass slot 1: HYPNO / GOLBAT */
    { 0x00D507, 2, {  54,  39,   0 } },  /* CeruleanCave1F grass slot 2: MAGNETON / GRAVELER */
    { 0x00D509, 2, { 116, 186,   0 } },  /* CeruleanCave1F grass slot 3: DODRIO / GLOOM */
    { 0x00D50B, 2, { 119, 189,   0 } },  /* CeruleanCave1F grass slot 4: VENOMOTH / WEEPINBELL */
    { 0x00D50D, 2, {  45,  97,   0 } },  /* CeruleanCave1F grass slot 5: ARBOK / SANDSLASH */
    { 0x00D50F, 2, {  38, 119,   0 } },  /* CeruleanCave1F grass slot 6: KADABRA / VENOMOTH */
    { 0x00D513, 2, {  85,  76,   0 } },  /* CeruleanCave1F grass slot 8: RAICHU / DITTO */
    { 0x00D519, 2, { 116, 130,   0 } },  /* CeruleanCave2F grass slot 0: DODRIO / GOLBAT */
    { 0x00D51B, 2, { 119, 130,   0 } },  /* CeruleanCave2F grass slot 1: VENOMOTH / GOLBAT */
    { 0x00D51D, 2, {  38,  39,   0 } },  /* CeruleanCave2F grass slot 2: KADABRA / GRAVELER */
    { 0x00D51F, 2, {   1,  97,   0 } },  /* CeruleanCave2F grass slot 3: RHYDON / SANDSLASH */
    { 0x00D521, 2, { 145,  18,   0 } },  /* CeruleanCave2F grass slot 4: MAROWAK / RHYHORN */
    { 0x00D523, 2, { 141,  76,   0 } },  /* CeruleanCave2F grass slot 5: ELECTRODE / DITTO */
    { 0x00D525, 2, {  40, 186,   0 } },  /* CeruleanCave2F grass slot 6: CHANSEY / GLOOM */
    { 0x00D527, 2, { 101, 189,   0 } },  /* CeruleanCave2F grass slot 7: WIGGLYTUFF / WEEPINBELL */
    { 0x00D529, 2, {  76,   1,   0 } },  /* CeruleanCave2F grass slot 8: DITTO / RHYDON */
    { 0x00D52B, 2, {  76,   1,   0 } },  /* CeruleanCave2F grass slot 9: DITTO / RHYDON */
    { 0x00D52F, 2, {   1, 130,   0 } },  /* CeruleanCaveB1F grass slot 0: RHYDON / GOLBAT */
    { 0x00D531, 2, { 145, 130,   0 } },  /* CeruleanCaveB1F grass slot 1: MAROWAK / GOLBAT */
    { 0x00D533, 2, { 141,  39,   0 } },  /* CeruleanCaveB1F grass slot 2: ELECTRODE / GRAVELER */
    { 0x00D535, 2, {  40,  18,   0 } },  /* CeruleanCaveB1F grass slot 3: CHANSEY / RHYHORN */
    { 0x00D537, 2, {  46,   1,   0 } },  /* CeruleanCaveB1F grass slot 4: PARASECT / RHYDON */
    { 0x00D539, 2, {  85,  76,   0 } },  /* CeruleanCaveB1F grass slot 5: RAICHU / DITTO */
    { 0x00D53B, 3, {  45,  97,  40 } },  /* CeruleanCaveB1F grass slot 6: ARBOK / SANDSLASH / CHANSEY */
    { 0x00D53F, 2, {  76,  11,   0 } },  /* CeruleanCaveB1F grass slot 8: DITTO / LICKITUNG */
    { 0x00D541, 2, {  76,  11,   0 } },  /* CeruleanCaveB1F grass slot 9: DITTO / LICKITUNG */
    { 0x00D153, 2, { 107, 169,   0 } },  /* MtMoon1F grass slot 2: ZUBAT / GEODUDE */
    { 0x00D155, 2, { 169, 107,   0 } },  /* MtMoon1F grass slot 3: GEODUDE / ZUBAT */
    { 0x00D15D, 2, { 109, 107,   0 } },  /* MtMoon1F grass slot 7: PARAS / ZUBAT */
    { 0x00D15F, 2, { 107,  96,   0 } },  /* MtMoon1F grass slot 8: ZUBAT / SANDSHREW */
    { 0x00D169, 2, { 169, 107,   0 } },  /* MtMoonB1F grass slot 2: GEODUDE / ZUBAT */
    { 0x00D16D, 2, { 107, 169,   0 } },  /* MtMoonB1F grass slot 4: ZUBAT / GEODUDE */
    { 0x00D16F, 2, { 109, 107,   0 } },  /* MtMoonB1F grass slot 5: PARAS / ZUBAT */
    { 0x00D171, 2, { 107, 109,   0 } },  /* MtMoonB1F grass slot 6: ZUBAT / PARAS */
    { 0x00D173, 2, { 107, 109,   0 } },  /* MtMoonB1F grass slot 7: ZUBAT / PARAS */
    { 0x00D177, 2, { 169,   4,   0 } },  /* MtMoonB1F grass slot 9: GEODUDE / CLEFAIRY */
    { 0x00D17F, 2, { 107, 109,   0 } },  /* MtMoonB2F grass slot 2: ZUBAT / PARAS */
    { 0x00D181, 2, { 169, 107,   0 } },  /* MtMoonB2F grass slot 3: GEODUDE / ZUBAT */
    { 0x00D185, 2, { 109, 107,   0 } },  /* MtMoonB2F grass slot 5: PARAS / ZUBAT */
    { 0x00D187, 2, { 109, 107,   0 } },  /* MtMoonB2F grass slot 6: PARAS / ZUBAT */
    { 0x00D18B, 2, { 107,   4,   0 } },  /* MtMoonB2F grass slot 8: ZUBAT / CLEFAIRY */
    { 0x00D481, 3, {  55,  13, 165 } },  /* PokemonMansion1F grass slot 0: KOFFING / GRIMER / RATTATA */
    { 0x00D483, 3, {  55,  13, 166 } },  /* PokemonMansion1F grass slot 1: KOFFING / GRIMER / RATICATE */
    { 0x00D485, 2, { 163,  13,   0 } },  /* PokemonMansion1F grass slot 2: PONYTA / GRIMER */
    { 0x00D487, 2, { 163,  33,   0 } },  /* PokemonMansion1F grass slot 3: PONYTA / GROWLITHE */
    { 0x00D489, 3, {  33,  82, 165 } },  /* PokemonMansion1F grass slot 4: GROWLITHE / VULPIX / RATTATA */
    { 0x00D48B, 2, { 163, 166,   0 } },  /* PokemonMansion1F grass slot 5: PONYTA / RATICATE */
    { 0x00D48D, 3, {  13,  55,  33 } },  /* PokemonMansion1F grass slot 6: GRIMER / KOFFING / GROWLITHE */
    { 0x00D48F, 2, { 163,  13,   0 } },  /* PokemonMansion1F grass slot 7: PONYTA / GRIMER */
    { 0x00D491, 3, { 143, 136,  33 } },  /* PokemonMansion1F grass slot 8: WEEZING / MUK / GROWLITHE */
    { 0x00D493, 3, { 136, 143,  33 } },  /* PokemonMansion1F grass slot 9: MUK / WEEZING / GROWLITHE */
    { 0x00D497, 3, {  33,  82, 165 } },  /* PokemonMansion2F grass slot 0: GROWLITHE / VULPIX / RATTATA */
    { 0x00D499, 3, {  55,  13, 166 } },  /* PokemonMansion2F grass slot 1: KOFFING / GRIMER / RATICATE */
    { 0x00D49B, 2, {  55,  13,   0 } },  /* PokemonMansion2F grass slot 2: KOFFING / GRIMER */
    { 0x00D49D, 2, { 163,  13,   0 } },  /* PokemonMansion2F grass slot 3: PONYTA / GRIMER */
    { 0x00D49F, 3, {  55,  13, 165 } },  /* PokemonMansion2F grass slot 4: KOFFING / GRIMER / RATTATA */
    { 0x00D4A1, 2, { 163, 166,   0 } },  /* PokemonMansion2F grass slot 5: PONYTA / RATICATE */
    { 0x00D4A3, 2, {  13,  55,   0 } },  /* PokemonMansion2F grass slot 6: GRIMER / KOFFING */
    { 0x00D4A5, 2, { 163,  13,   0 } },  /* PokemonMansion2F grass slot 7: PONYTA / GRIMER */
    { 0x00D4A7, 2, { 143, 136,   0 } },  /* PokemonMansion2F grass slot 8: WEEZING / MUK */
    { 0x00D4A9, 2, { 136, 143,   0 } },  /* PokemonMansion2F grass slot 9: MUK / WEEZING */
    { 0x00D4AD, 3, {  55,  13, 165 } },  /* PokemonMansion3F grass slot 0: KOFFING / GRIMER / RATTATA */
    { 0x00D4AF, 3, {  33,  82, 166 } },  /* PokemonMansion3F grass slot 1: GROWLITHE / VULPIX / RATICATE */
    { 0x00D4B1, 2, {  55,  13,   0 } },  /* PokemonMansion3F grass slot 2: KOFFING / GRIMER */
    { 0x00D4B3, 2, { 163,  13,   0 } },  /* PokemonMansion3F grass slot 3: PONYTA / GRIMER */
    { 0x00D4B5, 3, { 163,  51, 165 } },  /* PokemonMansion3F grass slot 4: PONYTA / MAGMAR / RATTATA */
    { 0x00D4B7, 3, { 143, 136, 166 } },  /* PokemonMansion3F grass slot 5: WEEZING / MUK / RATICATE */
    { 0x00D4B9, 2, {  13,  55,   0 } },  /* PokemonMansion3F grass slot 6: GRIMER / KOFFING */
    { 0x00D4BB, 3, { 143, 136,  13 } },  /* PokemonMansion3F grass slot 7: WEEZING / MUK / GRIMER */
    { 0x00D4BD, 2, { 163, 136,   0 } },  /* PokemonMansion3F grass slot 8: PONYTA / MUK */
    { 0x00D4BF, 2, { 136, 143,   0 } },  /* PokemonMansion3F grass slot 9: MUK / WEEZING */
    { 0x00D4C3, 2, {  55,  13,   0 } },  /* PokemonMansionB1F grass slot 0: KOFFING / GRIMER */
    { 0x00D4C5, 2, {  55,  13,   0 } },  /* PokemonMansionB1F grass slot 1: KOFFING / GRIMER */
    { 0x00D4C7, 3, {  33,  82, 166 } },  /* PokemonMansionB1F grass slot 2: GROWLITHE / VULPIX / RATICATE */
    { 0x00D4C9, 2, { 163, 166,   0 } },  /* PokemonMansionB1F grass slot 3: PONYTA / RATICATE */
    { 0x00D4CB, 3, {  55,  13, 136 } },  /* PokemonMansionB1F grass slot 4: KOFFING / GRIMER / MUK */
    { 0x00D4CD, 3, { 143, 136, 166 } },  /* PokemonMansionB1F grass slot 5: WEEZING / MUK / RATICATE */
    { 0x00D4CF, 2, { 163,  76,   0 } },  /* PokemonMansionB1F grass slot 6: PONYTA / DITTO */
    { 0x00D4D1, 3, {  13,  55, 166 } },  /* PokemonMansionB1F grass slot 7: GRIMER / KOFFING / RATICATE */
    { 0x00D4D3, 3, { 143,  51,  76 } },  /* PokemonMansionB1F grass slot 8: WEEZING / MAGMAR / DITTO */
    { 0x00D4D5, 3, { 136, 143,  76 } },  /* PokemonMansionB1F grass slot 9: MUK / WEEZING / DITTO */
    { 0x00D2C1, 2, {  17,  25,   0 } },  /* PokemonTower3F grass slot 7: CUBONE / GASTLY */
    { 0x00D2C3, 2, {  17, 147,   0 } },  /* PokemonTower3F grass slot 8: CUBONE / HAUNTER */
    { 0x00D2D5, 2, { 147,  25,   0 } },  /* PokemonTower4F grass slot 6: HAUNTER / GASTLY */
    { 0x00D2D7, 2, {  17,  25,   0 } },  /* PokemonTower4F grass slot 7: CUBONE / GASTLY */
    { 0x00D2D9, 2, {  17, 147,   0 } },  /* PokemonTower4F grass slot 8: CUBONE / HAUNTER */
    { 0x00D2DB, 2, {  25, 147,   0 } },  /* PokemonTower4F grass slot 9: GASTLY / HAUNTER */
    { 0x00D2EB, 2, { 147,  17,   0 } },  /* PokemonTower5F grass slot 6: HAUNTER / CUBONE */
    { 0x00D2ED, 2, {  17,  25,   0 } },  /* PokemonTower5F grass slot 7: CUBONE / GASTLY */
    { 0x00D2EF, 2, {  17, 147,   0 } },  /* PokemonTower5F grass slot 8: CUBONE / HAUNTER */
    { 0x00D2F1, 2, {  25, 147,   0 } },  /* PokemonTower5F grass slot 9: GASTLY / HAUNTER */
    { 0x00D301, 2, { 147,  17,   0 } },  /* PokemonTower6F grass slot 6: HAUNTER / CUBONE */
    { 0x00D303, 2, {  17,  25,   0 } },  /* PokemonTower6F grass slot 7: CUBONE / GASTLY */
    { 0x00D305, 2, {  17, 147,   0 } },  /* PokemonTower6F grass slot 8: CUBONE / HAUNTER */
    { 0x00D315, 2, { 147,  25,   0 } },  /* PokemonTower7F grass slot 5: HAUNTER / GASTLY */
    { 0x00D319, 2, {  17,  25,   0 } },  /* PokemonTower7F grass slot 7: CUBONE / GASTLY */
    { 0x00D545, 2, {   6, 173,   0 } },  /* PowerPlant grass slot 0: VOLTORB / MAGNEMITE */
    { 0x00D549, 2, {  84,  54,   0 } },  /* PowerPlant grass slot 2: PIKACHU / MAGNETON */
    { 0x00D54B, 2, {  84,   6,   0 } },  /* PowerPlant grass slot 3: PIKACHU / VOLTORB */
    { 0x00D54D, 2, { 173,   6,   0 } },  /* PowerPlant grass slot 4: MAGNEMITE / VOLTORB */
    { 0x00D54F, 2, {   6,  13,   0 } },  /* PowerPlant grass slot 5: VOLTORB / GRIMER */
    { 0x00D551, 2, {  54,  13,   0 } },  /* PowerPlant grass slot 6: MAGNETON / GRIMER */
    { 0x00D555, 3, {  53,  85, 136 } },  /* PowerPlant grass slot 8: ELECTABUZZ / RAICHU / MUK */
    { 0x00D557, 3, {  53,  85, 136 } },  /* PowerPlant grass slot 9: ELECTABUZZ / RAICHU / MUK */
    { 0x00D22D, 2, { 107, 169,   0 } },  /* RockTunnel1F grass slot 1: ZUBAT / GEODUDE */
    { 0x00D22F, 2, { 169, 107,   0 } },  /* RockTunnel1F grass slot 2: GEODUDE / ZUBAT */
    { 0x00D231, 2, { 106, 107,   0 } },  /* RockTunnel1F grass slot 3: MACHOP / ZUBAT */
    { 0x00D235, 2, { 107, 169,   0 } },  /* RockTunnel1F grass slot 5: ZUBAT / GEODUDE */
    { 0x00D23B, 2, {  34, 106,   0 } },  /* RockTunnel1F grass slot 8: ONIX / MACHOP */
    { 0x00D23D, 2, {  34, 106,   0 } },  /* RockTunnel1F grass slot 9: ONIX / MACHOP */
    { 0x00D243, 2, { 107, 169,   0 } },  /* RockTunnelB1F grass slot 1: ZUBAT / GEODUDE */
    { 0x00D245, 2, { 169, 106,   0 } },  /* RockTunnelB1F grass slot 2: GEODUDE / MACHOP */
    { 0x00D247, 2, { 106, 107,   0 } },  /* RockTunnelB1F grass slot 3: MACHOP / ZUBAT */
    { 0x00D249, 2, { 169, 107,   0 } },  /* RockTunnelB1F grass slot 4: GEODUDE / ZUBAT */
    { 0x00D24B, 2, { 107, 169,   0 } },  /* RockTunnelB1F grass slot 5: ZUBAT / GEODUDE */
    { 0x00D253, 2, { 169,  34,   0 } },  /* RockTunnelB1F grass slot 9: GEODUDE / ONIX */
    { 0x00D0E3, 2, { 165,  36,   0 } },  /* Route1 grass slot 1: RATTATA / PIDGEY */
    { 0x00D257, 2, {   6, 173,   0 } },  /* Route10 grass slot 0: VOLTORB / MAGNEMITE */
    { 0x00D259, 2, {   5, 165,   0 } },  /* Route10 grass slot 1: SPEAROW / RATTATA */
    { 0x00D25B, 2, {   6, 173,   0 } },  /* Route10 grass slot 2: VOLTORB / MAGNEMITE */
    { 0x00D25D, 3, { 108,  96, 173 } },  /* Route10 grass slot 3: EKANS / SANDSHREW / MAGNEMITE */
    { 0x00D25F, 2, {   5,   3,   0 } },  /* Route10 grass slot 4: SPEAROW / NIDORAN_M */
    { 0x00D261, 3, { 108,  96,  15 } },  /* Route10 grass slot 5: EKANS / SANDSHREW / NIDORAN_F */
    { 0x00D263, 2, {   6, 173,   0 } },  /* Route10 grass slot 6: VOLTORB / MAGNEMITE */
    { 0x00D265, 2, {   5, 166,   0 } },  /* Route10 grass slot 7: SPEAROW / RATICATE */
    { 0x00D267, 3, { 108,  96, 106 } },  /* Route10 grass slot 8: EKANS / SANDSHREW / MACHOP */
    { 0x00D269, 3, { 108,  96, 106 } },  /* Route10 grass slot 9: EKANS / SANDSHREW / MACHOP */
    { 0x00D215, 3, { 108,  96,  36 } },  /* Route11 grass slot 0: EKANS / SANDSHREW / PIDGEY */
    { 0x00D217, 2, {   5, 165,   0 } },  /* Route11 grass slot 1: SPEAROW / RATTATA */
    { 0x00D219, 3, { 108,  96,  36 } },  /* Route11 grass slot 2: EKANS / SANDSHREW / PIDGEY */
    { 0x00D21D, 2, {   5, 165,   0 } },  /* Route11 grass slot 4: SPEAROW / RATTATA */
    { 0x00D221, 3, { 108,  96, 150 } },  /* Route11 grass slot 6: EKANS / SANDSHREW / PIDGEOTTO */
    { 0x00D223, 2, {   5, 150,   0 } },  /* Route11 grass slot 7: SPEAROW / PIDGEOTTO */
    { 0x00D227, 2, {  48, 166,   0 } },  /* Route11 grass slot 9: DROWZEE / RATICATE */
    { 0x00D26D, 2, { 185, 188,   0 } },  /* Route12 grass slot 0: ODDISH / BELLSPROUT */
    { 0x00D26F, 2, {  36, 188,   0 } },  /* Route12 grass slot 1: PIDGEY / BELLSPROUT */
    { 0x00D273, 2, {  65, 150,   0 } },  /* Route12 grass slot 3: VENONAT / PIDGEOTTO */
    { 0x00D275, 2, { 185, 188,   0 } },  /* Route12 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00D277, 2, {  65, 188,   0 } },  /* Route12 grass slot 5: VENONAT / BELLSPROUT */
    { 0x00D279, 3, { 185, 188, 186 } },  /* Route12 grass slot 6: ODDISH / BELLSPROUT / GLOOM */
    { 0x00D27B, 2, {  36, 189,   0 } },  /* Route12 grass slot 7: PIDGEY / WEEPINBELL */
    { 0x00D27D, 3, { 186, 189,  64 } },  /* Route12 grass slot 8: GLOOM / WEEPINBELL / FARFETCHD */
    { 0x00D27F, 3, { 186, 189,  64 } },  /* Route12 grass slot 9: GLOOM / WEEPINBELL / FARFETCHD */
    { 0x00D321, 2, { 185, 188,   0 } },  /* Route13 grass slot 0: ODDISH / BELLSPROUT */
    { 0x00D323, 2, {  36, 188,   0 } },  /* Route13 grass slot 1: PIDGEY / BELLSPROUT */
    { 0x00D325, 2, {  36, 150,   0 } },  /* Route13 grass slot 2: PIDGEY / PIDGEOTTO */
    { 0x00D327, 2, {  65,  36,   0 } },  /* Route13 grass slot 3: VENONAT / PIDGEY */
    { 0x00D329, 2, { 185, 188,   0 } },  /* Route13 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00D32B, 2, {  65, 188,   0 } },  /* Route13 grass slot 5: VENONAT / BELLSPROUT */
    { 0x00D32D, 3, { 185, 188, 186 } },  /* Route13 grass slot 6: ODDISH / BELLSPROUT / GLOOM */
    { 0x00D32F, 2, {  76, 189,   0 } },  /* Route13 grass slot 7: DITTO / WEEPINBELL */
    { 0x00D331, 3, { 186, 189,  64 } },  /* Route13 grass slot 8: GLOOM / WEEPINBELL / FARFETCHD */
    { 0x00D333, 3, { 186, 189,  64 } },  /* Route13 grass slot 9: GLOOM / WEEPINBELL / FARFETCHD */
    { 0x00D337, 2, { 185, 188,   0 } },  /* Route14 grass slot 0: ODDISH / BELLSPROUT */
    { 0x00D339, 2, {  36, 188,   0 } },  /* Route14 grass slot 1: PIDGEY / BELLSPROUT */
    { 0x00D33B, 2, {  76,  65,   0 } },  /* Route14 grass slot 2: DITTO / VENONAT */
    { 0x00D33D, 2, {  65, 150,   0 } },  /* Route14 grass slot 3: VENONAT / PIDGEOTTO */
    { 0x00D33F, 2, { 185, 188,   0 } },  /* Route14 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00D341, 2, {  65, 188,   0 } },  /* Route14 grass slot 5: VENONAT / BELLSPROUT */
    { 0x00D343, 3, { 185, 188, 186 } },  /* Route14 grass slot 6: ODDISH / BELLSPROUT / GLOOM */
    { 0x00D345, 2, { 186, 189,   0 } },  /* Route14 grass slot 7: GLOOM / WEEPINBELL */
    { 0x00D347, 2, { 150,  65,   0 } },  /* Route14 grass slot 8: PIDGEOTTO / VENONAT */
    { 0x00D349, 2, { 150, 119,   0 } },  /* Route14 grass slot 9: PIDGEOTTO / VENOMOTH */
    { 0x00D34D, 2, { 185, 188,   0 } },  /* Route15 grass slot 0: ODDISH / BELLSPROUT */
    { 0x00D34F, 2, {  76, 188,   0 } },  /* Route15 grass slot 1: DITTO / BELLSPROUT */
    { 0x00D351, 2, {  36,  65,   0 } },  /* Route15 grass slot 2: PIDGEY / VENONAT */
    { 0x00D353, 2, {  65, 150,   0 } },  /* Route15 grass slot 3: VENONAT / PIDGEOTTO */
    { 0x00D355, 2, { 185, 188,   0 } },  /* Route15 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00D357, 2, {  65, 188,   0 } },  /* Route15 grass slot 5: VENONAT / BELLSPROUT */
    { 0x00D359, 3, { 185, 188, 186 } },  /* Route15 grass slot 6: ODDISH / BELLSPROUT / GLOOM */
    { 0x00D35B, 2, { 186, 189,   0 } },  /* Route15 grass slot 7: GLOOM / WEEPINBELL */
    { 0x00D35D, 2, { 150,  65,   0 } },  /* Route15 grass slot 8: PIDGEOTTO / VENONAT */
    { 0x00D35F, 2, { 150, 119,   0 } },  /* Route15 grass slot 9: PIDGEOTTO / VENOMOTH */
    { 0x00D365, 2, {   5,  70,   0 } },  /* Route16 grass slot 1: SPEAROW / DODUO */
    { 0x00D36F, 2, {  70,   5,   0 } },  /* Route16 grass slot 6: DODUO / SPEAROW */
    { 0x00D371, 2, { 165,  35,   0 } },  /* Route16 grass slot 7: RATTATA / FEAROW */
    { 0x00D379, 2, {   5,  70,   0 } },  /* Route17 grass slot 0: SPEAROW / DODUO */
    { 0x00D37B, 2, {   5,  35,   0 } },  /* Route17 grass slot 1: SPEAROW / FEAROW */
    { 0x00D37D, 2, { 166,  70,   0 } },  /* Route17 grass slot 2: RATICATE / DODUO */
    { 0x00D381, 2, { 166, 163,   0 } },  /* Route17 grass slot 4: RATICATE / PONYTA */
    { 0x00D383, 2, {  70, 163,   0 } },  /* Route17 grass slot 5: DODUO / PONYTA */
    { 0x00D385, 2, {  70,  35,   0 } },  /* Route17 grass slot 6: DODUO / FEAROW */
    { 0x00D387, 2, { 166,  70,   0 } },  /* Route17 grass slot 7: RATICATE / DODUO */
    { 0x00D389, 2, {  35, 163,   0 } },  /* Route17 grass slot 8: FEAROW / PONYTA */
    { 0x00D38B, 2, {  35, 116,   0 } },  /* Route17 grass slot 9: FEAROW / DODRIO */
    { 0x00D391, 2, {   5,  70,   0 } },  /* Route18 grass slot 1: SPEAROW / DODUO */
    { 0x00D393, 2, { 166, 165,   0 } },  /* Route18 grass slot 2: RATICATE / RATTATA */
    { 0x00D397, 2, {  35, 165,   0 } },  /* Route18 grass slot 4: FEAROW / RATTATA */
    { 0x00D39B, 2, {  70,   5,   0 } },  /* Route18 grass slot 6: DODUO / SPEAROW */
    { 0x00D39D, 2, { 166,  35,   0 } },  /* Route18 grass slot 7: RATICATE / FEAROW */
    { 0x00D39F, 2, {  35, 166,   0 } },  /* Route18 grass slot 8: FEAROW / RATICATE */
    { 0x00D3A1, 2, {  35, 166,   0 } },  /* Route18 grass slot 9: FEAROW / RATICATE */
    { 0x00D0FB, 2, {  36, 165,   0 } },  /* Route2 grass slot 2: PIDGEY / RATTATA */
    { 0x00D0FD, 2, { 165,   3,   0 } },  /* Route2 grass slot 3: RATTATA / NIDORAN_M */
    { 0x00D0FF, 2, {  36,  15,   0 } },  /* Route2 grass slot 4: PIDGEY / NIDORAN_F */
    { 0x00D101, 3, { 112, 123,  36 } },  /* Route2 grass slot 5: WEEDLE / CATERPIE / PIDGEY */
    { 0x00D103, 2, { 165,   3,   0 } },  /* Route2 grass slot 6: RATTATA / NIDORAN_M */
    { 0x00D105, 2, { 165,  15,   0 } },  /* Route2 grass slot 7: RATTATA / NIDORAN_F */
    { 0x00D107, 3, { 112, 123,  36 } },  /* Route2 grass slot 8: WEEDLE / CATERPIE / PIDGEY */
    { 0x00D109, 3, { 112, 123,  36 } },  /* Route2 grass slot 9: WEEDLE / CATERPIE / PIDGEY */
    { 0x00D4D9, 2, { 165,  36,   0 } },  /* Route21 grass slot 0: RATTATA / PIDGEY */
    { 0x00D4DB, 2, {  36, 165,   0 } },  /* Route21 grass slot 1: PIDGEY / RATTATA */
    { 0x00D4DD, 2, { 166,  36,   0 } },  /* Route21 grass slot 2: RATICATE / PIDGEY */
    { 0x00D4DF, 2, { 165,  36,   0 } },  /* Route21 grass slot 3: RATTATA / PIDGEY */
    { 0x00D4E3, 2, { 150, 165,   0 } },  /* Route21 grass slot 5: PIDGEOTTO / RATTATA */
    { 0x00D4E5, 2, { 150, 166,   0 } },  /* Route21 grass slot 6: PIDGEOTTO / RATICATE */
    { 0x00D4E7, 2, {  30, 150,   0 } },  /* Route21 grass slot 7: TANGELA / PIDGEOTTO */
    { 0x00D4E9, 2, {  30, 150,   0 } },  /* Route21 grass slot 8: TANGELA / PIDGEOTTO */
    { 0x00D4EB, 2, {  30, 150,   0 } },  /* Route21 grass slot 9: TANGELA / PIDGEOTTO */
    { 0x00D10D, 2, { 165,   3,   0 } },  /* Route22 grass slot 0: RATTATA / NIDORAN_M */
    { 0x00D10F, 2, {   3,  15,   0 } },  /* Route22 grass slot 1: NIDORAN_M / NIDORAN_F */
    { 0x00D111, 2, { 165,  57,   0 } },  /* Route22 grass slot 2: RATTATA / MANKEY */
    { 0x00D113, 3, {   3,  15, 165 } },  /* Route22 grass slot 3: NIDORAN_M / NIDORAN_F / RATTATA */
    { 0x00D115, 2, { 165,   3,   0 } },  /* Route22 grass slot 4: RATTATA / NIDORAN_M */
    { 0x00D117, 2, {   3,  15,   0 } },  /* Route22 grass slot 5: NIDORAN_M / NIDORAN_F */
    { 0x00D119, 2, {   5,  57,   0 } },  /* Route22 grass slot 6: SPEAROW / MANKEY */
    { 0x00D11D, 3, {  15,   3,   5 } },  /* Route22 grass slot 8: NIDORAN_F / NIDORAN_M / SPEAROW */
    { 0x00D11F, 3, {  15,   3,   5 } },  /* Route22 grass slot 9: NIDORAN_F / NIDORAN_M / SPEAROW */
    { 0x00D55B, 3, { 108,  96, 167 } },  /* Route23 grass slot 0: EKANS / SANDSHREW / NIDORINO */
    { 0x00D55D, 2, {  76, 168,   0 } },  /* Route23 grass slot 1: DITTO / NIDORINA */
    { 0x00D55F, 2, {   5,  57,   0 } },  /* Route23 grass slot 2: SPEAROW / MANKEY */
    { 0x00D561, 2, {  35, 167,   0 } },  /* Route23 grass slot 3: FEAROW / NIDORINO */
    { 0x00D563, 2, {  76, 168,   0 } },  /* Route23 grass slot 4: DITTO / NIDORINA */
    { 0x00D567, 3, {  45,  97,  57 } },  /* Route23 grass slot 6: ARBOK / SANDSLASH / MANKEY */
    { 0x00D569, 2, {  76,  35,   0 } },  /* Route23 grass slot 7: DITTO / FEAROW */
    { 0x00D56B, 2, {  35, 117,   0 } },  /* Route23 grass slot 8: FEAROW / PRIMEAPE */
    { 0x00D56D, 2, {  35, 117,   0 } },  /* Route23 grass slot 9: FEAROW / PRIMEAPE */
    { 0x00D1A7, 3, { 112, 123, 185 } },  /* Route24 grass slot 0: WEEDLE / CATERPIE / ODDISH */
    { 0x00D1A9, 3, { 113, 124, 188 } },  /* Route24 grass slot 1: KAKUNA / METAPOD / BELLSPROUT */
    { 0x00D1AD, 2, { 185, 188,   0 } },  /* Route24 grass slot 3: ODDISH / BELLSPROUT */
    { 0x00D1AF, 2, { 185, 188,   0 } },  /* Route24 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00D1B1, 2, { 148,  36,   0 } },  /* Route24 grass slot 5: ABRA / PIDGEY */
    { 0x00D1B3, 3, { 185, 188,  65 } },  /* Route24 grass slot 6: ODDISH / BELLSPROUT / VENONAT */
    { 0x00D1B5, 2, {  36,  65,   0 } },  /* Route24 grass slot 7: PIDGEY / VENONAT */
    { 0x00D1B7, 2, { 148,  36,   0 } },  /* Route24 grass slot 8: ABRA / PIDGEY */
    { 0x00D1B9, 2, { 148, 150,   0 } },  /* Route24 grass slot 9: ABRA / PIDGEOTTO */
    { 0x00D1BD, 3, { 112, 123, 185 } },  /* Route25 grass slot 0: WEEDLE / CATERPIE / ODDISH */
    { 0x00D1BF, 3, { 113, 124, 188 } },  /* Route25 grass slot 1: KAKUNA / METAPOD / BELLSPROUT */
    { 0x00D1C3, 2, { 185, 188,   0 } },  /* Route25 grass slot 3: ODDISH / BELLSPROUT */
    { 0x00D1C5, 2, { 185, 188,   0 } },  /* Route25 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00D1C7, 2, { 148,  36,   0 } },  /* Route25 grass slot 5: ABRA / PIDGEY */
    { 0x00D1C9, 3, { 185, 188,  65 } },  /* Route25 grass slot 6: ODDISH / BELLSPROUT / VENONAT */
    { 0x00D1CB, 2, { 148,  65,   0 } },  /* Route25 grass slot 7: ABRA / VENONAT */
    { 0x00D1CD, 3, { 124, 113,  36 } },  /* Route25 grass slot 8: METAPOD / KAKUNA / PIDGEY */
    { 0x00D1CF, 3, { 123, 112, 150 } },  /* Route25 grass slot 9: CATERPIE / WEEDLE / PIDGEOTTO */
    { 0x00D139, 2, {  36,   5,   0 } },  /* Route3 grass slot 0: PIDGEY / SPEAROW */
    { 0x00D13D, 2, {  36,  57,   0 } },  /* Route3 grass slot 2: PIDGEY / MANKEY */
    { 0x00D141, 2, {   5,  96,   0 } },  /* Route3 grass slot 4: SPEAROW / SANDSHREW */
    { 0x00D143, 2, {  36, 165,   0 } },  /* Route3 grass slot 5: PIDGEY / RATTATA */
    { 0x00D145, 2, {   5,  96,   0 } },  /* Route3 grass slot 6: SPEAROW / SANDSHREW */
    { 0x00D147, 2, { 100, 165,   0 } },  /* Route3 grass slot 7: JIGGLYPUFF / RATTATA */
    { 0x00D149, 2, { 100,   5,   0 } },  /* Route3 grass slot 8: JIGGLYPUFF / SPEAROW */
    { 0x00D14B, 2, { 100,   5,   0 } },  /* Route3 grass slot 9: JIGGLYPUFF / SPEAROW */
    { 0x00D191, 2, { 165,   5,   0 } },  /* Route4 grass slot 0: RATTATA / SPEAROW */
    { 0x00D195, 2, { 165,  57,   0 } },  /* Route4 grass slot 2: RATTATA / MANKEY */
    { 0x00D197, 3, { 108,  96,   5 } },  /* Route4 grass slot 3: EKANS / SANDSHREW / SPEAROW */
    { 0x00D199, 2, {   5,  96,   0 } },  /* Route4 grass slot 4: SPEAROW / SANDSHREW */
    { 0x00D19B, 3, { 108,  96, 165 } },  /* Route4 grass slot 5: EKANS / SANDSHREW / RATTATA */
    { 0x00D19D, 2, { 165,  96,   0 } },  /* Route4 grass slot 6: RATTATA / SANDSHREW */
    { 0x00D19F, 2, {   5, 165,   0 } },  /* Route4 grass slot 7: SPEAROW / RATTATA */
    { 0x00D1A1, 3, { 108,  96,   5 } },  /* Route4 grass slot 8: EKANS / SANDSHREW / SPEAROW */
    { 0x00D1A3, 3, { 108,  96,   5 } },  /* Route4 grass slot 9: EKANS / SANDSHREW / SPEAROW */
    { 0x00D1E9, 3, { 185, 188,  36 } },  /* Route5 grass slot 0: ODDISH / BELLSPROUT / PIDGEY */
    { 0x00D1EB, 2, {  36, 165,   0 } },  /* Route5 grass slot 1: PIDGEY / RATTATA */
    { 0x00D1ED, 2, {  36, 148,   0 } },  /* Route5 grass slot 2: PIDGEY / ABRA */
    { 0x00D1EF, 3, {  57,  77,  36 } },  /* Route5 grass slot 3: MANKEY / MEOWTH / PIDGEY */
    { 0x00D1F1, 3, {  57,  77, 165 } },  /* Route5 grass slot 4: MANKEY / MEOWTH / RATTATA */
    { 0x00D1F3, 3, { 185, 188,  36 } },  /* Route5 grass slot 5: ODDISH / BELLSPROUT / PIDGEY */
    { 0x00D1F5, 3, { 185, 188, 150 } },  /* Route5 grass slot 6: ODDISH / BELLSPROUT / PIDGEOTTO */
    { 0x00D1F7, 2, {  36, 100,   0 } },  /* Route5 grass slot 7: PIDGEY / JIGGLYPUFF */
    { 0x00D1F9, 3, {  57,  77, 100 } },  /* Route5 grass slot 8: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00D1FB, 3, {  57,  77, 100 } },  /* Route5 grass slot 9: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00D1FF, 3, { 185, 188,  36 } },  /* Route6 grass slot 0: ODDISH / BELLSPROUT / PIDGEY */
    { 0x00D201, 2, {  36, 165,   0 } },  /* Route6 grass slot 1: PIDGEY / RATTATA */
    { 0x00D203, 2, {  36, 148,   0 } },  /* Route6 grass slot 2: PIDGEY / ABRA */
    { 0x00D205, 3, {  57,  77,  36 } },  /* Route6 grass slot 3: MANKEY / MEOWTH / PIDGEY */
    { 0x00D207, 3, {  57,  77, 165 } },  /* Route6 grass slot 4: MANKEY / MEOWTH / RATTATA */
    { 0x00D209, 3, { 185, 188,  36 } },  /* Route6 grass slot 5: ODDISH / BELLSPROUT / PIDGEY */
    { 0x00D20B, 3, { 185, 188, 150 } },  /* Route6 grass slot 6: ODDISH / BELLSPROUT / PIDGEOTTO */
    { 0x00D20D, 2, {  36, 100,   0 } },  /* Route6 grass slot 7: PIDGEY / JIGGLYPUFF */
    { 0x00D20F, 3, {  57,  77, 100 } },  /* Route6 grass slot 8: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00D211, 3, {  57,  77, 100 } },  /* Route6 grass slot 9: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00D29B, 3, { 185, 188,  36 } },  /* Route7 grass slot 1: ODDISH / BELLSPROUT / PIDGEY */
    { 0x00D29D, 3, {  57,  77, 165 } },  /* Route7 grass slot 2: MANKEY / MEOWTH / RATTATA */
    { 0x00D29F, 3, { 185, 188, 148 } },  /* Route7 grass slot 3: ODDISH / BELLSPROUT / ABRA */
    { 0x00D2A1, 2, {  36, 148,   0 } },  /* Route7 grass slot 4: PIDGEY / ABRA */
    { 0x00D2A3, 3, {  57,  77, 150 } },  /* Route7 grass slot 5: MANKEY / MEOWTH / PIDGEOTTO */
    { 0x00D2A5, 3, {  33,  82, 148 } },  /* Route7 grass slot 6: GROWLITHE / VULPIX / ABRA */
    { 0x00D2A7, 3, {  33,  82, 100 } },  /* Route7 grass slot 7: GROWLITHE / VULPIX / JIGGLYPUFF */
    { 0x00D2A9, 3, {  57,  77, 100 } },  /* Route7 grass slot 8: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00D2AB, 3, {  57,  77, 100 } },  /* Route7 grass slot 9: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00D285, 3, {  57,  77,  36 } },  /* Route8 grass slot 1: MANKEY / MEOWTH / PIDGEY */
    { 0x00D287, 3, { 108,  96, 165 } },  /* Route8 grass slot 2: EKANS / SANDSHREW / RATTATA */
    { 0x00D289, 3, {  33,  82, 148 } },  /* Route8 grass slot 3: GROWLITHE / VULPIX / ABRA */
    { 0x00D28B, 2, {  36, 148,   0 } },  /* Route8 grass slot 4: PIDGEY / ABRA */
    { 0x00D28D, 3, {  57,  77, 150 } },  /* Route8 grass slot 5: MANKEY / MEOWTH / PIDGEOTTO */
    { 0x00D28F, 3, { 108,  96, 100 } },  /* Route8 grass slot 6: EKANS / SANDSHREW / JIGGLYPUFF */
    { 0x00D291, 3, {  33,  82, 100 } },  /* Route8 grass slot 7: GROWLITHE / VULPIX / JIGGLYPUFF */
    { 0x00D293, 3, {  33,  82,  38 } },  /* Route8 grass slot 8: GROWLITHE / VULPIX / KADABRA */
    { 0x00D295, 3, {  33,  82,  38 } },  /* Route8 grass slot 9: GROWLITHE / VULPIX / KADABRA */
    { 0x00D1D3, 2, { 165,   3,   0 } },  /* Route9 grass slot 0: RATTATA / NIDORAN_M */
    { 0x00D1D5, 2, {   5,  15,   0 } },  /* Route9 grass slot 1: SPEAROW / NIDORAN_F */
    { 0x00D1D9, 3, { 108,  96,   3 } },  /* Route9 grass slot 3: EKANS / SANDSHREW / NIDORAN_M */
    { 0x00D1DB, 2, {   5,  15,   0 } },  /* Route9 grass slot 4: SPEAROW / NIDORAN_F */
    { 0x00D1DD, 3, { 108,  96,   5 } },  /* Route9 grass slot 5: EKANS / SANDSHREW / SPEAROW */
    { 0x00D1DF, 2, { 165, 167,   0 } },  /* Route9 grass slot 6: RATTATA / NIDORINO */
    { 0x00D1E1, 2, {   5, 168,   0 } },  /* Route9 grass slot 7: SPEAROW / NIDORINA */
    { 0x00D1E3, 3, { 108,  96, 166 } },  /* Route9 grass slot 8: EKANS / SANDSHREW / RATICATE */
    { 0x00D1E5, 3, { 108,  96,  35 } },  /* Route9 grass slot 9: EKANS / SANDSHREW / FEAROW */
    { 0x00D3A5, 2, {   3,  15,   0 } },  /* SafariZoneCenter grass slot 0: NIDORAN_M / NIDORAN_F */
    { 0x00D3A7, 2, {  18,  15,   0 } },  /* SafariZoneCenter grass slot 1: RHYHORN / NIDORAN_F */
    { 0x00D3A9, 2, {  65,  12,   0 } },  /* SafariZoneCenter grass slot 2: VENONAT / EXEGGCUTE */
    { 0x00D3AB, 2, {  12,  18,   0 } },  /* SafariZoneCenter grass slot 3: EXEGGCUTE / RHYHORN */
    { 0x00D3AD, 2, { 167, 168,   0 } },  /* SafariZoneCenter grass slot 4: NIDORINO / NIDORINA */
    { 0x00D3AF, 2, {  12,  46,   0 } },  /* SafariZoneCenter grass slot 5: EXEGGCUTE / PARASECT */
    { 0x00D3B1, 3, { 168, 167, 109 } },  /* SafariZoneCenter grass slot 6: NIDORINA / NIDORINO / PARAS */
    { 0x00D3B5, 3, {  26,  29,  30 } },  /* SafariZoneCenter grass slot 8: SCYTHER / PINSIR / TANGELA */
    { 0x00D3BB, 2, {   3,  15,   0 } },  /* SafariZoneEast grass slot 0: NIDORAN_M / NIDORAN_F */
    { 0x00D3BD, 2, {  70,  15,   0 } },  /* SafariZoneEast grass slot 1: DODUO / NIDORAN_F */
    { 0x00D3BF, 2, { 109,  12,   0 } },  /* SafariZoneEast grass slot 2: PARAS / EXEGGCUTE */
    { 0x00D3C1, 2, {  12,  60,   0 } },  /* SafariZoneEast grass slot 3: EXEGGCUTE / TAUROS */
    { 0x00D3C3, 2, { 167, 168,   0 } },  /* SafariZoneEast grass slot 4: NIDORINO / NIDORINA */
    { 0x00D3C5, 2, {  12,  17,   0 } },  /* SafariZoneEast grass slot 5: EXEGGCUTE / CUBONE */
    { 0x00D3C7, 3, {  15,   3,  12 } },  /* SafariZoneEast grass slot 6: NIDORAN_F / NIDORAN_M / EXEGGCUTE */
    { 0x00D3C9, 2, {  46, 145,   0 } },  /* SafariZoneEast grass slot 7: PARASECT / MAROWAK */
    { 0x00D3CB, 2, {   2,  40,   0 } },  /* SafariZoneEast grass slot 8: KANGASKHAN / CHANSEY */
    { 0x00D3CD, 2, {  26,  29,   0 } },  /* SafariZoneEast grass slot 9: SCYTHER / PINSIR */
    { 0x00D3D1, 2, {   3,  15,   0 } },  /* SafariZoneNorth grass slot 0: NIDORAN_M / NIDORAN_F */
    { 0x00D3D3, 2, {  18,  15,   0 } },  /* SafariZoneNorth grass slot 1: RHYHORN / NIDORAN_F */
    { 0x00D3D5, 2, { 109,  12,   0 } },  /* SafariZoneNorth grass slot 2: PARAS / EXEGGCUTE */
    { 0x00D3D7, 2, {  12,  18,   0 } },  /* SafariZoneNorth grass slot 3: EXEGGCUTE / RHYHORN */
    { 0x00D3D9, 2, { 167, 168,   0 } },  /* SafariZoneNorth grass slot 4: NIDORINO / NIDORINA */
    { 0x00D3DB, 2, {  12,   2,   0 } },  /* SafariZoneNorth grass slot 5: EXEGGCUTE / KANGASKHAN */
    { 0x00D3DD, 3, { 168, 167,  17 } },  /* SafariZoneNorth grass slot 6: NIDORINA / NIDORINO / CUBONE */
    { 0x00D3DF, 2, { 119,   2,   0 } },  /* SafariZoneNorth grass slot 7: VENOMOTH / KANGASKHAN */
    { 0x00D3E1, 2, {  40,  26,   0 } },  /* SafariZoneNorth grass slot 8: CHANSEY / SCYTHER */
    { 0x00D3E3, 2, {  60,  29,   0 } },  /* SafariZoneNorth grass slot 9: TAUROS / PINSIR */
    { 0x00D3E7, 2, {   3,  15,   0 } },  /* SafariZoneWest grass slot 0: NIDORAN_M / NIDORAN_F */
    { 0x00D3E9, 2, {  70,  15,   0 } },  /* SafariZoneWest grass slot 1: DODUO / NIDORAN_F */
    { 0x00D3EB, 2, {  65,  12,   0 } },  /* SafariZoneWest grass slot 2: VENONAT / EXEGGCUTE */
    { 0x00D3ED, 2, {  12,  60,   0 } },  /* SafariZoneWest grass slot 3: EXEGGCUTE / TAUROS */
    { 0x00D3EF, 2, { 167, 168,   0 } },  /* SafariZoneWest grass slot 4: NIDORINO / NIDORINA */
    { 0x00D3F1, 2, {  12,  17,   0 } },  /* SafariZoneWest grass slot 5: EXEGGCUTE / CUBONE */
    { 0x00D3F3, 3, {  15,   3,  12 } },  /* SafariZoneWest grass slot 6: NIDORAN_F / NIDORAN_M / EXEGGCUTE */
    { 0x00D3F5, 2, { 119, 145,   0 } },  /* SafariZoneWest grass slot 7: VENOMOTH / MAROWAK */
    { 0x00D3F7, 2, {  60,  29,   0 } },  /* SafariZoneWest grass slot 8: TAUROS / PINSIR */
    { 0x00D3F9, 2, {   2,  30,   0 } },  /* SafariZoneWest grass slot 9: KANGASKHAN / TANGELA */
    { 0x00D413, 2, {  58, 107,   0 } },  /* SeafoamIslands1F grass slot 0: SEEL / ZUBAT */
    { 0x00D415, 3, {  37,  47,  78 } },  /* SeafoamIslands1F grass slot 1: SLOWPOKE / PSYDUCK / KRABBY */
    { 0x00D417, 3, {  23,  27,  78 } },  /* SeafoamIslands1F grass slot 2: SHELLDER / STARYU / KRABBY */
    { 0x00D419, 3, {  92,  78, 107 } },  /* SeafoamIslands1F grass slot 3: HORSEA / KRABBY / ZUBAT */
    { 0x00D41B, 3, {  92,  78, 107 } },  /* SeafoamIslands1F grass slot 4: HORSEA / KRABBY / ZUBAT */
    { 0x00D41D, 2, { 107,  37,   0 } },  /* SeafoamIslands1F grass slot 5: ZUBAT / SLOWPOKE */
    { 0x00D41F, 2, { 130,  37,   0 } },  /* SeafoamIslands1F grass slot 6: GOLBAT / SLOWPOKE */
    { 0x00D421, 3, {  47,  37, 107 } },  /* SeafoamIslands1F grass slot 7: PSYDUCK / SLOWPOKE / ZUBAT */
    { 0x00D423, 3, {  23,  27, 130 } },  /* SeafoamIslands1F grass slot 8: SHELLDER / STARYU / GOLBAT */
    { 0x00D425, 3, { 128,   8, 130 } },  /* SeafoamIslands1F grass slot 9: GOLDUCK / SLOWBRO / GOLBAT */
    { 0x00D429, 3, {  27,  23, 107 } },  /* SeafoamIslandsB1F grass slot 0: STARYU / SHELLDER / ZUBAT */
    { 0x00D42B, 2, {  92,  78,   0 } },  /* SeafoamIslandsB1F grass slot 1: HORSEA / KRABBY */
    { 0x00D42D, 3, {  23,  27, 107 } },  /* SeafoamIslandsB1F grass slot 2: SHELLDER / STARYU / ZUBAT */
    { 0x00D42F, 2, {  92,  78,   0 } },  /* SeafoamIslandsB1F grass slot 3: HORSEA / KRABBY */
    { 0x00D431, 3, {  37,  47, 130 } },  /* SeafoamIslandsB1F grass slot 4: SLOWPOKE / PSYDUCK / GOLBAT */
    { 0x00D433, 2, {  58,  37,   0 } },  /* SeafoamIslandsB1F grass slot 5: SEEL / SLOWPOKE */
    { 0x00D435, 3, {  37,  47, 107 } },  /* SeafoamIslandsB1F grass slot 6: SLOWPOKE / PSYDUCK / ZUBAT */
    { 0x00D437, 2, {  58, 138,   0 } },  /* SeafoamIslandsB1F grass slot 7: SEEL / KINGLER */
    { 0x00D439, 2, { 120,  58,   0 } },  /* SeafoamIslandsB1F grass slot 8: DEWGONG / SEEL */
    { 0x00D43B, 3, {  93, 138,  58 } },  /* SeafoamIslandsB1F grass slot 9: SEADRA / KINGLER / SEEL */
    { 0x00D43F, 2, {  58, 107,   0 } },  /* SeafoamIslandsB2F grass slot 0: SEEL / ZUBAT */
    { 0x00D441, 3, {  37,  47,  78 } },  /* SeafoamIslandsB2F grass slot 1: SLOWPOKE / PSYDUCK / KRABBY */
    { 0x00D443, 2, {  58, 107,   0 } },  /* SeafoamIslandsB2F grass slot 2: SEEL / ZUBAT */
    { 0x00D445, 3, {  37,  47, 130 } },  /* SeafoamIslandsB2F grass slot 3: SLOWPOKE / PSYDUCK / GOLBAT */
    { 0x00D447, 3, {  92,  78, 138 } },  /* SeafoamIslandsB2F grass slot 4: HORSEA / KRABBY / KINGLER */
    { 0x00D449, 3, {  27,  23,  58 } },  /* SeafoamIslandsB2F grass slot 5: STARYU / SHELLDER / SEEL */
    { 0x00D44B, 2, {  92,  78,   0 } },  /* SeafoamIslandsB2F grass slot 6: HORSEA / KRABBY */
    { 0x00D44D, 3, {  23,  27, 130 } },  /* SeafoamIslandsB2F grass slot 7: SHELLDER / STARYU / GOLBAT */
    { 0x00D44F, 2, { 130,  37,   0 } },  /* SeafoamIslandsB2F grass slot 8: GOLBAT / SLOWPOKE */
    { 0x00D451, 2, {   8, 128,   0 } },  /* SeafoamIslandsB2F grass slot 9: SLOWBRO / GOLDUCK */
    { 0x00D455, 3, {  37,  47, 130 } },  /* SeafoamIslandsB3F grass slot 0: SLOWPOKE / PSYDUCK / GOLBAT */
    { 0x00D457, 2, {  58, 107,   0 } },  /* SeafoamIslandsB3F grass slot 1: SEEL / ZUBAT */
    { 0x00D459, 3, {  37,  47,  78 } },  /* SeafoamIslandsB3F grass slot 2: SLOWPOKE / PSYDUCK / KRABBY */
    { 0x00D45B, 2, {  58, 107,   0 } },  /* SeafoamIslandsB3F grass slot 3: SEEL / ZUBAT */
    { 0x00D45D, 3, {  92,  78, 138 } },  /* SeafoamIslandsB3F grass slot 4: HORSEA / KRABBY / KINGLER */
    { 0x00D45F, 3, {  23,  27,  58 } },  /* SeafoamIslandsB3F grass slot 5: SHELLDER / STARYU / SEEL */
    { 0x00D461, 2, {  92,  78,   0 } },  /* SeafoamIslandsB3F grass slot 6: HORSEA / KRABBY */
    { 0x00D463, 3, {  23,  27,  58 } },  /* SeafoamIslandsB3F grass slot 7: SHELLDER / STARYU / SEEL */
    { 0x00D465, 3, {  93, 138, 120 } },  /* SeafoamIslandsB3F grass slot 8: SEADRA / KINGLER / DEWGONG */
    { 0x00D46B, 3, {  92,  78, 130 } },  /* SeafoamIslandsB4F grass slot 0: HORSEA / KRABBY / GOLBAT */
    { 0x00D46D, 3, {  23,  27, 107 } },  /* SeafoamIslandsB4F grass slot 1: SHELLDER / STARYU / ZUBAT */
    { 0x00D46F, 2, {  92,  78,   0 } },  /* SeafoamIslandsB4F grass slot 2: HORSEA / KRABBY */
    { 0x00D471, 3, {  23,  27, 138 } },  /* SeafoamIslandsB4F grass slot 3: SHELLDER / STARYU / KINGLER */
    { 0x00D473, 3, {  37,  47,  58 } },  /* SeafoamIslandsB4F grass slot 4: SLOWPOKE / PSYDUCK / SEEL */
    { 0x00D477, 3, {  37,  47, 130 } },  /* SeafoamIslandsB4F grass slot 6: SLOWPOKE / PSYDUCK / GOLBAT */
    { 0x00D479, 2, {  58, 107,   0 } },  /* SeafoamIslandsB4F grass slot 7: SEEL / ZUBAT */
    { 0x00D47B, 3, {   8, 128, 120 } },  /* SeafoamIslandsB4F grass slot 8: SLOWBRO / GOLDUCK / DEWGONG */
    { 0x00D47D, 2, { 130, 120,   0 } },  /* SeafoamIslandsB4F grass slot 9: GOLBAT / DEWGONG */
    { 0x00D59D, 2, { 106, 169,   0 } },  /* VictoryRoad1F grass slot 0: MACHOP / GEODUDE */
    { 0x00D5A1, 2, { 107, 169,   0 } },  /* VictoryRoad1F grass slot 2: ZUBAT / GEODUDE */
    { 0x00D5A3, 2, {  34, 107,   0 } },  /* VictoryRoad1F grass slot 3: ONIX / ZUBAT */
    { 0x00D5A5, 2, {  34, 107,   0 } },  /* VictoryRoad1F grass slot 4: ONIX / ZUBAT */
    { 0x00D5A7, 2, {  34, 169,   0 } },  /* VictoryRoad1F grass slot 5: ONIX / GEODUDE */
    { 0x00D5A9, 2, {  39,  34,   0 } },  /* VictoryRoad1F grass slot 6: GRAVELER / ONIX */
    { 0x00D5AB, 2, { 130,  34,   0 } },  /* VictoryRoad1F grass slot 7: GOLBAT / ONIX */
    { 0x00D5AD, 2, {  41,  39,   0 } },  /* VictoryRoad1F grass slot 8: MACHOKE / GRAVELER */
    { 0x00D5AF, 2, { 145,  39,   0 } },  /* VictoryRoad1F grass slot 9: MAROWAK / GRAVELER */
    { 0x00D571, 2, { 106, 169,   0 } },  /* VictoryRoad2F grass slot 0: MACHOP / GEODUDE */
    { 0x00D575, 2, { 107, 169,   0 } },  /* VictoryRoad2F grass slot 2: ZUBAT / GEODUDE */
    { 0x00D577, 2, {  34, 107,   0 } },  /* VictoryRoad2F grass slot 3: ONIX / ZUBAT */
    { 0x00D579, 2, {  34, 130,   0 } },  /* VictoryRoad2F grass slot 4: ONIX / GOLBAT */
    { 0x00D57B, 2, {  34,  39,   0 } },  /* VictoryRoad2F grass slot 5: ONIX / GRAVELER */
    { 0x00D57D, 2, {  41,  34,   0 } },  /* VictoryRoad2F grass slot 6: MACHOKE / ONIX */
    { 0x00D57F, 2, { 130,  34,   0 } },  /* VictoryRoad2F grass slot 7: GOLBAT / ONIX */
    { 0x00D581, 2, { 145,  41,   0 } },  /* VictoryRoad2F grass slot 8: MAROWAK / MACHOKE */
    { 0x00D583, 2, {  39,  41,   0 } },  /* VictoryRoad2F grass slot 9: GRAVELER / MACHOKE */
    { 0x00D587, 2, { 106, 169,   0 } },  /* VictoryRoad3F grass slot 0: MACHOP / GEODUDE */
    { 0x00D589, 2, { 169, 130,   0 } },  /* VictoryRoad3F grass slot 1: GEODUDE / GOLBAT */
    { 0x00D58B, 2, { 107, 169,   0 } },  /* VictoryRoad3F grass slot 2: ZUBAT / GEODUDE */
    { 0x00D58F, 2, { 119, 169,   0 } },  /* VictoryRoad3F grass slot 4: VENOMOTH / GEODUDE */
    { 0x00D591, 2, {  34,  39,   0 } },  /* VictoryRoad3F grass slot 5: ONIX / GRAVELER */
    { 0x00D593, 2, {  39,  41,   0 } },  /* VictoryRoad3F grass slot 6: GRAVELER / MACHOKE */
    { 0x00D595, 2, { 130,  41,   0 } },  /* VictoryRoad3F grass slot 7: GOLBAT / MACHOKE */
    { 0x00D597, 2, {  41,  39,   0 } },  /* VictoryRoad3F grass slot 8: MACHOKE / GRAVELER */
    { 0x00D599, 2, {  41,  39,   0 } },  /* VictoryRoad3F grass slot 9: MACHOKE / GRAVELER */
    { 0x00D123, 2, { 112, 123,   0 } },  /* ViridianForest grass slot 0: WEEDLE / CATERPIE */
    { 0x00D125, 2, { 113, 124,   0 } },  /* ViridianForest grass slot 1: KAKUNA / METAPOD */
    { 0x00D127, 2, { 112, 123,   0 } },  /* ViridianForest grass slot 2: WEEDLE / CATERPIE */
    { 0x00D129, 2, { 112, 123,   0 } },  /* ViridianForest grass slot 3: WEEDLE / CATERPIE */
    { 0x00D12B, 3, { 113, 124,  36 } },  /* ViridianForest grass slot 4: KAKUNA / METAPOD / PIDGEY */
    { 0x00D12D, 3, { 113, 124,  36 } },  /* ViridianForest grass slot 5: KAKUNA / METAPOD / PIDGEY */
    { 0x00D12F, 3, { 124, 113, 123 } },  /* ViridianForest grass slot 6: METAPOD / KAKUNA / CATERPIE */
    { 0x00D131, 3, { 123, 112, 124 } },  /* ViridianForest grass slot 7: CATERPIE / WEEDLE / METAPOD */
    { 0x00D133, 2, {  84,  36,   0 } },  /* ViridianForest grass slot 8: PIKACHU / PIDGEY */
    { 0x00D135, 2, {  84, 150,   0 } },  /* ViridianForest grass slot 9: PIKACHU / PIDGEOTTO */
};

#endif /* GEN1_WILD_DIFFS_RB_GEN_H */
