/* AUTO-GENERATED by runtime/tools/generate_wild_diffs.py.
 * Source: pret/pokeyellow (Yellow ROM).
 * Do not edit by hand. Re-run the script if pret
 * sources change. */

#ifndef GEN1_WILD_DIFFS_YELLOW_GEN_H
#define GEN1_WILD_DIFFS_YELLOW_GEN_H

#include <stdint.h>

#ifndef GBGEN1_WILDDIFF_STRUCT_DEFINED
#define GBGEN1_WILDDIFF_STRUCT_DEFINED
typedef struct {
    uint32_t rom_offset;
    uint8_t  count;          /* 2 or 3 candidate species */
    uint8_t  species[3];
} GBGen1WildDiff;
#endif

#define GEN1_WILD_DIFFS_YELLOW_COUNT  432

static const GBGen1WildDiff GEN1_WILD_DIFFS_YELLOW[GEN1_WILD_DIFFS_YELLOW_COUNT] = {
    { 0x00D22B, 2, { 129, 130,   0 } },  /* CeruleanCave1F grass slot 1: HYPNO / GOLBAT */
    { 0x00D22D, 2, {  54,  39,   0 } },  /* CeruleanCave1F grass slot 2: MAGNETON / GRAVELER */
    { 0x00D22F, 2, { 116, 186,   0 } },  /* CeruleanCave1F grass slot 3: DODRIO / GLOOM */
    { 0x00D231, 2, { 119, 189,   0 } },  /* CeruleanCave1F grass slot 4: VENOMOTH / WEEPINBELL */
    { 0x00D233, 2, {  45,  97,   0 } },  /* CeruleanCave1F grass slot 5: ARBOK / SANDSLASH */
    { 0x00D235, 2, {  38, 119,   0 } },  /* CeruleanCave1F grass slot 6: KADABRA / VENOMOTH */
    { 0x00D239, 2, {  85,  76,   0 } },  /* CeruleanCave1F grass slot 8: RAICHU / DITTO */
    { 0x00D23F, 2, { 116, 130,   0 } },  /* CeruleanCave2F grass slot 0: DODRIO / GOLBAT */
    { 0x00D241, 2, { 119, 130,   0 } },  /* CeruleanCave2F grass slot 1: VENOMOTH / GOLBAT */
    { 0x00D243, 2, {  38,  39,   0 } },  /* CeruleanCave2F grass slot 2: KADABRA / GRAVELER */
    { 0x00D245, 2, {   1,  97,   0 } },  /* CeruleanCave2F grass slot 3: RHYDON / SANDSLASH */
    { 0x00D247, 2, { 145,  18,   0 } },  /* CeruleanCave2F grass slot 4: MAROWAK / RHYHORN */
    { 0x00D249, 2, { 141,  76,   0 } },  /* CeruleanCave2F grass slot 5: ELECTRODE / DITTO */
    { 0x00D24B, 2, {  40, 186,   0 } },  /* CeruleanCave2F grass slot 6: CHANSEY / GLOOM */
    { 0x00D24D, 2, { 101, 189,   0 } },  /* CeruleanCave2F grass slot 7: WIGGLYTUFF / WEEPINBELL */
    { 0x00D24F, 2, {  76,   1,   0 } },  /* CeruleanCave2F grass slot 8: DITTO / RHYDON */
    { 0x00D251, 2, {  76,   1,   0 } },  /* CeruleanCave2F grass slot 9: DITTO / RHYDON */
    { 0x00D255, 2, {   1, 130,   0 } },  /* CeruleanCaveB1F grass slot 0: RHYDON / GOLBAT */
    { 0x00D257, 2, { 145, 130,   0 } },  /* CeruleanCaveB1F grass slot 1: MAROWAK / GOLBAT */
    { 0x00D259, 2, { 141,  39,   0 } },  /* CeruleanCaveB1F grass slot 2: ELECTRODE / GRAVELER */
    { 0x00D25B, 2, {  40,  18,   0 } },  /* CeruleanCaveB1F grass slot 3: CHANSEY / RHYHORN */
    { 0x00D25D, 2, {  46,   1,   0 } },  /* CeruleanCaveB1F grass slot 4: PARASECT / RHYDON */
    { 0x00D25F, 2, {  85,  76,   0 } },  /* CeruleanCaveB1F grass slot 5: RAICHU / DITTO */
    { 0x00D261, 3, {  45,  97,  40 } },  /* CeruleanCaveB1F grass slot 6: ARBOK / SANDSLASH / CHANSEY */
    { 0x00D265, 2, {  76,  11,   0 } },  /* CeruleanCaveB1F grass slot 8: DITTO / LICKITUNG */
    { 0x00D267, 2, {  76,  11,   0 } },  /* CeruleanCaveB1F grass slot 9: DITTO / LICKITUNG */
    { 0x00CDFF, 2, { 107, 169,   0 } },  /* MtMoon1F grass slot 2: ZUBAT / GEODUDE */
    { 0x00CE01, 2, { 169, 107,   0 } },  /* MtMoon1F grass slot 3: GEODUDE / ZUBAT */
    { 0x00CE09, 2, { 109, 107,   0 } },  /* MtMoon1F grass slot 7: PARAS / ZUBAT */
    { 0x00CE0B, 2, { 107,  96,   0 } },  /* MtMoon1F grass slot 8: ZUBAT / SANDSHREW */
    { 0x00CE15, 2, { 169, 107,   0 } },  /* MtMoonB1F grass slot 2: GEODUDE / ZUBAT */
    { 0x00CE19, 2, { 107, 169,   0 } },  /* MtMoonB1F grass slot 4: ZUBAT / GEODUDE */
    { 0x00CE1B, 2, { 109, 107,   0 } },  /* MtMoonB1F grass slot 5: PARAS / ZUBAT */
    { 0x00CE1D, 2, { 107, 109,   0 } },  /* MtMoonB1F grass slot 6: ZUBAT / PARAS */
    { 0x00CE1F, 2, { 107, 109,   0 } },  /* MtMoonB1F grass slot 7: ZUBAT / PARAS */
    { 0x00CE23, 2, { 169,   4,   0 } },  /* MtMoonB1F grass slot 9: GEODUDE / CLEFAIRY */
    { 0x00CE2B, 2, { 107, 109,   0 } },  /* MtMoonB2F grass slot 2: ZUBAT / PARAS */
    { 0x00CE2D, 2, { 169, 107,   0 } },  /* MtMoonB2F grass slot 3: GEODUDE / ZUBAT */
    { 0x00CE31, 2, { 109, 107,   0 } },  /* MtMoonB2F grass slot 5: PARAS / ZUBAT */
    { 0x00CE33, 2, { 109, 107,   0 } },  /* MtMoonB2F grass slot 6: PARAS / ZUBAT */
    { 0x00CE37, 2, { 107,   4,   0 } },  /* MtMoonB2F grass slot 8: ZUBAT / CLEFAIRY */
    { 0x00D1A7, 3, {  55,  13, 165 } },  /* PokemonMansion1F grass slot 0: KOFFING / GRIMER / RATTATA */
    { 0x00D1A9, 3, {  55,  13, 166 } },  /* PokemonMansion1F grass slot 1: KOFFING / GRIMER / RATICATE */
    { 0x00D1AB, 2, { 163,  13,   0 } },  /* PokemonMansion1F grass slot 2: PONYTA / GRIMER */
    { 0x00D1AD, 2, { 163,  33,   0 } },  /* PokemonMansion1F grass slot 3: PONYTA / GROWLITHE */
    { 0x00D1AF, 3, {  33,  82, 165 } },  /* PokemonMansion1F grass slot 4: GROWLITHE / VULPIX / RATTATA */
    { 0x00D1B1, 2, { 163, 166,   0 } },  /* PokemonMansion1F grass slot 5: PONYTA / RATICATE */
    { 0x00D1B3, 3, {  13,  55,  33 } },  /* PokemonMansion1F grass slot 6: GRIMER / KOFFING / GROWLITHE */
    { 0x00D1B5, 2, { 163,  13,   0 } },  /* PokemonMansion1F grass slot 7: PONYTA / GRIMER */
    { 0x00D1B7, 3, { 143, 136,  33 } },  /* PokemonMansion1F grass slot 8: WEEZING / MUK / GROWLITHE */
    { 0x00D1B9, 3, { 136, 143,  33 } },  /* PokemonMansion1F grass slot 9: MUK / WEEZING / GROWLITHE */
    { 0x00D1BD, 3, {  33,  82, 165 } },  /* PokemonMansion2F grass slot 0: GROWLITHE / VULPIX / RATTATA */
    { 0x00D1BF, 3, {  55,  13, 166 } },  /* PokemonMansion2F grass slot 1: KOFFING / GRIMER / RATICATE */
    { 0x00D1C1, 2, {  55,  13,   0 } },  /* PokemonMansion2F grass slot 2: KOFFING / GRIMER */
    { 0x00D1C3, 2, { 163,  13,   0 } },  /* PokemonMansion2F grass slot 3: PONYTA / GRIMER */
    { 0x00D1C5, 3, {  55,  13, 165 } },  /* PokemonMansion2F grass slot 4: KOFFING / GRIMER / RATTATA */
    { 0x00D1C7, 2, { 163, 166,   0 } },  /* PokemonMansion2F grass slot 5: PONYTA / RATICATE */
    { 0x00D1C9, 2, {  13,  55,   0 } },  /* PokemonMansion2F grass slot 6: GRIMER / KOFFING */
    { 0x00D1CB, 2, { 163,  13,   0 } },  /* PokemonMansion2F grass slot 7: PONYTA / GRIMER */
    { 0x00D1CD, 2, { 143, 136,   0 } },  /* PokemonMansion2F grass slot 8: WEEZING / MUK */
    { 0x00D1CF, 2, { 136, 143,   0 } },  /* PokemonMansion2F grass slot 9: MUK / WEEZING */
    { 0x00D1D3, 3, {  55,  13, 165 } },  /* PokemonMansion3F grass slot 0: KOFFING / GRIMER / RATTATA */
    { 0x00D1D5, 3, {  33,  82, 166 } },  /* PokemonMansion3F grass slot 1: GROWLITHE / VULPIX / RATICATE */
    { 0x00D1D7, 2, {  55,  13,   0 } },  /* PokemonMansion3F grass slot 2: KOFFING / GRIMER */
    { 0x00D1D9, 2, { 163,  13,   0 } },  /* PokemonMansion3F grass slot 3: PONYTA / GRIMER */
    { 0x00D1DB, 3, { 163,  51, 165 } },  /* PokemonMansion3F grass slot 4: PONYTA / MAGMAR / RATTATA */
    { 0x00D1DD, 3, { 143, 136, 166 } },  /* PokemonMansion3F grass slot 5: WEEZING / MUK / RATICATE */
    { 0x00D1DF, 2, {  13,  55,   0 } },  /* PokemonMansion3F grass slot 6: GRIMER / KOFFING */
    { 0x00D1E1, 3, { 143, 136,  13 } },  /* PokemonMansion3F grass slot 7: WEEZING / MUK / GRIMER */
    { 0x00D1E3, 2, { 163, 136,   0 } },  /* PokemonMansion3F grass slot 8: PONYTA / MUK */
    { 0x00D1E5, 2, { 136, 143,   0 } },  /* PokemonMansion3F grass slot 9: MUK / WEEZING */
    { 0x00D1E9, 2, {  55,  13,   0 } },  /* PokemonMansionB1F grass slot 0: KOFFING / GRIMER */
    { 0x00D1EB, 2, {  55,  13,   0 } },  /* PokemonMansionB1F grass slot 1: KOFFING / GRIMER */
    { 0x00D1ED, 3, {  33,  82, 166 } },  /* PokemonMansionB1F grass slot 2: GROWLITHE / VULPIX / RATICATE */
    { 0x00D1EF, 2, { 163, 166,   0 } },  /* PokemonMansionB1F grass slot 3: PONYTA / RATICATE */
    { 0x00D1F1, 3, {  55,  13, 136 } },  /* PokemonMansionB1F grass slot 4: KOFFING / GRIMER / MUK */
    { 0x00D1F3, 3, { 143, 136, 166 } },  /* PokemonMansionB1F grass slot 5: WEEZING / MUK / RATICATE */
    { 0x00D1F5, 2, { 163,  76,   0 } },  /* PokemonMansionB1F grass slot 6: PONYTA / DITTO */
    { 0x00D1F7, 3, {  13,  55, 166 } },  /* PokemonMansionB1F grass slot 7: GRIMER / KOFFING / RATICATE */
    { 0x00D1F9, 3, { 143,  51,  76 } },  /* PokemonMansionB1F grass slot 8: WEEZING / MAGMAR / DITTO */
    { 0x00D1FB, 3, { 136, 143,  76 } },  /* PokemonMansionB1F grass slot 9: MUK / WEEZING / DITTO */
    { 0x00CF95, 2, {  17,  25,   0 } },  /* PokemonTower3F grass slot 7: CUBONE / GASTLY */
    { 0x00CF97, 2, {  17, 147,   0 } },  /* PokemonTower3F grass slot 8: CUBONE / HAUNTER */
    { 0x00CFA9, 2, { 147,  25,   0 } },  /* PokemonTower4F grass slot 6: HAUNTER / GASTLY */
    { 0x00CFAB, 2, {  17,  25,   0 } },  /* PokemonTower4F grass slot 7: CUBONE / GASTLY */
    { 0x00CFAD, 2, {  17, 147,   0 } },  /* PokemonTower4F grass slot 8: CUBONE / HAUNTER */
    { 0x00CFAF, 2, {  25, 147,   0 } },  /* PokemonTower4F grass slot 9: GASTLY / HAUNTER */
    { 0x00CFBF, 2, { 147,  17,   0 } },  /* PokemonTower5F grass slot 6: HAUNTER / CUBONE */
    { 0x00CFC1, 2, {  17,  25,   0 } },  /* PokemonTower5F grass slot 7: CUBONE / GASTLY */
    { 0x00CFC3, 2, {  17, 147,   0 } },  /* PokemonTower5F grass slot 8: CUBONE / HAUNTER */
    { 0x00CFC5, 2, {  25, 147,   0 } },  /* PokemonTower5F grass slot 9: GASTLY / HAUNTER */
    { 0x00CFD5, 2, { 147,  17,   0 } },  /* PokemonTower6F grass slot 6: HAUNTER / CUBONE */
    { 0x00CFD7, 2, {  17,  25,   0 } },  /* PokemonTower6F grass slot 7: CUBONE / GASTLY */
    { 0x00CFD9, 2, {  17, 147,   0 } },  /* PokemonTower6F grass slot 8: CUBONE / HAUNTER */
    { 0x00CFE9, 2, { 147,  25,   0 } },  /* PokemonTower7F grass slot 5: HAUNTER / GASTLY */
    { 0x00CFED, 2, {  17,  25,   0 } },  /* PokemonTower7F grass slot 7: CUBONE / GASTLY */
    { 0x00D26B, 2, {   6, 173,   0 } },  /* PowerPlant grass slot 0: VOLTORB / MAGNEMITE */
    { 0x00D26F, 2, {  84,  54,   0 } },  /* PowerPlant grass slot 2: PIKACHU / MAGNETON */
    { 0x00D271, 2, {  84,   6,   0 } },  /* PowerPlant grass slot 3: PIKACHU / VOLTORB */
    { 0x00D273, 2, { 173,   6,   0 } },  /* PowerPlant grass slot 4: MAGNEMITE / VOLTORB */
    { 0x00D275, 2, {   6,  13,   0 } },  /* PowerPlant grass slot 5: VOLTORB / GRIMER */
    { 0x00D277, 2, {  54,  13,   0 } },  /* PowerPlant grass slot 6: MAGNETON / GRIMER */
    { 0x00D27B, 3, {  53,  85, 136 } },  /* PowerPlant grass slot 8: ELECTABUZZ / RAICHU / MUK */
    { 0x00D27D, 3, {  53,  85, 136 } },  /* PowerPlant grass slot 9: ELECTABUZZ / RAICHU / MUK */
    { 0x00CEED, 2, { 107, 169,   0 } },  /* RockTunnel1F grass slot 1: ZUBAT / GEODUDE */
    { 0x00CEEF, 2, { 169, 107,   0 } },  /* RockTunnel1F grass slot 2: GEODUDE / ZUBAT */
    { 0x00CEF1, 2, { 106, 107,   0 } },  /* RockTunnel1F grass slot 3: MACHOP / ZUBAT */
    { 0x00CEF5, 2, { 107, 169,   0 } },  /* RockTunnel1F grass slot 5: ZUBAT / GEODUDE */
    { 0x00CEFB, 2, {  34, 106,   0 } },  /* RockTunnel1F grass slot 8: ONIX / MACHOP */
    { 0x00CEFD, 2, {  34, 106,   0 } },  /* RockTunnel1F grass slot 9: ONIX / MACHOP */
    { 0x00CF03, 2, { 107, 169,   0 } },  /* RockTunnelB1F grass slot 1: ZUBAT / GEODUDE */
    { 0x00CF05, 2, { 169, 106,   0 } },  /* RockTunnelB1F grass slot 2: GEODUDE / MACHOP */
    { 0x00CF07, 2, { 106, 107,   0 } },  /* RockTunnelB1F grass slot 3: MACHOP / ZUBAT */
    { 0x00CF09, 2, { 169, 107,   0 } },  /* RockTunnelB1F grass slot 4: GEODUDE / ZUBAT */
    { 0x00CF0B, 2, { 107, 169,   0 } },  /* RockTunnelB1F grass slot 5: ZUBAT / GEODUDE */
    { 0x00CF13, 2, { 169,  34,   0 } },  /* RockTunnelB1F grass slot 9: GEODUDE / ONIX */
    { 0x00CD8F, 2, { 165,  36,   0 } },  /* Route1 grass slot 1: RATTATA / PIDGEY */
    { 0x00CF17, 2, {   6, 173,   0 } },  /* Route10 grass slot 0: VOLTORB / MAGNEMITE */
    { 0x00CF19, 2, {   5, 165,   0 } },  /* Route10 grass slot 1: SPEAROW / RATTATA */
    { 0x00CF1B, 2, {   6, 173,   0 } },  /* Route10 grass slot 2: VOLTORB / MAGNEMITE */
    { 0x00CF1D, 3, { 108,  96, 173 } },  /* Route10 grass slot 3: EKANS / SANDSHREW / MAGNEMITE */
    { 0x00CF1F, 2, {   5,   3,   0 } },  /* Route10 grass slot 4: SPEAROW / NIDORAN_M */
    { 0x00CF21, 3, { 108,  96,  15 } },  /* Route10 grass slot 5: EKANS / SANDSHREW / NIDORAN_F */
    { 0x00CF23, 2, {   6, 173,   0 } },  /* Route10 grass slot 6: VOLTORB / MAGNEMITE */
    { 0x00CF25, 2, {   5, 166,   0 } },  /* Route10 grass slot 7: SPEAROW / RATICATE */
    { 0x00CF27, 3, { 108,  96, 106 } },  /* Route10 grass slot 8: EKANS / SANDSHREW / MACHOP */
    { 0x00CF29, 3, { 108,  96, 106 } },  /* Route10 grass slot 9: EKANS / SANDSHREW / MACHOP */
    { 0x00CED5, 3, { 108,  96,  36 } },  /* Route11 grass slot 0: EKANS / SANDSHREW / PIDGEY */
    { 0x00CED7, 2, {   5, 165,   0 } },  /* Route11 grass slot 1: SPEAROW / RATTATA */
    { 0x00CED9, 3, { 108,  96,  36 } },  /* Route11 grass slot 2: EKANS / SANDSHREW / PIDGEY */
    { 0x00CEDD, 2, {   5, 165,   0 } },  /* Route11 grass slot 4: SPEAROW / RATTATA */
    { 0x00CEE1, 3, { 108,  96, 150 } },  /* Route11 grass slot 6: EKANS / SANDSHREW / PIDGEOTTO */
    { 0x00CEE3, 2, {   5, 150,   0 } },  /* Route11 grass slot 7: SPEAROW / PIDGEOTTO */
    { 0x00CEE7, 2, {  48, 166,   0 } },  /* Route11 grass slot 9: DROWZEE / RATICATE */
    { 0x00CF2D, 2, { 185, 188,   0 } },  /* Route12 grass slot 0: ODDISH / BELLSPROUT */
    { 0x00CF2F, 2, {  36, 188,   0 } },  /* Route12 grass slot 1: PIDGEY / BELLSPROUT */
    { 0x00CF33, 2, {  65, 150,   0 } },  /* Route12 grass slot 3: VENONAT / PIDGEOTTO */
    { 0x00CF35, 2, { 185, 188,   0 } },  /* Route12 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00CF37, 2, {  65, 188,   0 } },  /* Route12 grass slot 5: VENONAT / BELLSPROUT */
    { 0x00CF39, 3, { 185, 188, 186 } },  /* Route12 grass slot 6: ODDISH / BELLSPROUT / GLOOM */
    { 0x00CF3B, 2, {  36, 189,   0 } },  /* Route12 grass slot 7: PIDGEY / WEEPINBELL */
    { 0x00CF3D, 3, { 186, 189,  64 } },  /* Route12 grass slot 8: GLOOM / WEEPINBELL / FARFETCHD */
    { 0x00CF3F, 3, { 186, 189,  64 } },  /* Route12 grass slot 9: GLOOM / WEEPINBELL / FARFETCHD */
    { 0x00CFF5, 2, { 185, 188,   0 } },  /* Route13 grass slot 0: ODDISH / BELLSPROUT */
    { 0x00CFF7, 2, {  36, 188,   0 } },  /* Route13 grass slot 1: PIDGEY / BELLSPROUT */
    { 0x00CFF9, 2, {  36, 150,   0 } },  /* Route13 grass slot 2: PIDGEY / PIDGEOTTO */
    { 0x00CFFB, 2, {  65,  36,   0 } },  /* Route13 grass slot 3: VENONAT / PIDGEY */
    { 0x00CFFD, 2, { 185, 188,   0 } },  /* Route13 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00CFFF, 2, {  65, 188,   0 } },  /* Route13 grass slot 5: VENONAT / BELLSPROUT */
    { 0x00D001, 3, { 185, 188, 186 } },  /* Route13 grass slot 6: ODDISH / BELLSPROUT / GLOOM */
    { 0x00D003, 2, {  76, 189,   0 } },  /* Route13 grass slot 7: DITTO / WEEPINBELL */
    { 0x00D005, 3, { 186, 189,  64 } },  /* Route13 grass slot 8: GLOOM / WEEPINBELL / FARFETCHD */
    { 0x00D007, 3, { 186, 189,  64 } },  /* Route13 grass slot 9: GLOOM / WEEPINBELL / FARFETCHD */
    { 0x00D01F, 2, { 185, 188,   0 } },  /* Route14 grass slot 0: ODDISH / BELLSPROUT */
    { 0x00D021, 2, {  36, 188,   0 } },  /* Route14 grass slot 1: PIDGEY / BELLSPROUT */
    { 0x00D023, 2, {  76,  65,   0 } },  /* Route14 grass slot 2: DITTO / VENONAT */
    { 0x00D025, 2, {  65, 150,   0 } },  /* Route14 grass slot 3: VENONAT / PIDGEOTTO */
    { 0x00D027, 2, { 185, 188,   0 } },  /* Route14 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00D029, 2, {  65, 188,   0 } },  /* Route14 grass slot 5: VENONAT / BELLSPROUT */
    { 0x00D02B, 3, { 185, 188, 186 } },  /* Route14 grass slot 6: ODDISH / BELLSPROUT / GLOOM */
    { 0x00D02D, 2, { 186, 189,   0 } },  /* Route14 grass slot 7: GLOOM / WEEPINBELL */
    { 0x00D02F, 2, { 150,  65,   0 } },  /* Route14 grass slot 8: PIDGEOTTO / VENONAT */
    { 0x00D031, 2, { 150, 119,   0 } },  /* Route14 grass slot 9: PIDGEOTTO / VENOMOTH */
    { 0x00D035, 2, { 185, 188,   0 } },  /* Route15 grass slot 0: ODDISH / BELLSPROUT */
    { 0x00D037, 2, {  76, 188,   0 } },  /* Route15 grass slot 1: DITTO / BELLSPROUT */
    { 0x00D039, 2, {  36,  65,   0 } },  /* Route15 grass slot 2: PIDGEY / VENONAT */
    { 0x00D03B, 2, {  65, 150,   0 } },  /* Route15 grass slot 3: VENONAT / PIDGEOTTO */
    { 0x00D03D, 2, { 185, 188,   0 } },  /* Route15 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00D03F, 2, {  65, 188,   0 } },  /* Route15 grass slot 5: VENONAT / BELLSPROUT */
    { 0x00D041, 3, { 185, 188, 186 } },  /* Route15 grass slot 6: ODDISH / BELLSPROUT / GLOOM */
    { 0x00D043, 2, { 186, 189,   0 } },  /* Route15 grass slot 7: GLOOM / WEEPINBELL */
    { 0x00D045, 2, { 150,  65,   0 } },  /* Route15 grass slot 8: PIDGEOTTO / VENONAT */
    { 0x00D047, 2, { 150, 119,   0 } },  /* Route15 grass slot 9: PIDGEOTTO / VENOMOTH */
    { 0x00D04D, 2, {   5,  70,   0 } },  /* Route16 grass slot 1: SPEAROW / DODUO */
    { 0x00D057, 2, {  70,   5,   0 } },  /* Route16 grass slot 6: DODUO / SPEAROW */
    { 0x00D059, 2, { 165,  35,   0 } },  /* Route16 grass slot 7: RATTATA / FEAROW */
    { 0x00D061, 2, {   5,  70,   0 } },  /* Route17 grass slot 0: SPEAROW / DODUO */
    { 0x00D063, 2, {   5,  35,   0 } },  /* Route17 grass slot 1: SPEAROW / FEAROW */
    { 0x00D065, 2, { 166,  70,   0 } },  /* Route17 grass slot 2: RATICATE / DODUO */
    { 0x00D069, 2, { 166, 163,   0 } },  /* Route17 grass slot 4: RATICATE / PONYTA */
    { 0x00D06B, 2, {  70, 163,   0 } },  /* Route17 grass slot 5: DODUO / PONYTA */
    { 0x00D06D, 2, {  70,  35,   0 } },  /* Route17 grass slot 6: DODUO / FEAROW */
    { 0x00D06F, 2, { 166,  70,   0 } },  /* Route17 grass slot 7: RATICATE / DODUO */
    { 0x00D071, 2, {  35, 163,   0 } },  /* Route17 grass slot 8: FEAROW / PONYTA */
    { 0x00D073, 2, {  35, 116,   0 } },  /* Route17 grass slot 9: FEAROW / DODRIO */
    { 0x00D079, 2, {   5,  70,   0 } },  /* Route18 grass slot 1: SPEAROW / DODUO */
    { 0x00D07B, 2, { 166, 165,   0 } },  /* Route18 grass slot 2: RATICATE / RATTATA */
    { 0x00D07F, 2, {  35, 165,   0 } },  /* Route18 grass slot 4: FEAROW / RATTATA */
    { 0x00D083, 2, {  70,   5,   0 } },  /* Route18 grass slot 6: DODUO / SPEAROW */
    { 0x00D085, 2, { 166,  35,   0 } },  /* Route18 grass slot 7: RATICATE / FEAROW */
    { 0x00D087, 2, {  35, 166,   0 } },  /* Route18 grass slot 8: FEAROW / RATICATE */
    { 0x00D089, 2, {  35, 166,   0 } },  /* Route18 grass slot 9: FEAROW / RATICATE */
    { 0x00CDA7, 2, {  36, 165,   0 } },  /* Route2 grass slot 2: PIDGEY / RATTATA */
    { 0x00CDA9, 2, { 165,   3,   0 } },  /* Route2 grass slot 3: RATTATA / NIDORAN_M */
    { 0x00CDAB, 2, {  36,  15,   0 } },  /* Route2 grass slot 4: PIDGEY / NIDORAN_F */
    { 0x00CDAD, 3, { 112, 123,  36 } },  /* Route2 grass slot 5: WEEDLE / CATERPIE / PIDGEY */
    { 0x00CDAF, 2, { 165,   3,   0 } },  /* Route2 grass slot 6: RATTATA / NIDORAN_M */
    { 0x00CDB1, 2, { 165,  15,   0 } },  /* Route2 grass slot 7: RATTATA / NIDORAN_F */
    { 0x00CDB3, 3, { 112, 123,  36 } },  /* Route2 grass slot 8: WEEDLE / CATERPIE / PIDGEY */
    { 0x00CDB5, 3, { 112, 123,  36 } },  /* Route2 grass slot 9: WEEDLE / CATERPIE / PIDGEY */
    { 0x00D1FF, 2, { 165,  36,   0 } },  /* Route21 grass slot 0: RATTATA / PIDGEY */
    { 0x00D201, 2, {  36, 165,   0 } },  /* Route21 grass slot 1: PIDGEY / RATTATA */
    { 0x00D203, 2, { 166,  36,   0 } },  /* Route21 grass slot 2: RATICATE / PIDGEY */
    { 0x00D205, 2, { 165,  36,   0 } },  /* Route21 grass slot 3: RATTATA / PIDGEY */
    { 0x00D209, 2, { 150, 165,   0 } },  /* Route21 grass slot 5: PIDGEOTTO / RATTATA */
    { 0x00D20B, 2, { 150, 166,   0 } },  /* Route21 grass slot 6: PIDGEOTTO / RATICATE */
    { 0x00D20D, 2, {  30, 150,   0 } },  /* Route21 grass slot 7: TANGELA / PIDGEOTTO */
    { 0x00D20F, 2, {  30, 150,   0 } },  /* Route21 grass slot 8: TANGELA / PIDGEOTTO */
    { 0x00D211, 2, {  30, 150,   0 } },  /* Route21 grass slot 9: TANGELA / PIDGEOTTO */
    { 0x00CDB9, 2, { 165,   3,   0 } },  /* Route22 grass slot 0: RATTATA / NIDORAN_M */
    { 0x00CDBB, 2, {   3,  15,   0 } },  /* Route22 grass slot 1: NIDORAN_M / NIDORAN_F */
    { 0x00CDBD, 2, { 165,  57,   0 } },  /* Route22 grass slot 2: RATTATA / MANKEY */
    { 0x00CDBF, 3, {   3,  15, 165 } },  /* Route22 grass slot 3: NIDORAN_M / NIDORAN_F / RATTATA */
    { 0x00CDC1, 2, { 165,   3,   0 } },  /* Route22 grass slot 4: RATTATA / NIDORAN_M */
    { 0x00CDC3, 2, {   3,  15,   0 } },  /* Route22 grass slot 5: NIDORAN_M / NIDORAN_F */
    { 0x00CDC5, 2, {   5,  57,   0 } },  /* Route22 grass slot 6: SPEAROW / MANKEY */
    { 0x00CDC9, 3, {  15,   3,   5 } },  /* Route22 grass slot 8: NIDORAN_F / NIDORAN_M / SPEAROW */
    { 0x00CDCB, 3, {  15,   3,   5 } },  /* Route22 grass slot 9: NIDORAN_F / NIDORAN_M / SPEAROW */
    { 0x00D281, 3, { 108,  96, 167 } },  /* Route23 grass slot 0: EKANS / SANDSHREW / NIDORINO */
    { 0x00D283, 2, {  76, 168,   0 } },  /* Route23 grass slot 1: DITTO / NIDORINA */
    { 0x00D285, 2, {   5,  57,   0 } },  /* Route23 grass slot 2: SPEAROW / MANKEY */
    { 0x00D287, 2, {  35, 167,   0 } },  /* Route23 grass slot 3: FEAROW / NIDORINO */
    { 0x00D289, 2, {  76, 168,   0 } },  /* Route23 grass slot 4: DITTO / NIDORINA */
    { 0x00D28D, 3, {  45,  97,  57 } },  /* Route23 grass slot 6: ARBOK / SANDSLASH / MANKEY */
    { 0x00D28F, 2, {  76,  35,   0 } },  /* Route23 grass slot 7: DITTO / FEAROW */
    { 0x00D291, 2, {  35, 117,   0 } },  /* Route23 grass slot 8: FEAROW / PRIMEAPE */
    { 0x00D293, 2, {  35, 117,   0 } },  /* Route23 grass slot 9: FEAROW / PRIMEAPE */
    { 0x00CE53, 3, { 112, 123, 185 } },  /* Route24 grass slot 0: WEEDLE / CATERPIE / ODDISH */
    { 0x00CE55, 3, { 113, 124, 188 } },  /* Route24 grass slot 1: KAKUNA / METAPOD / BELLSPROUT */
    { 0x00CE59, 2, { 185, 188,   0 } },  /* Route24 grass slot 3: ODDISH / BELLSPROUT */
    { 0x00CE5B, 2, { 185, 188,   0 } },  /* Route24 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00CE5D, 2, { 148,  36,   0 } },  /* Route24 grass slot 5: ABRA / PIDGEY */
    { 0x00CE5F, 3, { 185, 188,  65 } },  /* Route24 grass slot 6: ODDISH / BELLSPROUT / VENONAT */
    { 0x00CE61, 2, {  36,  65,   0 } },  /* Route24 grass slot 7: PIDGEY / VENONAT */
    { 0x00CE63, 2, { 148,  36,   0 } },  /* Route24 grass slot 8: ABRA / PIDGEY */
    { 0x00CE65, 2, { 148, 150,   0 } },  /* Route24 grass slot 9: ABRA / PIDGEOTTO */
    { 0x00CE69, 3, { 112, 123, 185 } },  /* Route25 grass slot 0: WEEDLE / CATERPIE / ODDISH */
    { 0x00CE6B, 3, { 113, 124, 188 } },  /* Route25 grass slot 1: KAKUNA / METAPOD / BELLSPROUT */
    { 0x00CE6F, 2, { 185, 188,   0 } },  /* Route25 grass slot 3: ODDISH / BELLSPROUT */
    { 0x00CE71, 2, { 185, 188,   0 } },  /* Route25 grass slot 4: ODDISH / BELLSPROUT */
    { 0x00CE73, 2, { 148,  36,   0 } },  /* Route25 grass slot 5: ABRA / PIDGEY */
    { 0x00CE75, 3, { 185, 188,  65 } },  /* Route25 grass slot 6: ODDISH / BELLSPROUT / VENONAT */
    { 0x00CE77, 2, { 148,  65,   0 } },  /* Route25 grass slot 7: ABRA / VENONAT */
    { 0x00CE79, 3, { 124, 113,  36 } },  /* Route25 grass slot 8: METAPOD / KAKUNA / PIDGEY */
    { 0x00CE7B, 3, { 123, 112, 150 } },  /* Route25 grass slot 9: CATERPIE / WEEDLE / PIDGEOTTO */
    { 0x00CDE5, 2, {  36,   5,   0 } },  /* Route3 grass slot 0: PIDGEY / SPEAROW */
    { 0x00CDE9, 2, {  36,  57,   0 } },  /* Route3 grass slot 2: PIDGEY / MANKEY */
    { 0x00CDED, 2, {   5,  96,   0 } },  /* Route3 grass slot 4: SPEAROW / SANDSHREW */
    { 0x00CDEF, 2, {  36, 165,   0 } },  /* Route3 grass slot 5: PIDGEY / RATTATA */
    { 0x00CDF1, 2, {   5,  96,   0 } },  /* Route3 grass slot 6: SPEAROW / SANDSHREW */
    { 0x00CDF3, 2, { 100, 165,   0 } },  /* Route3 grass slot 7: JIGGLYPUFF / RATTATA */
    { 0x00CDF5, 2, { 100,   5,   0 } },  /* Route3 grass slot 8: JIGGLYPUFF / SPEAROW */
    { 0x00CDF7, 2, { 100,   5,   0 } },  /* Route3 grass slot 9: JIGGLYPUFF / SPEAROW */
    { 0x00CE3D, 2, { 165,   5,   0 } },  /* Route4 grass slot 0: RATTATA / SPEAROW */
    { 0x00CE41, 2, { 165,  57,   0 } },  /* Route4 grass slot 2: RATTATA / MANKEY */
    { 0x00CE43, 3, { 108,  96,   5 } },  /* Route4 grass slot 3: EKANS / SANDSHREW / SPEAROW */
    { 0x00CE45, 2, {   5,  96,   0 } },  /* Route4 grass slot 4: SPEAROW / SANDSHREW */
    { 0x00CE47, 3, { 108,  96, 165 } },  /* Route4 grass slot 5: EKANS / SANDSHREW / RATTATA */
    { 0x00CE49, 2, { 165,  96,   0 } },  /* Route4 grass slot 6: RATTATA / SANDSHREW */
    { 0x00CE4B, 2, {   5, 165,   0 } },  /* Route4 grass slot 7: SPEAROW / RATTATA */
    { 0x00CE4D, 3, { 108,  96,   5 } },  /* Route4 grass slot 8: EKANS / SANDSHREW / SPEAROW */
    { 0x00CE4F, 3, { 108,  96,   5 } },  /* Route4 grass slot 9: EKANS / SANDSHREW / SPEAROW */
    { 0x00CE95, 3, { 185, 188,  36 } },  /* Route5 grass slot 0: ODDISH / BELLSPROUT / PIDGEY */
    { 0x00CE97, 2, {  36, 165,   0 } },  /* Route5 grass slot 1: PIDGEY / RATTATA */
    { 0x00CE99, 2, {  36, 148,   0 } },  /* Route5 grass slot 2: PIDGEY / ABRA */
    { 0x00CE9B, 3, {  57,  77,  36 } },  /* Route5 grass slot 3: MANKEY / MEOWTH / PIDGEY */
    { 0x00CE9D, 3, {  57,  77, 165 } },  /* Route5 grass slot 4: MANKEY / MEOWTH / RATTATA */
    { 0x00CE9F, 3, { 185, 188,  36 } },  /* Route5 grass slot 5: ODDISH / BELLSPROUT / PIDGEY */
    { 0x00CEA1, 3, { 185, 188, 150 } },  /* Route5 grass slot 6: ODDISH / BELLSPROUT / PIDGEOTTO */
    { 0x00CEA3, 2, {  36, 100,   0 } },  /* Route5 grass slot 7: PIDGEY / JIGGLYPUFF */
    { 0x00CEA5, 3, {  57,  77, 100 } },  /* Route5 grass slot 8: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00CEA7, 3, {  57,  77, 100 } },  /* Route5 grass slot 9: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00CEAB, 3, { 185, 188,  36 } },  /* Route6 grass slot 0: ODDISH / BELLSPROUT / PIDGEY */
    { 0x00CEAD, 2, {  36, 165,   0 } },  /* Route6 grass slot 1: PIDGEY / RATTATA */
    { 0x00CEAF, 2, {  36, 148,   0 } },  /* Route6 grass slot 2: PIDGEY / ABRA */
    { 0x00CEB1, 3, {  57,  77,  36 } },  /* Route6 grass slot 3: MANKEY / MEOWTH / PIDGEY */
    { 0x00CEB3, 3, {  57,  77, 165 } },  /* Route6 grass slot 4: MANKEY / MEOWTH / RATTATA */
    { 0x00CEB5, 3, { 185, 188,  36 } },  /* Route6 grass slot 5: ODDISH / BELLSPROUT / PIDGEY */
    { 0x00CEB7, 3, { 185, 188, 150 } },  /* Route6 grass slot 6: ODDISH / BELLSPROUT / PIDGEOTTO */
    { 0x00CEB9, 2, {  36, 100,   0 } },  /* Route6 grass slot 7: PIDGEY / JIGGLYPUFF */
    { 0x00CEBB, 3, {  57,  77, 100 } },  /* Route6 grass slot 8: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00CEBD, 3, {  57,  77, 100 } },  /* Route6 grass slot 9: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00CF6F, 3, { 185, 188,  36 } },  /* Route7 grass slot 1: ODDISH / BELLSPROUT / PIDGEY */
    { 0x00CF71, 3, {  57,  77, 165 } },  /* Route7 grass slot 2: MANKEY / MEOWTH / RATTATA */
    { 0x00CF73, 3, { 185, 188, 148 } },  /* Route7 grass slot 3: ODDISH / BELLSPROUT / ABRA */
    { 0x00CF75, 2, {  36, 148,   0 } },  /* Route7 grass slot 4: PIDGEY / ABRA */
    { 0x00CF77, 3, {  57,  77, 150 } },  /* Route7 grass slot 5: MANKEY / MEOWTH / PIDGEOTTO */
    { 0x00CF79, 3, {  33,  82, 148 } },  /* Route7 grass slot 6: GROWLITHE / VULPIX / ABRA */
    { 0x00CF7B, 3, {  33,  82, 100 } },  /* Route7 grass slot 7: GROWLITHE / VULPIX / JIGGLYPUFF */
    { 0x00CF7D, 3, {  57,  77, 100 } },  /* Route7 grass slot 8: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00CF7F, 3, {  57,  77, 100 } },  /* Route7 grass slot 9: MANKEY / MEOWTH / JIGGLYPUFF */
    { 0x00CF59, 3, {  57,  77,  36 } },  /* Route8 grass slot 1: MANKEY / MEOWTH / PIDGEY */
    { 0x00CF5B, 3, { 108,  96, 165 } },  /* Route8 grass slot 2: EKANS / SANDSHREW / RATTATA */
    { 0x00CF5D, 3, {  33,  82, 148 } },  /* Route8 grass slot 3: GROWLITHE / VULPIX / ABRA */
    { 0x00CF5F, 2, {  36, 148,   0 } },  /* Route8 grass slot 4: PIDGEY / ABRA */
    { 0x00CF61, 3, {  57,  77, 150 } },  /* Route8 grass slot 5: MANKEY / MEOWTH / PIDGEOTTO */
    { 0x00CF63, 3, { 108,  96, 100 } },  /* Route8 grass slot 6: EKANS / SANDSHREW / JIGGLYPUFF */
    { 0x00CF65, 3, {  33,  82, 100 } },  /* Route8 grass slot 7: GROWLITHE / VULPIX / JIGGLYPUFF */
    { 0x00CF67, 3, {  33,  82,  38 } },  /* Route8 grass slot 8: GROWLITHE / VULPIX / KADABRA */
    { 0x00CF69, 3, {  33,  82,  38 } },  /* Route8 grass slot 9: GROWLITHE / VULPIX / KADABRA */
    { 0x00CE7F, 2, { 165,   3,   0 } },  /* Route9 grass slot 0: RATTATA / NIDORAN_M */
    { 0x00CE81, 2, {   5,  15,   0 } },  /* Route9 grass slot 1: SPEAROW / NIDORAN_F */
    { 0x00CE85, 3, { 108,  96,   3 } },  /* Route9 grass slot 3: EKANS / SANDSHREW / NIDORAN_M */
    { 0x00CE87, 2, {   5,  15,   0 } },  /* Route9 grass slot 4: SPEAROW / NIDORAN_F */
    { 0x00CE89, 3, { 108,  96,   5 } },  /* Route9 grass slot 5: EKANS / SANDSHREW / SPEAROW */
    { 0x00CE8B, 2, { 165, 167,   0 } },  /* Route9 grass slot 6: RATTATA / NIDORINO */
    { 0x00CE8D, 2, {   5, 168,   0 } },  /* Route9 grass slot 7: SPEAROW / NIDORINA */
    { 0x00CE8F, 3, { 108,  96, 166 } },  /* Route9 grass slot 8: EKANS / SANDSHREW / RATICATE */
    { 0x00CE91, 3, { 108,  96,  35 } },  /* Route9 grass slot 9: EKANS / SANDSHREW / FEAROW */
    { 0x00D08D, 2, {   3,  15,   0 } },  /* SafariZoneCenter grass slot 0: NIDORAN_M / NIDORAN_F */
    { 0x00D08F, 2, {  18,  15,   0 } },  /* SafariZoneCenter grass slot 1: RHYHORN / NIDORAN_F */
    { 0x00D091, 2, {  65,  12,   0 } },  /* SafariZoneCenter grass slot 2: VENONAT / EXEGGCUTE */
    { 0x00D093, 2, {  12,  18,   0 } },  /* SafariZoneCenter grass slot 3: EXEGGCUTE / RHYHORN */
    { 0x00D095, 2, { 167, 168,   0 } },  /* SafariZoneCenter grass slot 4: NIDORINO / NIDORINA */
    { 0x00D097, 2, {  12,  46,   0 } },  /* SafariZoneCenter grass slot 5: EXEGGCUTE / PARASECT */
    { 0x00D099, 3, { 168, 167, 109 } },  /* SafariZoneCenter grass slot 6: NIDORINA / NIDORINO / PARAS */
    { 0x00D09D, 3, {  26,  29,  30 } },  /* SafariZoneCenter grass slot 8: SCYTHER / PINSIR / TANGELA */
    { 0x00D0A3, 2, {   3,  15,   0 } },  /* SafariZoneEast grass slot 0: NIDORAN_M / NIDORAN_F */
    { 0x00D0A5, 2, {  70,  15,   0 } },  /* SafariZoneEast grass slot 1: DODUO / NIDORAN_F */
    { 0x00D0A7, 2, { 109,  12,   0 } },  /* SafariZoneEast grass slot 2: PARAS / EXEGGCUTE */
    { 0x00D0A9, 2, {  12,  60,   0 } },  /* SafariZoneEast grass slot 3: EXEGGCUTE / TAUROS */
    { 0x00D0AB, 2, { 167, 168,   0 } },  /* SafariZoneEast grass slot 4: NIDORINO / NIDORINA */
    { 0x00D0AD, 2, {  12,  17,   0 } },  /* SafariZoneEast grass slot 5: EXEGGCUTE / CUBONE */
    { 0x00D0AF, 3, {  15,   3,  12 } },  /* SafariZoneEast grass slot 6: NIDORAN_F / NIDORAN_M / EXEGGCUTE */
    { 0x00D0B1, 2, {  46, 145,   0 } },  /* SafariZoneEast grass slot 7: PARASECT / MAROWAK */
    { 0x00D0B3, 2, {   2,  40,   0 } },  /* SafariZoneEast grass slot 8: KANGASKHAN / CHANSEY */
    { 0x00D0B5, 2, {  26,  29,   0 } },  /* SafariZoneEast grass slot 9: SCYTHER / PINSIR */
    { 0x00D0B9, 2, {   3,  15,   0 } },  /* SafariZoneNorth grass slot 0: NIDORAN_M / NIDORAN_F */
    { 0x00D0BB, 2, {  18,  15,   0 } },  /* SafariZoneNorth grass slot 1: RHYHORN / NIDORAN_F */
    { 0x00D0BD, 2, { 109,  12,   0 } },  /* SafariZoneNorth grass slot 2: PARAS / EXEGGCUTE */
    { 0x00D0BF, 2, {  12,  18,   0 } },  /* SafariZoneNorth grass slot 3: EXEGGCUTE / RHYHORN */
    { 0x00D0C1, 2, { 167, 168,   0 } },  /* SafariZoneNorth grass slot 4: NIDORINO / NIDORINA */
    { 0x00D0C3, 2, {  12,   2,   0 } },  /* SafariZoneNorth grass slot 5: EXEGGCUTE / KANGASKHAN */
    { 0x00D0C5, 3, { 168, 167,  17 } },  /* SafariZoneNorth grass slot 6: NIDORINA / NIDORINO / CUBONE */
    { 0x00D0C7, 2, { 119,   2,   0 } },  /* SafariZoneNorth grass slot 7: VENOMOTH / KANGASKHAN */
    { 0x00D0C9, 2, {  40,  26,   0 } },  /* SafariZoneNorth grass slot 8: CHANSEY / SCYTHER */
    { 0x00D0CB, 2, {  60,  29,   0 } },  /* SafariZoneNorth grass slot 9: TAUROS / PINSIR */
    { 0x00D0CF, 2, {   3,  15,   0 } },  /* SafariZoneWest grass slot 0: NIDORAN_M / NIDORAN_F */
    { 0x00D0D1, 2, {  70,  15,   0 } },  /* SafariZoneWest grass slot 1: DODUO / NIDORAN_F */
    { 0x00D0D3, 2, {  65,  12,   0 } },  /* SafariZoneWest grass slot 2: VENONAT / EXEGGCUTE */
    { 0x00D0D5, 2, {  12,  60,   0 } },  /* SafariZoneWest grass slot 3: EXEGGCUTE / TAUROS */
    { 0x00D0D7, 2, { 167, 168,   0 } },  /* SafariZoneWest grass slot 4: NIDORINO / NIDORINA */
    { 0x00D0D9, 2, {  12,  17,   0 } },  /* SafariZoneWest grass slot 5: EXEGGCUTE / CUBONE */
    { 0x00D0DB, 3, {  15,   3,  12 } },  /* SafariZoneWest grass slot 6: NIDORAN_F / NIDORAN_M / EXEGGCUTE */
    { 0x00D0DD, 2, { 119, 145,   0 } },  /* SafariZoneWest grass slot 7: VENOMOTH / MAROWAK */
    { 0x00D0DF, 2, {  60,  29,   0 } },  /* SafariZoneWest grass slot 8: TAUROS / PINSIR */
    { 0x00D0E1, 2, {   2,  30,   0 } },  /* SafariZoneWest grass slot 9: KANGASKHAN / TANGELA */
    { 0x00D111, 2, {  58, 107,   0 } },  /* SeafoamIslands1F grass slot 0: SEEL / ZUBAT */
    { 0x00D113, 3, {  37,  47,  78 } },  /* SeafoamIslands1F grass slot 1: SLOWPOKE / PSYDUCK / KRABBY */
    { 0x00D115, 3, {  23,  27,  78 } },  /* SeafoamIslands1F grass slot 2: SHELLDER / STARYU / KRABBY */
    { 0x00D117, 3, {  92,  78, 107 } },  /* SeafoamIslands1F grass slot 3: HORSEA / KRABBY / ZUBAT */
    { 0x00D119, 3, {  92,  78, 107 } },  /* SeafoamIslands1F grass slot 4: HORSEA / KRABBY / ZUBAT */
    { 0x00D11B, 2, { 107,  37,   0 } },  /* SeafoamIslands1F grass slot 5: ZUBAT / SLOWPOKE */
    { 0x00D11D, 2, { 130,  37,   0 } },  /* SeafoamIslands1F grass slot 6: GOLBAT / SLOWPOKE */
    { 0x00D11F, 3, {  47,  37, 107 } },  /* SeafoamIslands1F grass slot 7: PSYDUCK / SLOWPOKE / ZUBAT */
    { 0x00D121, 3, {  23,  27, 130 } },  /* SeafoamIslands1F grass slot 8: SHELLDER / STARYU / GOLBAT */
    { 0x00D123, 3, { 128,   8, 130 } },  /* SeafoamIslands1F grass slot 9: GOLDUCK / SLOWBRO / GOLBAT */
    { 0x00D127, 3, {  27,  23, 107 } },  /* SeafoamIslandsB1F grass slot 0: STARYU / SHELLDER / ZUBAT */
    { 0x00D129, 2, {  92,  78,   0 } },  /* SeafoamIslandsB1F grass slot 1: HORSEA / KRABBY */
    { 0x00D12B, 3, {  23,  27, 107 } },  /* SeafoamIslandsB1F grass slot 2: SHELLDER / STARYU / ZUBAT */
    { 0x00D12D, 2, {  92,  78,   0 } },  /* SeafoamIslandsB1F grass slot 3: HORSEA / KRABBY */
    { 0x00D12F, 3, {  37,  47, 130 } },  /* SeafoamIslandsB1F grass slot 4: SLOWPOKE / PSYDUCK / GOLBAT */
    { 0x00D131, 2, {  58,  37,   0 } },  /* SeafoamIslandsB1F grass slot 5: SEEL / SLOWPOKE */
    { 0x00D133, 3, {  37,  47, 107 } },  /* SeafoamIslandsB1F grass slot 6: SLOWPOKE / PSYDUCK / ZUBAT */
    { 0x00D135, 2, {  58, 138,   0 } },  /* SeafoamIslandsB1F grass slot 7: SEEL / KINGLER */
    { 0x00D137, 2, { 120,  58,   0 } },  /* SeafoamIslandsB1F grass slot 8: DEWGONG / SEEL */
    { 0x00D139, 3, {  93, 138,  58 } },  /* SeafoamIslandsB1F grass slot 9: SEADRA / KINGLER / SEEL */
    { 0x00D13D, 2, {  58, 107,   0 } },  /* SeafoamIslandsB2F grass slot 0: SEEL / ZUBAT */
    { 0x00D13F, 3, {  37,  47,  78 } },  /* SeafoamIslandsB2F grass slot 1: SLOWPOKE / PSYDUCK / KRABBY */
    { 0x00D141, 2, {  58, 107,   0 } },  /* SeafoamIslandsB2F grass slot 2: SEEL / ZUBAT */
    { 0x00D143, 3, {  37,  47, 130 } },  /* SeafoamIslandsB2F grass slot 3: SLOWPOKE / PSYDUCK / GOLBAT */
    { 0x00D145, 3, {  92,  78, 138 } },  /* SeafoamIslandsB2F grass slot 4: HORSEA / KRABBY / KINGLER */
    { 0x00D147, 3, {  27,  23,  58 } },  /* SeafoamIslandsB2F grass slot 5: STARYU / SHELLDER / SEEL */
    { 0x00D149, 2, {  92,  78,   0 } },  /* SeafoamIslandsB2F grass slot 6: HORSEA / KRABBY */
    { 0x00D14B, 3, {  23,  27, 130 } },  /* SeafoamIslandsB2F grass slot 7: SHELLDER / STARYU / GOLBAT */
    { 0x00D14D, 2, { 130,  37,   0 } },  /* SeafoamIslandsB2F grass slot 8: GOLBAT / SLOWPOKE */
    { 0x00D14F, 2, {   8, 128,   0 } },  /* SeafoamIslandsB2F grass slot 9: SLOWBRO / GOLDUCK */
    { 0x00D153, 3, {  37,  47, 130 } },  /* SeafoamIslandsB3F grass slot 0: SLOWPOKE / PSYDUCK / GOLBAT */
    { 0x00D155, 2, {  58, 107,   0 } },  /* SeafoamIslandsB3F grass slot 1: SEEL / ZUBAT */
    { 0x00D157, 3, {  37,  47,  78 } },  /* SeafoamIslandsB3F grass slot 2: SLOWPOKE / PSYDUCK / KRABBY */
    { 0x00D159, 2, {  58, 107,   0 } },  /* SeafoamIslandsB3F grass slot 3: SEEL / ZUBAT */
    { 0x00D15B, 3, {  92,  78, 138 } },  /* SeafoamIslandsB3F grass slot 4: HORSEA / KRABBY / KINGLER */
    { 0x00D15D, 3, {  23,  27,  58 } },  /* SeafoamIslandsB3F grass slot 5: SHELLDER / STARYU / SEEL */
    { 0x00D15F, 2, {  92,  78,   0 } },  /* SeafoamIslandsB3F grass slot 6: HORSEA / KRABBY */
    { 0x00D161, 3, {  23,  27,  58 } },  /* SeafoamIslandsB3F grass slot 7: SHELLDER / STARYU / SEEL */
    { 0x00D163, 3, {  93, 138, 120 } },  /* SeafoamIslandsB3F grass slot 8: SEADRA / KINGLER / DEWGONG */
    { 0x00D17D, 3, {  92,  78, 130 } },  /* SeafoamIslandsB4F grass slot 0: HORSEA / KRABBY / GOLBAT */
    { 0x00D17F, 3, {  23,  27, 107 } },  /* SeafoamIslandsB4F grass slot 1: SHELLDER / STARYU / ZUBAT */
    { 0x00D181, 2, {  92,  78,   0 } },  /* SeafoamIslandsB4F grass slot 2: HORSEA / KRABBY */
    { 0x00D183, 3, {  23,  27, 138 } },  /* SeafoamIslandsB4F grass slot 3: SHELLDER / STARYU / KINGLER */
    { 0x00D185, 3, {  37,  47,  58 } },  /* SeafoamIslandsB4F grass slot 4: SLOWPOKE / PSYDUCK / SEEL */
    { 0x00D189, 3, {  37,  47, 130 } },  /* SeafoamIslandsB4F grass slot 6: SLOWPOKE / PSYDUCK / GOLBAT */
    { 0x00D18B, 2, {  58, 107,   0 } },  /* SeafoamIslandsB4F grass slot 7: SEEL / ZUBAT */
    { 0x00D18D, 3, {   8, 128, 120 } },  /* SeafoamIslandsB4F grass slot 8: SLOWBRO / GOLDUCK / DEWGONG */
    { 0x00D18F, 2, { 130, 120,   0 } },  /* SeafoamIslandsB4F grass slot 9: GOLBAT / DEWGONG */
    { 0x00D2C3, 2, { 106, 169,   0 } },  /* VictoryRoad1F grass slot 0: MACHOP / GEODUDE */
    { 0x00D2C7, 2, { 107, 169,   0 } },  /* VictoryRoad1F grass slot 2: ZUBAT / GEODUDE */
    { 0x00D2C9, 2, {  34, 107,   0 } },  /* VictoryRoad1F grass slot 3: ONIX / ZUBAT */
    { 0x00D2CB, 2, {  34, 107,   0 } },  /* VictoryRoad1F grass slot 4: ONIX / ZUBAT */
    { 0x00D2CD, 2, {  34, 169,   0 } },  /* VictoryRoad1F grass slot 5: ONIX / GEODUDE */
    { 0x00D2CF, 2, {  39,  34,   0 } },  /* VictoryRoad1F grass slot 6: GRAVELER / ONIX */
    { 0x00D2D1, 2, { 130,  34,   0 } },  /* VictoryRoad1F grass slot 7: GOLBAT / ONIX */
    { 0x00D2D3, 2, {  41,  39,   0 } },  /* VictoryRoad1F grass slot 8: MACHOKE / GRAVELER */
    { 0x00D2D5, 2, { 145,  39,   0 } },  /* VictoryRoad1F grass slot 9: MAROWAK / GRAVELER */
    { 0x00D297, 2, { 106, 169,   0 } },  /* VictoryRoad2F grass slot 0: MACHOP / GEODUDE */
    { 0x00D29B, 2, { 107, 169,   0 } },  /* VictoryRoad2F grass slot 2: ZUBAT / GEODUDE */
    { 0x00D29D, 2, {  34, 107,   0 } },  /* VictoryRoad2F grass slot 3: ONIX / ZUBAT */
    { 0x00D29F, 2, {  34, 130,   0 } },  /* VictoryRoad2F grass slot 4: ONIX / GOLBAT */
    { 0x00D2A1, 2, {  34,  39,   0 } },  /* VictoryRoad2F grass slot 5: ONIX / GRAVELER */
    { 0x00D2A3, 2, {  41,  34,   0 } },  /* VictoryRoad2F grass slot 6: MACHOKE / ONIX */
    { 0x00D2A5, 2, { 130,  34,   0 } },  /* VictoryRoad2F grass slot 7: GOLBAT / ONIX */
    { 0x00D2A7, 2, { 145,  41,   0 } },  /* VictoryRoad2F grass slot 8: MAROWAK / MACHOKE */
    { 0x00D2A9, 2, {  39,  41,   0 } },  /* VictoryRoad2F grass slot 9: GRAVELER / MACHOKE */
    { 0x00D2AD, 2, { 106, 169,   0 } },  /* VictoryRoad3F grass slot 0: MACHOP / GEODUDE */
    { 0x00D2AF, 2, { 169, 130,   0 } },  /* VictoryRoad3F grass slot 1: GEODUDE / GOLBAT */
    { 0x00D2B1, 2, { 107, 169,   0 } },  /* VictoryRoad3F grass slot 2: ZUBAT / GEODUDE */
    { 0x00D2B5, 2, { 119, 169,   0 } },  /* VictoryRoad3F grass slot 4: VENOMOTH / GEODUDE */
    { 0x00D2B7, 2, {  34,  39,   0 } },  /* VictoryRoad3F grass slot 5: ONIX / GRAVELER */
    { 0x00D2B9, 2, {  39,  41,   0 } },  /* VictoryRoad3F grass slot 6: GRAVELER / MACHOKE */
    { 0x00D2BB, 2, { 130,  41,   0 } },  /* VictoryRoad3F grass slot 7: GOLBAT / MACHOKE */
    { 0x00D2BD, 2, {  41,  39,   0 } },  /* VictoryRoad3F grass slot 8: MACHOKE / GRAVELER */
    { 0x00D2BF, 2, {  41,  39,   0 } },  /* VictoryRoad3F grass slot 9: MACHOKE / GRAVELER */
    { 0x00CDCF, 2, { 112, 123,   0 } },  /* ViridianForest grass slot 0: WEEDLE / CATERPIE */
    { 0x00CDD1, 2, { 113, 124,   0 } },  /* ViridianForest grass slot 1: KAKUNA / METAPOD */
    { 0x00CDD3, 2, { 112, 123,   0 } },  /* ViridianForest grass slot 2: WEEDLE / CATERPIE */
    { 0x00CDD5, 2, { 112, 123,   0 } },  /* ViridianForest grass slot 3: WEEDLE / CATERPIE */
    { 0x00CDD7, 3, { 113, 124,  36 } },  /* ViridianForest grass slot 4: KAKUNA / METAPOD / PIDGEY */
    { 0x00CDD9, 3, { 113, 124,  36 } },  /* ViridianForest grass slot 5: KAKUNA / METAPOD / PIDGEY */
    { 0x00CDDB, 3, { 124, 113, 123 } },  /* ViridianForest grass slot 6: METAPOD / KAKUNA / CATERPIE */
    { 0x00CDDD, 3, { 123, 112, 124 } },  /* ViridianForest grass slot 7: CATERPIE / WEEDLE / METAPOD */
    { 0x00CDDF, 2, {  84,  36,   0 } },  /* ViridianForest grass slot 8: PIKACHU / PIDGEY */
    { 0x00CDE1, 2, {  84, 150,   0 } },  /* ViridianForest grass slot 9: PIKACHU / PIDGEOTTO */
};

#endif /* GEN1_WILD_DIFFS_YELLOW_GEN_H */
