/* AUTO-GENERATED by runtime/tools/generate_wild_diffs_gen2.py.
 * Source: pret/pokegold-decomp (Gold + Silver share offsets).
 * Do not edit by hand. Re-run the script if pret
 * sources change. */

#ifndef GEN2_WILD_DIFFS_GS_GEN_H
#define GEN2_WILD_DIFFS_GS_GEN_H

#include <stdint.h>

#ifndef GBGEN2_WILDDIFF_STRUCT_DEFINED
#define GBGEN2_WILDDIFF_STRUCT_DEFINED
typedef struct {
    uint32_t rom_offset;
    uint8_t  count;
    uint8_t  species[3];
} GBGen2WildDiff;
#endif

#define GEN2_WILD_DIFFS_GS_COUNT  859

static const GBGen2WildDiff GEN2_WILD_DIFFS_GS[GEN2_WILD_DIFFS_GS_COUNT] = {
    { 0x02AD19, 2, { 109,  19,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_1F slot 4: KOFFING / RATTATA */
    { 0x02AD27, 2, { 109,  19,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_1F slot 11: KOFFING / RATTATA */
    { 0x02AD35, 2, { 109,  19,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_1F slot 18: KOFFING / RATTATA */
    { 0x02AD46, 2, {  19,  41,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 3: RATTATA / ZUBAT */
    { 0x02AD48, 2, {  41, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 4: ZUBAT / KOFFING */
    { 0x02AD4A, 2, { 126, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 5: MAGMAR / KOFFING */
    { 0x02AD4C, 2, { 126, 110,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 6: MAGMAR / WEEZING */
    { 0x02AD54, 2, { 126,  41,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 10: MAGMAR / ZUBAT */
    { 0x02AD56, 2, {  41, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 11: ZUBAT / KOFFING */
    { 0x02AD58, 2, {  19, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 12: RATTATA / KOFFING */
    { 0x02AD5A, 2, {  19, 110,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 13: RATTATA / WEEZING */
    { 0x02AD62, 2, {  19,  41,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 17: RATTATA / ZUBAT */
    { 0x02AD64, 2, {  41, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 18: ZUBAT / KOFFING */
    { 0x02AD66, 2, { 126, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 19: MAGMAR / KOFFING */
    { 0x02AD68, 2, { 126, 110,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 20: MAGMAR / WEEZING */
    { 0x02B326, 2, { 202, 217,   0 } },  /* JohtoGrassWildMons DARK_CAVE_BLACKTHORN_ENTRANCE slot 3: WOBBUFFET / URSARING */
    { 0x02B328, 2, { 202, 216,   0 } },  /* JohtoGrassWildMons DARK_CAVE_BLACKTHORN_ENTRANCE slot 4: WOBBUFFET / TEDDIURSA */
    { 0x02B334, 2, { 202, 217,   0 } },  /* JohtoGrassWildMons DARK_CAVE_BLACKTHORN_ENTRANCE slot 10: WOBBUFFET / URSARING */
    { 0x02B336, 2, { 202, 217,   0 } },  /* JohtoGrassWildMons DARK_CAVE_BLACKTHORN_ENTRANCE slot 11: WOBBUFFET / URSARING */
    { 0x02B2F9, 2, {  41, 216,   0 } },  /* JohtoGrassWildMons DARK_CAVE_VIOLET_ENTRANCE slot 4: ZUBAT / TEDDIURSA */
    { 0x02AFD4, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 1: GOLBAT / ZUBAT */
    { 0x02AFD6, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 2: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AFDA, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 4: ZUBAT / GOLBAT */
    { 0x02AFDC, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 5: JYNX / GOLBAT */
    { 0x02AFDE, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 6: JYNX / GOLBAT */
    { 0x02AFE2, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 8: GOLBAT / ZUBAT */
    { 0x02AFE4, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 9: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AFE8, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 11: JYNX / GOLBAT */
    { 0x02AFEA, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 12: JYNX / GOLBAT */
    { 0x02AFEC, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 13: JYNX / GOLBAT */
    { 0x02AFEE, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 14: SWINUB / DELIBIRD */
    { 0x02AFF0, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 15: GOLBAT / ZUBAT */
    { 0x02AFF2, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 16: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AFF4, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 17: SWINUB / DELIBIRD */
    { 0x02AFF6, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 18: ZUBAT / GOLBAT */
    { 0x02AFF8, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 19: JYNX / GOLBAT */
    { 0x02AFFA, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 20: JYNX / GOLBAT */
    { 0x02B003, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 1: GOLBAT / ZUBAT */
    { 0x02B005, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 2: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B009, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 4: ZUBAT / GOLBAT */
    { 0x02B00B, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 5: JYNX / GOLBAT */
    { 0x02B011, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 8: GOLBAT / ZUBAT */
    { 0x02B013, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 9: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B017, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 11: JYNX / GOLBAT */
    { 0x02B019, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 12: JYNX / GOLBAT */
    { 0x02B01D, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 14: SWINUB / DELIBIRD */
    { 0x02B01F, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 15: GOLBAT / ZUBAT */
    { 0x02B021, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 16: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B023, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 17: SWINUB / DELIBIRD */
    { 0x02B025, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 18: ZUBAT / GOLBAT */
    { 0x02B027, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 19: JYNX / GOLBAT */
    { 0x02B029, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 20: JYNX / SNEASEL */
    { 0x02B061, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 1: GOLBAT / ZUBAT */
    { 0x02B063, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 2: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B067, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 4: ZUBAT / GOLBAT */
    { 0x02B06F, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 8: GOLBAT / ZUBAT */
    { 0x02B071, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 9: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B075, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 11: JYNX / GOLBAT */
    { 0x02B07B, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 14: SWINUB / DELIBIRD */
    { 0x02B07D, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 15: GOLBAT / ZUBAT */
    { 0x02B07F, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 16: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B081, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 17: SWINUB / DELIBIRD */
    { 0x02B083, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 18: ZUBAT / GOLBAT */
    { 0x02B085, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 19: JYNX / SNEASEL */
    { 0x02B087, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 20: JYNX / SNEASEL */
    { 0x02B032, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 1: GOLBAT / ZUBAT */
    { 0x02B034, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 2: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B038, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 4: ZUBAT / GOLBAT */
    { 0x02B040, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 8: GOLBAT / ZUBAT */
    { 0x02B042, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 9: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B046, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 11: JYNX / GOLBAT */
    { 0x02B04C, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 14: SWINUB / DELIBIRD */
    { 0x02B04E, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 15: GOLBAT / ZUBAT */
    { 0x02B050, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 16: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B052, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 17: SWINUB / DELIBIRD */
    { 0x02B054, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 18: ZUBAT / GOLBAT */
    { 0x02B056, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 19: JYNX / SNEASEL */
    { 0x02B058, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 20: JYNX / SNEASEL */
    { 0x02B090, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 1: GOLBAT / ZUBAT */
    { 0x02B092, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 2: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B096, 2, {  41, 124,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 4: ZUBAT / JYNX */
    { 0x02B09E, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 8: GOLBAT / ZUBAT */
    { 0x02B0A0, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 9: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B0AA, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 14: SWINUB / DELIBIRD */
    { 0x02B0AC, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 15: GOLBAT / ZUBAT */
    { 0x02B0AE, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 16: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02B0B0, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 17: SWINUB / DELIBIRD */
    { 0x02B0B2, 2, {  41, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 18: ZUBAT / SNEASEL */
    { 0x02B0B4, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 19: JYNX / SNEASEL */
    { 0x02B0B6, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 20: JYNX / SNEASEL */
    { 0x02AEE7, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 0: CATERPIE / WEEDLE */
    { 0x02AEE9, 3, {  11,  14,  13 } },  /* JohtoGrassWildMons ILEX_FOREST slot 1: METAPOD / KAKUNA / WEEDLE */
    { 0x02AEEB, 3, {  10,  13,  11 } },  /* JohtoGrassWildMons ILEX_FOREST slot 2: CATERPIE / WEEDLE / METAPOD */
    { 0x02AEED, 2, {  46,  14,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 3: PARAS / KAKUNA */
    { 0x02AEEF, 2, {  41,  16,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 4: ZUBAT / PIDGEY */
    { 0x02AEF5, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 7: CATERPIE / WEEDLE */
    { 0x02AEF7, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 8: CATERPIE / WEEDLE */
    { 0x02AEF9, 2, {  11,  14,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 9: METAPOD / KAKUNA */
    { 0x02AEFB, 2, {  11,  14,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 10: METAPOD / KAKUNA */
    { 0x02AEFD, 2, {  41,  16,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 11: ZUBAT / PIDGEY */
    { 0x02AF05, 2, {  43,  48,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 15: ODDISH / VENONAT */
    { 0x02AF07, 2, {  41,  43,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 16: ZUBAT / ODDISH */
    { 0x02AF09, 2, {  46,  54,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 17: PARAS / PSYDUCK */
    { 0x02AF0B, 2, {  41, 163,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 18: ZUBAT / HOOTHOOT */
    { 0x02AF47, 2, {  66,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 1: MACHOP / RATTATA */
    { 0x02AF49, 2, {  74,  66,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 2: GEODUDE / MACHOP */
    { 0x02AF4B, 2, {  19,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 3: RATTATA / RATICATE */
    { 0x02AF4D, 2, {  66,  41,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 4: MACHOP / ZUBAT */
    { 0x02AF4F, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 5: ZUBAT / GOLBAT */
    { 0x02AF51, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 6: ZUBAT / GOLBAT */
    { 0x02AF55, 2, {  66,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 8: MACHOP / RATTATA */
    { 0x02AF57, 2, {  74,  66,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 9: GEODUDE / MACHOP */
    { 0x02AF59, 2, {  19,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 10: RATTATA / RATICATE */
    { 0x02AF5B, 2, {  66,  41,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 11: MACHOP / ZUBAT */
    { 0x02AF5D, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 12: ZUBAT / GOLBAT */
    { 0x02AF5F, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 13: ZUBAT / GOLBAT */
    { 0x02AF63, 2, {  66,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 15: MACHOP / RATTATA */
    { 0x02AF65, 2, {  74,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 16: GEODUDE / RATICATE */
    { 0x02AF67, 2, {  19,  41,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 17: RATTATA / ZUBAT */
    { 0x02AF69, 2, {  66, 183,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 18: MACHOP / MARILL */
    { 0x02AF6B, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 19: ZUBAT / GOLBAT */
    { 0x02AF6D, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 20: ZUBAT / GOLBAT */
    { 0x02AF16, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 0: ZUBAT / RATTATA */
    { 0x02AF1C, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 3: RATTATA / GOLBAT */
    { 0x02AF20, 2, {  19,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 5: RATTATA / RATICATE */
    { 0x02AF22, 2, { 183,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 6: MARILL / RATICATE */
    { 0x02AF24, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 7: ZUBAT / RATTATA */
    { 0x02AF2A, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 10: RATTATA / GOLBAT */
    { 0x02AF2E, 2, {  19,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 12: RATTATA / RATICATE */
    { 0x02AF30, 2, { 183,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 13: MARILL / RATICATE */
    { 0x02AF32, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 14: ZUBAT / RATTATA */
    { 0x02AF36, 2, {  66, 183,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 16: MACHOP / MARILL */
    { 0x02AF38, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 17: RATTATA / GOLBAT */
    { 0x02AF3C, 2, {  19,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 19: RATTATA / RATICATE */
    { 0x02AF3E, 2, { 183,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 20: MARILL / RATICATE */
    { 0x02AF92, 2, {  67,  74,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_2F_INSIDE slot 15: MACHOKE / GEODUDE */
    { 0x02AF94, 2, {  74,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_2F_INSIDE slot 16: GEODUDE / RATICATE */
    { 0x02AF96, 2, {  20,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_2F_INSIDE slot 17: RATICATE / GOLBAT */
    { 0x02AF98, 2, {  66, 183,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_2F_INSIDE slot 18: MACHOP / MARILL */
    { 0x02AFA7, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_B1F slot 2: RATTATA / GOLBAT */
    { 0x02AFB5, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_B1F slot 9: RATTATA / GOLBAT */
    { 0x02AFC3, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_B1F slot 16: RATTATA / GOLBAT */
    { 0x02AFC5, 2, {  66, 183,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_B1F slot 17: MACHOP / MARILL */
    { 0x02AD6F, 3, {  10,  13,  32 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 0: CATERPIE / WEEDLE / NIDORAN_M */
    { 0x02AD71, 3, {  11,  14,  29 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 1: METAPOD / KAKUNA / NIDORAN_F */
    { 0x02AD73, 3, {  10,  13, 165 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 2: CATERPIE / WEEDLE / LEDYBA */
    { 0x02AD77, 2, {  16,  10,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 4: PIDGEY / CATERPIE */
    { 0x02AD79, 2, {  16,  13,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 5: PIDGEY / WEEDLE */
    { 0x02AD7B, 2, {  16,  13,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 6: PIDGEY / WEEDLE */
    { 0x02AD7D, 3, {  10,  13,  29 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 7: CATERPIE / WEEDLE / NIDORAN_F */
    { 0x02AD7F, 3, {  11,  14,  32 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 8: METAPOD / KAKUNA / NIDORAN_M */
    { 0x02AD85, 2, { 191,  10,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 11: SUNKERN / CATERPIE */
    { 0x02AD87, 2, {  16,  13,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 12: PIDGEY / WEEDLE */
    { 0x02AD89, 2, {  16,  13,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 13: PIDGEY / WEEDLE */
    { 0x02AD8B, 2, { 163,  54,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 14: HOOTHOOT / PSYDUCK */
    { 0x02AD8F, 2, { 163, 167,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 16: HOOTHOOT / SPINARAK */
    { 0x02AD93, 2, { 163,  48,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 18: HOOTHOOT / VENONAT */
    { 0x02AD95, 2, { 163,  48,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 19: HOOTHOOT / VENONAT */
    { 0x02AD97, 2, { 163,  48,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 20: HOOTHOOT / VENONAT */
    { 0x02B359, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_29 slot 5: PIDGEY / HOPPIP */
    { 0x02B35B, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_29 slot 6: PIDGEY / HOPPIP */
    { 0x02B367, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_29 slot 12: PIDGEY / HOPPIP */
    { 0x02B369, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_29 slot 13: PIDGEY / HOPPIP */
    { 0x02B36D, 2, { 163,  19,   0 } },  /* JohtoGrassWildMons ROUTE_29 slot 15: HOOTHOOT / RATTATA */
    { 0x02B37E, 2, {  16, 165,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 0: PIDGEY / LEDYBA */
    { 0x02B380, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 1: CATERPIE / WEEDLE */
    { 0x02B382, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 2: CATERPIE / WEEDLE */
    { 0x02B384, 3, {  11,  14,  16 } },  /* JohtoGrassWildMons ROUTE_30 slot 3: METAPOD / KAKUNA / PIDGEY */
    { 0x02B386, 2, {  16,  13,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 4: PIDGEY / WEEDLE */
    { 0x02B388, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 5: PIDGEY / HOPPIP */
    { 0x02B38A, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 6: PIDGEY / HOPPIP */
    { 0x02B38E, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 8: CATERPIE / WEEDLE */
    { 0x02B390, 2, {  16,  10,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 9: PIDGEY / CATERPIE */
    { 0x02B392, 3, {  11,  14,  16 } },  /* JohtoGrassWildMons ROUTE_30 slot 10: METAPOD / KAKUNA / PIDGEY */
    { 0x02B394, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 11: CATERPIE / WEEDLE */
    { 0x02B396, 3, {  11,  14, 187 } },  /* JohtoGrassWildMons ROUTE_30 slot 12: METAPOD / KAKUNA / HOPPIP */
    { 0x02B398, 3, {  11,  14, 187 } },  /* JohtoGrassWildMons ROUTE_30 slot 13: METAPOD / KAKUNA / HOPPIP */
    { 0x02B39A, 2, { 167, 163,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 14: SPINARAK / HOOTHOOT */
    { 0x02B39C, 2, {  19, 163,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 15: RATTATA / HOOTHOOT */
    { 0x02B39E, 2, { 163,  60,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 16: HOOTHOOT / POLIWAG */
    { 0x02B3A0, 2, {  19, 163,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 17: RATTATA / HOOTHOOT */
    { 0x02B3A2, 2, { 163,  41,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 18: HOOTHOOT / ZUBAT */
    { 0x02B3AD, 2, {  16, 165,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 0: PIDGEY / LEDYBA */
    { 0x02B3AF, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 1: CATERPIE / WEEDLE */
    { 0x02B3B3, 3, {  11,  14,  16 } },  /* JohtoGrassWildMons ROUTE_31 slot 3: METAPOD / KAKUNA / PIDGEY */
    { 0x02B3B5, 3, {  10,  16,  13 } },  /* JohtoGrassWildMons ROUTE_31 slot 4: CATERPIE / PIDGEY / WEEDLE */
    { 0x02B3B7, 3, {  11,  16, 187 } },  /* JohtoGrassWildMons ROUTE_31 slot 5: METAPOD / PIDGEY / HOPPIP */
    { 0x02B3B9, 3, {  11,  16, 187 } },  /* JohtoGrassWildMons ROUTE_31 slot 6: METAPOD / PIDGEY / HOPPIP */
    { 0x02B3BD, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 8: CATERPIE / WEEDLE */
    { 0x02B3C1, 3, {  11,  14,  16 } },  /* JohtoGrassWildMons ROUTE_31 slot 10: METAPOD / KAKUNA / PIDGEY */
    { 0x02B3C3, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 11: CATERPIE / WEEDLE */
    { 0x02B3C5, 3, {  11,  14, 187 } },  /* JohtoGrassWildMons ROUTE_31 slot 12: METAPOD / KAKUNA / HOPPIP */
    { 0x02B3C7, 3, {  11,  14, 187 } },  /* JohtoGrassWildMons ROUTE_31 slot 13: METAPOD / KAKUNA / HOPPIP */
    { 0x02B3C9, 2, { 167, 163,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 14: SPINARAK / HOOTHOOT */
    { 0x02B3CB, 2, {  19,  60,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 15: RATTATA / POLIWAG */
    { 0x02B3CF, 2, {  19, 163,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 17: RATTATA / HOOTHOOT */
    { 0x02B3D1, 2, { 163,  41,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 18: HOOTHOOT / ZUBAT */
    { 0x02B3D3, 2, { 163,  92,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 19: HOOTHOOT / GASTLY */
    { 0x02B3D5, 2, { 163,  92,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 20: HOOTHOOT / GASTLY */
    { 0x02B3DC, 2, {  69,  23,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 0: BELLSPROUT / EKANS */
    { 0x02B3DE, 2, {  19,  23,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 1: RATTATA / EKANS */
    { 0x02B3E0, 2, { 179,  69,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 2: MAREEP / BELLSPROUT */
    { 0x02B3E4, 2, {  19,  16,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 4: RATTATA / PIDGEY */
    { 0x02B3E6, 2, { 194, 187,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 5: WOOPER / HOPPIP */
    { 0x02B3E8, 2, {  41, 187,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 6: ZUBAT / HOPPIP */
    { 0x02B3EA, 2, {  69,  23,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 7: BELLSPROUT / EKANS */
    { 0x02B3EC, 2, {  19,  23,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 8: RATTATA / EKANS */
    { 0x02B3EE, 2, { 179,  69,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 9: MAREEP / BELLSPROUT */
    { 0x02B3F2, 2, {  19,  16,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 11: RATTATA / PIDGEY */
    { 0x02B3F4, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 12: RATTATA / HOPPIP */
    { 0x02B3F6, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 13: RATTATA / HOPPIP */
    { 0x02B3FA, 2, {  19,  23,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 15: RATTATA / EKANS */
    { 0x02B3FE, 2, { 179,  41,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 17: MAREEP / ZUBAT */
    { 0x02B400, 2, { 194, 163,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 18: WOOPER / HOOTHOOT */
    { 0x02B402, 2, {  41,  92,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 19: ZUBAT / GASTLY */
    { 0x02B404, 2, {  41,  92,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 20: ZUBAT / GASTLY */
    { 0x02B40B, 2, { 187,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 0: HOPPIP / RATTATA */
    { 0x02B40D, 3, {  19,  23,  21 } },  /* JohtoGrassWildMons ROUTE_33 slot 1: RATTATA / EKANS / SPEAROW */
    { 0x02B40F, 2, {  21,  74,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 2: SPEAROW / GEODUDE */
    { 0x02B411, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 3: RATTATA / HOPPIP */
    { 0x02B413, 2, { 187,  23,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 4: HOPPIP / EKANS */
    { 0x02B415, 2, {  41, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 5: ZUBAT / HOPPIP */
    { 0x02B417, 2, {  41, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 6: ZUBAT / HOPPIP */
    { 0x02B419, 2, { 187,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 7: HOPPIP / RATTATA */
    { 0x02B41B, 3, {  19,  23,  21 } },  /* JohtoGrassWildMons ROUTE_33 slot 8: RATTATA / EKANS / SPEAROW */
    { 0x02B41D, 2, {  21,  74,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 9: SPEAROW / GEODUDE */
    { 0x02B41F, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 10: RATTATA / HOPPIP */
    { 0x02B421, 2, { 187,  23,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 11: HOPPIP / EKANS */
    { 0x02B423, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 12: RATTATA / HOPPIP */
    { 0x02B425, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 13: RATTATA / HOPPIP */
    { 0x02B427, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 14: ZUBAT / RATTATA */
    { 0x02B429, 3, {  19,  23,  41 } },  /* JohtoGrassWildMons ROUTE_33 slot 15: RATTATA / EKANS / ZUBAT */
    { 0x02B42B, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 16: RATTATA / GEODUDE */
    { 0x02B42D, 2, {  19,  41,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 17: RATTATA / ZUBAT */
    { 0x02B42F, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 18: ZUBAT / RATTATA */
    { 0x02B431, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 19: ZUBAT / RATTATA */
    { 0x02B433, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 20: ZUBAT / RATTATA */
    { 0x02B43A, 2, {  96, 209,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 0: DROWZEE / SNUBBULL */
    { 0x02B43E, 2, {  96,  16,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 2: DROWZEE / PIDGEY */
    { 0x02B442, 2, {  19,  39,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 4: RATTATA / JIGGLYPUFF */
    { 0x02B448, 2, {  96, 209,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 7: DROWZEE / SNUBBULL */
    { 0x02B44C, 2, {  96,  16,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 9: DROWZEE / PIDGEY */
    { 0x02B450, 2, {  19,  39,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 11: RATTATA / JIGGLYPUFF */
    { 0x02B45A, 2, {  96, 163,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 16: DROWZEE / HOOTHOOT */
    { 0x02B45E, 2, {  19,  39,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 18: RATTATA / JIGGLYPUFF */
    { 0x02B469, 3, {  32,  29, 209 } },  /* JohtoGrassWildMons ROUTE_35 slot 0: NIDORAN_M / NIDORAN_F / SNUBBULL */
    { 0x02B46B, 3, {  29,  32,  16 } },  /* JohtoGrassWildMons ROUTE_35 slot 1: NIDORAN_F / NIDORAN_M / PIDGEY */
    { 0x02B46D, 2, {  96,  58,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 2: DROWZEE / GROWLITHE */
    { 0x02B471, 2, {  16,  39,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 4: PIDGEY / JIGGLYPUFF */
    { 0x02B477, 3, {  32,  29, 209 } },  /* JohtoGrassWildMons ROUTE_35 slot 7: NIDORAN_M / NIDORAN_F / SNUBBULL */
    { 0x02B479, 3, {  29,  32,  16 } },  /* JohtoGrassWildMons ROUTE_35 slot 8: NIDORAN_F / NIDORAN_M / PIDGEY */
    { 0x02B47B, 2, {  96,  58,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 9: DROWZEE / GROWLITHE */
    { 0x02B47F, 2, {  16,  39,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 11: PIDGEY / JIGGLYPUFF */
    { 0x02B485, 3, {  32,  29,  96 } },  /* JohtoGrassWildMons ROUTE_35 slot 14: NIDORAN_M / NIDORAN_F / DROWZEE */
    { 0x02B487, 3, {  29,  32, 163 } },  /* JohtoGrassWildMons ROUTE_35 slot 15: NIDORAN_F / NIDORAN_M / HOOTHOOT */
    { 0x02B489, 2, {  96,  54,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 16: DROWZEE / PSYDUCK */
    { 0x02B48D, 2, { 163,  39,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 18: HOOTHOOT / JIGGLYPUFF */
    { 0x02B498, 3, {  32,  29, 165 } },  /* JohtoGrassWildMons ROUTE_36 slot 0: NIDORAN_M / NIDORAN_F / LEDYBA */
    { 0x02B49A, 3, {  29,  32,  16 } },  /* JohtoGrassWildMons ROUTE_36 slot 1: NIDORAN_F / NIDORAN_M / PIDGEY */
    { 0x02B49C, 2, {  16,  69,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 2: PIDGEY / BELLSPROUT */
    { 0x02B49E, 2, {  58,  37,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 3: GROWLITHE / VULPIX */
    { 0x02B4A0, 2, { 234,  16,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 4: STANTLER / PIDGEY */
    { 0x02B4A6, 3, {  32,  29,  16 } },  /* JohtoGrassWildMons ROUTE_36 slot 7: NIDORAN_M / NIDORAN_F / PIDGEY */
    { 0x02B4A8, 3, {  29,  32,  16 } },  /* JohtoGrassWildMons ROUTE_36 slot 8: NIDORAN_F / NIDORAN_M / PIDGEY */
    { 0x02B4AA, 2, {  16,  69,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 9: PIDGEY / BELLSPROUT */
    { 0x02B4AC, 2, {  58,  37,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 10: GROWLITHE / VULPIX */
    { 0x02B4AE, 2, { 234,  16,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 11: STANTLER / PIDGEY */
    { 0x02B4B0, 3, {  58,  37,  16 } },  /* JohtoGrassWildMons ROUTE_36 slot 12: GROWLITHE / VULPIX / PIDGEY */
    { 0x02B4B2, 3, {  58,  37,  16 } },  /* JohtoGrassWildMons ROUTE_36 slot 13: GROWLITHE / VULPIX / PIDGEY */
    { 0x02B4B4, 3, {  32,  29, 167 } },  /* JohtoGrassWildMons ROUTE_36 slot 14: NIDORAN_M / NIDORAN_F / SPINARAK */
    { 0x02B4B6, 3, {  29,  32, 163 } },  /* JohtoGrassWildMons ROUTE_36 slot 15: NIDORAN_F / NIDORAN_M / HOOTHOOT */
    { 0x02B4B8, 2, { 163,  69,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 16: HOOTHOOT / BELLSPROUT */
    { 0x02B4BA, 3, {  58,  37, 163 } },  /* JohtoGrassWildMons ROUTE_36 slot 17: GROWLITHE / VULPIX / HOOTHOOT */
    { 0x02B4BC, 2, { 234, 163,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 18: STANTLER / HOOTHOOT */
    { 0x02B4BE, 2, { 163,  92,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 19: HOOTHOOT / GASTLY */
    { 0x02B4C0, 2, { 163,  92,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 20: HOOTHOOT / GASTLY */
    { 0x02B4C7, 2, {  16, 165,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 0: PIDGEY / LEDYBA */
    { 0x02B4C9, 2, { 234,  58,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 1: STANTLER / GROWLITHE */
    { 0x02B4CD, 2, {  58,  37,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 3: GROWLITHE / VULPIX */
    { 0x02B4CF, 3, {  16, 165,  17 } },  /* JohtoGrassWildMons ROUTE_37 slot 4: PIDGEY / LEDYBA / PIDGEOTTO */
    { 0x02B4D1, 3, {  16, 165, 166 } },  /* JohtoGrassWildMons ROUTE_37 slot 5: PIDGEY / LEDYBA / LEDIAN */
    { 0x02B4D3, 3, {  16, 165, 166 } },  /* JohtoGrassWildMons ROUTE_37 slot 6: PIDGEY / LEDYBA / LEDIAN */
    { 0x02B4D7, 2, { 234,  58,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 8: STANTLER / GROWLITHE */
    { 0x02B4DB, 2, {  58,  37,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 10: GROWLITHE / VULPIX */
    { 0x02B4DF, 3, {  58,  37,  16 } },  /* JohtoGrassWildMons ROUTE_37 slot 12: GROWLITHE / VULPIX / PIDGEY */
    { 0x02B4E1, 3, {  58,  37,  16 } },  /* JohtoGrassWildMons ROUTE_37 slot 13: GROWLITHE / VULPIX / PIDGEY */
    { 0x02B4E3, 2, { 167, 163,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 14: SPINARAK / HOOTHOOT */
    { 0x02B4E9, 3, {  58,  37, 234 } },  /* JohtoGrassWildMons ROUTE_37 slot 17: GROWLITHE / VULPIX / STANTLER */
    { 0x02B4EB, 3, { 167, 163, 164 } },  /* JohtoGrassWildMons ROUTE_37 slot 18: SPINARAK / HOOTHOOT / NOCTOWL */
    { 0x02B4ED, 3, { 167, 163, 168 } },  /* JohtoGrassWildMons ROUTE_37 slot 19: SPINARAK / HOOTHOOT / ARIADOS */
    { 0x02B4EF, 3, { 167, 163, 168 } },  /* JohtoGrassWildMons ROUTE_37 slot 20: SPINARAK / HOOTHOOT / ARIADOS */
    { 0x02B4F6, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 0: RATTATA / MEOWTH */
    { 0x02B4FC, 2, {  83,  17,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 3: FARFETCH_D / PIDGEOTTO */
    { 0x02B4FE, 2, { 241, 128,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 4: MILTANK / TAUROS */
    { 0x02B500, 2, { 128, 241,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 5: TAUROS / MILTANK */
    { 0x02B502, 2, { 209, 241,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 6: SNUBBULL / MILTANK */
    { 0x02B504, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 7: RATTATA / MEOWTH */
    { 0x02B50A, 2, {  83,  17,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 10: FARFETCH_D / PIDGEOTTO */
    { 0x02B50C, 2, { 241, 128,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 11: MILTANK / TAUROS */
    { 0x02B50E, 2, { 128, 241,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 12: TAUROS / MILTANK */
    { 0x02B510, 2, { 209, 241,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 13: SNUBBULL / MILTANK */
    { 0x02B512, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 14: RATTATA / MEOWTH */
    { 0x02B518, 3, {  19,  52, 164 } },  /* JohtoGrassWildMons ROUTE_38 slot 17: RATTATA / MEOWTH / NOCTOWL */
    { 0x02B51A, 2, { 241,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 18: MILTANK / MEOWTH */
    { 0x02B51C, 2, { 128,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 19: TAUROS / MEOWTH */
    { 0x02B51E, 2, { 209,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 20: SNUBBULL / MEOWTH */
    { 0x02B525, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 0: RATTATA / MEOWTH */
    { 0x02B52B, 2, {  83,  17,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 3: FARFETCH_D / PIDGEOTTO */
    { 0x02B533, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 7: RATTATA / MEOWTH */
    { 0x02B539, 2, {  83,  17,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 10: FARFETCH_D / PIDGEOTTO */
    { 0x02B541, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 14: RATTATA / MEOWTH */
    { 0x02B547, 3, {  19,  52, 164 } },  /* JohtoGrassWildMons ROUTE_39 slot 17: RATTATA / MEOWTH / NOCTOWL */
    { 0x02B549, 2, { 241,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 18: MILTANK / MEOWTH */
    { 0x02B54B, 2, { 128,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 19: TAUROS / MEOWTH */
    { 0x02B54D, 2, { 128,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 20: TAUROS / MEOWTH */
    { 0x02B554, 3, {  56, 179,  23 } },  /* JohtoGrassWildMons ROUTE_42 slot 0: MANKEY / MAREEP / EKANS */
    { 0x02B556, 2, { 179,  21,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 1: MAREEP / SPEAROW */
    { 0x02B558, 3, {  21, 179,  19 } },  /* JohtoGrassWildMons ROUTE_42 slot 2: SPEAROW / MAREEP / RATTATA */
    { 0x02B55A, 2, {  21,  20,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 3: SPEAROW / RATICATE */
    { 0x02B55C, 2, { 180,  24,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 4: FLAAFFY / ARBOK */
    { 0x02B55E, 2, { 180,  22,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 5: FLAAFFY / FEAROW */
    { 0x02B560, 2, { 180,  22,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 6: FLAAFFY / FEAROW */
    { 0x02B562, 3, {  56, 179,  23 } },  /* JohtoGrassWildMons ROUTE_42 slot 7: MANKEY / MAREEP / EKANS */
    { 0x02B564, 2, { 179,  21,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 8: MAREEP / SPEAROW */
    { 0x02B566, 3, {  21, 179,  19 } },  /* JohtoGrassWildMons ROUTE_42 slot 9: SPEAROW / MAREEP / RATTATA */
    { 0x02B568, 2, {  21,  20,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 10: SPEAROW / RATICATE */
    { 0x02B56A, 2, { 180,  24,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 11: FLAAFFY / ARBOK */
    { 0x02B56C, 2, { 180,  22,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 12: FLAAFFY / FEAROW */
    { 0x02B56E, 2, { 180,  22,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 13: FLAAFFY / FEAROW */
    { 0x02B570, 3, {  56, 179,  19 } },  /* JohtoGrassWildMons ROUTE_42 slot 14: MANKEY / MAREEP / RATTATA */
    { 0x02B572, 2, { 179,  41,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 15: MAREEP / ZUBAT */
    { 0x02B574, 3, {  41, 179,  20 } },  /* JohtoGrassWildMons ROUTE_42 slot 16: ZUBAT / MAREEP / RATICATE */
    { 0x02B576, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 17: ZUBAT / GOLBAT */
    { 0x02B578, 2, { 180, 183,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 18: FLAAFFY / MARILL */
    { 0x02B57A, 2, { 180,  42,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 19: FLAAFFY / GOLBAT */
    { 0x02B57C, 2, { 180,  42,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 20: FLAAFFY / GOLBAT */
    { 0x02B583, 2, { 180, 161,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 0: FLAAFFY / SENTRET */
    { 0x02B585, 2, { 203,  17,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 1: GIRAFARIG / PIDGEOTTO */
    { 0x02B587, 2, {  17,  83,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 2: PIDGEOTTO / FARFETCH_D */
    { 0x02B589, 2, { 179, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 3: MAREEP / FURRET */
    { 0x02B58B, 2, {  48,  20,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 4: VENONAT / RATICATE */
    { 0x02B58D, 2, {  17, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 5: PIDGEOTTO / FURRET */
    { 0x02B58F, 2, {  17, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 6: PIDGEOTTO / FURRET */
    { 0x02B591, 2, { 180, 161,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 7: FLAAFFY / SENTRET */
    { 0x02B593, 2, { 203,  17,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 8: GIRAFARIG / PIDGEOTTO */
    { 0x02B595, 2, {  17,  83,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 9: PIDGEOTTO / FARFETCH_D */
    { 0x02B597, 2, { 179, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 10: MAREEP / FURRET */
    { 0x02B599, 2, { 180,  20,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 11: FLAAFFY / RATICATE */
    { 0x02B59B, 2, { 180, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 12: FLAAFFY / FURRET */
    { 0x02B59D, 2, { 180, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 13: FLAAFFY / FURRET */
    { 0x02B59F, 2, { 180,  48,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 14: FLAAFFY / VENONAT */
    { 0x02B5A1, 2, { 203, 164,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 15: GIRAFARIG / NOCTOWL */
    { 0x02B5A3, 2, { 164,  20,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 16: NOCTOWL / RATICATE */
    { 0x02B5A7, 2, { 179,  20,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 18: MAREEP / RATICATE */
    { 0x02B5A9, 2, {  48,  49,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 19: VENONAT / VENOMOTH */
    { 0x02B5AB, 2, {  48,  49,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 20: VENONAT / VENOMOTH */
    { 0x02B5B4, 2, {  70, 108,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 1: WEEPINBELL / LICKITUNG */
    { 0x02B5B8, 2, { 108,  70,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 3: LICKITUNG / WEEPINBELL */
    { 0x02B5BA, 2, {  70, 108,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 4: WEEPINBELL / LICKITUNG */
    { 0x02B5C2, 2, {  70, 108,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 8: WEEPINBELL / LICKITUNG */
    { 0x02B5C6, 2, { 108,  70,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 10: LICKITUNG / WEEPINBELL */
    { 0x02B5C8, 2, {  70, 108,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 11: WEEPINBELL / LICKITUNG */
    { 0x02B5D0, 2, {  70,  60,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 15: WEEPINBELL / POLIWAG */
    { 0x02B5D4, 2, { 108,  70,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 17: LICKITUNG / WEEPINBELL */
    { 0x02B5D6, 2, {  70,  61,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 18: WEEPINBELL / POLIWHIRL */
    { 0x02B5D8, 2, { 108,  61,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 19: LICKITUNG / POLIWHIRL */
    { 0x02B5DA, 2, { 108,  61,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 20: LICKITUNG / POLIWHIRL */
    { 0x02B5E5, 2, { 207,  75,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 2: GLIGAR / GRAVELER */
    { 0x02B5E7, 3, { 216, 231, 232 } },  /* JohtoGrassWildMons ROUTE_45 slot 3: TEDDIURSA / PHANPY / DONPHAN */
    { 0x02B5E9, 2, {  75, 231,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 4: GRAVELER / PHANPY */
    { 0x02B5EB, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 5: GRAVELER / SKARMORY */
    { 0x02B5ED, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 6: GRAVELER / SKARMORY */
    { 0x02B5F3, 2, { 207,  75,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 9: GLIGAR / GRAVELER */
    { 0x02B5F5, 3, { 216, 231, 232 } },  /* JohtoGrassWildMons ROUTE_45 slot 10: TEDDIURSA / PHANPY / DONPHAN */
    { 0x02B5F7, 2, {  75, 232,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 11: GRAVELER / DONPHAN */
    { 0x02B5F9, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 12: GRAVELER / SKARMORY */
    { 0x02B5FB, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 13: GRAVELER / SKARMORY */
    { 0x02B601, 2, { 207,  75,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 16: GLIGAR / GRAVELER */
    { 0x02B603, 3, { 216, 231,  75 } },  /* JohtoGrassWildMons ROUTE_45 slot 17: TEDDIURSA / PHANPY / GRAVELER */
    { 0x02B607, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 19: GRAVELER / SKARMORY */
    { 0x02B609, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 20: GRAVELER / SKARMORY */
    { 0x02B614, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 2: RATTATA / GEODUDE */
    { 0x02B616, 2, {  74,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 3: GEODUDE / RATTATA */
    { 0x02B618, 2, {  21, 231,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 4: SPEAROW / PHANPY */
    { 0x02B61A, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 5: JIGGLYPUFF / RATTATA */
    { 0x02B61C, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 6: JIGGLYPUFF / RATTATA */
    { 0x02B622, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 9: RATTATA / GEODUDE */
    { 0x02B624, 2, {  74,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 10: GEODUDE / RATTATA */
    { 0x02B626, 2, {  21,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 11: SPEAROW / RATTATA */
    { 0x02B628, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 12: JIGGLYPUFF / RATTATA */
    { 0x02B62A, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 13: JIGGLYPUFF / RATTATA */
    { 0x02B630, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 16: RATTATA / GEODUDE */
    { 0x02B632, 2, {  74,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 17: GEODUDE / RATTATA */
    { 0x02B634, 2, {  74,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 18: GEODUDE / RATTATA */
    { 0x02B636, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 19: JIGGLYPUFF / RATTATA */
    { 0x02B638, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 20: JIGGLYPUFF / RATTATA */
    { 0x02ADC2, 2, { 235, 194,   0 } },  /* JohtoGrassWildMons RUINS_OF_ALPH_OUTSIDE slot 18: SMEARGLE / WOOPER */
    { 0x02ADC4, 2, { 235, 195,   0 } },  /* JohtoGrassWildMons RUINS_OF_ALPH_OUTSIDE slot 19: SMEARGLE / QUAGSIRE */
    { 0x02ADC6, 2, { 235, 195,   0 } },  /* JohtoGrassWildMons RUINS_OF_ALPH_OUTSIDE slot 20: SMEARGLE / QUAGSIRE */
    { 0x02B2C2, 2, { 195,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 0: QUAGSIRE / GOLBAT */
    { 0x02B2C4, 2, {  55,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 1: GOLDUCK / GOLBAT */
    { 0x02B2C6, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 2: URSARING / DONPHAN / GOLBAT */
    { 0x02B2C8, 2, { 195,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 3: QUAGSIRE / PARASECT */
    { 0x02B2CA, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 4: GOLBAT / PARASECT */
    { 0x02B2CC, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 5: LARVITAR / PARASECT */
    { 0x02B2CE, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 6: LARVITAR / PARASECT */
    { 0x02B2D0, 2, { 195,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 7: QUAGSIRE / GOLBAT */
    { 0x02B2D2, 2, {  55,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 8: GOLDUCK / GOLBAT */
    { 0x02B2D4, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 9: URSARING / DONPHAN / GOLBAT */
    { 0x02B2D6, 2, { 195,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 10: QUAGSIRE / PARASECT */
    { 0x02B2D8, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 11: GOLBAT / PARASECT */
    { 0x02B2DA, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 12: LARVITAR / PARASECT */
    { 0x02B2DC, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 13: LARVITAR / PARASECT */
    { 0x02B2E0, 2, {  55,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 15: GOLDUCK / GOLBAT */
    { 0x02B2E2, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 16: URSARING / DONPHAN / GOLBAT */
    { 0x02B2E4, 2, { 195,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 17: QUAGSIRE / PARASECT */
    { 0x02B2E6, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 18: GOLBAT / PARASECT */
    { 0x02B2E8, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 19: LARVITAR / PARASECT */
    { 0x02B2EA, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 20: LARVITAR / PARASECT */
    { 0x02B643, 3, { 217, 232,  24 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 2: URSARING / DONPHAN / ARBOK */
    { 0x02B651, 3, { 217, 232,  24 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 9: URSARING / DONPHAN / ARBOK */
    { 0x02B65D, 2, {  77,  61,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 15: PONYTA / POLIWHIRL */
    { 0x02B65F, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 16: URSARING / DONPHAN / GOLBAT */
    { 0x02B661, 2, {  78,  61,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 17: RAPIDASH / POLIWHIRL */
    { 0x02B663, 2, { 215,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 18: SNEASEL / GOLBAT */
    { 0x02B665, 2, { 215,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 19: SNEASEL / GOLBAT */
    { 0x02B667, 2, { 215,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 20: SNEASEL / GOLBAT */
    { 0x02B235, 2, {  95,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 0: ONIX / GRAVELER */
    { 0x02B237, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 1: URSARING / DONPHAN */
    { 0x02B239, 2, {  75,  95,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 2: GRAVELER / ONIX */
    { 0x02B23B, 2, {  75, 126,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 3: GRAVELER / MAGMAR */
    { 0x02B243, 2, {  95,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 7: ONIX / GRAVELER */
    { 0x02B245, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 8: URSARING / DONPHAN */
    { 0x02B247, 2, {  75,  95,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 9: GRAVELER / ONIX */
    { 0x02B249, 2, {  75, 126,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 10: GRAVELER / MAGMAR */
    { 0x02B251, 2, {  95,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 14: ONIX / GRAVELER */
    { 0x02B253, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 15: URSARING / DONPHAN / GOLBAT */
    { 0x02B255, 2, {  75,  95,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 16: GRAVELER / ONIX */
    { 0x02B257, 2, {  75,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 17: GRAVELER / GOLBAT */
    { 0x02B259, 2, {  42,  55,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 18: GOLBAT / GOLDUCK */
    { 0x02B25B, 2, { 246,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 19: LARVITAR / GOLBAT */
    { 0x02B25D, 2, { 246,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 20: LARVITAR / GOLBAT */
    { 0x02B264, 2, { 195,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 0: QUAGSIRE / GOLBAT */
    { 0x02B266, 2, {  55,  67,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 1: GOLDUCK / MACHOKE */
    { 0x02B268, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 2: URSARING / DONPHAN */
    { 0x02B26A, 2, { 195,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 3: QUAGSIRE / PARASECT */
    { 0x02B26C, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 4: GOLBAT / PARASECT */
    { 0x02B272, 2, { 195,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 7: QUAGSIRE / GOLBAT */
    { 0x02B274, 2, {  55,  67,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 8: GOLDUCK / MACHOKE */
    { 0x02B276, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 9: URSARING / DONPHAN */
    { 0x02B278, 2, { 195,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 10: QUAGSIRE / PARASECT */
    { 0x02B27A, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 11: GOLBAT / PARASECT */
    { 0x02B280, 2, { 195,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 14: QUAGSIRE / GOLBAT */
    { 0x02B284, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 16: URSARING / DONPHAN / GOLBAT */
    { 0x02B286, 2, { 200,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 17: MISDREAVUS / PARASECT */
    { 0x02B288, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 18: GOLBAT / PARASECT */
    { 0x02B28A, 2, { 246, 200,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 19: LARVITAR / MISDREAVUS */
    { 0x02B28C, 2, { 246, 200,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 20: LARVITAR / MISDREAVUS */
    { 0x02B297, 2, {  42,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 2: GOLBAT / GRAVELER */
    { 0x02B299, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 3: URSARING / DONPHAN */
    { 0x02B29B, 2, {  55, 246,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 4: GOLDUCK / LARVITAR */
    { 0x02B29F, 2, { 246, 247,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 6: LARVITAR / PUPITAR */
    { 0x02B2A5, 2, {  42,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 9: GOLBAT / GRAVELER */
    { 0x02B2A7, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 10: URSARING / DONPHAN */
    { 0x02B2A9, 2, {  55, 246,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 11: GOLDUCK / LARVITAR */
    { 0x02B2AD, 2, { 246, 247,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 13: LARVITAR / PUPITAR */
    { 0x02B2B3, 2, {  42,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 16: GOLBAT / GRAVELER */
    { 0x02B2B5, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 17: URSARING / DONPHAN / GOLBAT */
    { 0x02B2B9, 2, { 246,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 19: LARVITAR / GOLBAT */
    { 0x02B2BB, 2, { 246,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 20: LARVITAR / GOLBAT */
    { 0x02ADFE, 2, {  27,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_1F slot 1: SANDSHREW / RATTATA */
    { 0x02AE0C, 2, {  27,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_1F slot 8: SANDSHREW / RATTATA */
    { 0x02AE1A, 2, {  27,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_1F slot 15: SANDSHREW / RATTATA */
    { 0x02AE1C, 2, {  41, 194,   0 } },  /* JohtoGrassWildMons UNION_CAVE_1F slot 16: ZUBAT / WOOPER */
    { 0x02AE2D, 3, {  27,  19,  41 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 1: SANDSHREW / RATTATA / ZUBAT */
    { 0x02AE33, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 4: ZUBAT / RATTATA */
    { 0x02AE3B, 3, {  27,  19,  41 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 8: SANDSHREW / RATTATA / ZUBAT */
    { 0x02AE41, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 11: ZUBAT / RATTATA */
    { 0x02AE49, 3, {  27,  19,  41 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 15: SANDSHREW / RATTATA / ZUBAT */
    { 0x02AE4B, 2, {  41, 194,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 16: ZUBAT / WOOPER */
    { 0x02AE4F, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 18: ZUBAT / RATTATA */
    { 0x02AE5C, 2, {  20,  42,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 1: RATICATE / GOLBAT */
    { 0x02AE5E, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 2: GOLBAT / ZUBAT */
    { 0x02AE60, 2, {  74,  20,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 3: GEODUDE / RATICATE */
    { 0x02AE62, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 4: RATTATA / GEODUDE */
    { 0x02AE6A, 2, {  20,  42,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 8: RATICATE / GOLBAT */
    { 0x02AE6C, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 9: GOLBAT / ZUBAT */
    { 0x02AE6E, 2, {  74,  20,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 10: GEODUDE / RATICATE */
    { 0x02AE70, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 11: RATTATA / GEODUDE */
    { 0x02AE78, 2, {  20,  42,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 15: RATICATE / GOLBAT */
    { 0x02AE7A, 2, {  42, 195,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 16: GOLBAT / QUAGSIRE */
    { 0x02AE7C, 2, {  74,  20,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 17: GEODUDE / RATICATE */
    { 0x02AE7E, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 18: RATTATA / GEODUDE */
    { 0x02B1AC, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 2: KRABBY / SEEL */
    { 0x02B1AE, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 3: SEEL / KRABBY */
    { 0x02B1BA, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 9: KRABBY / SEEL */
    { 0x02B1BC, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 10: SEEL / KRABBY */
    { 0x02B1CA, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 17: SEEL / KRABBY */
    { 0x02B1CE, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 19: SEEL / GOLBAT */
    { 0x02B1D0, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 20: SEEL / GOLBAT */
    { 0x02B1DB, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 2: KRABBY / SEEL */
    { 0x02B1DD, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 3: SEEL / KRABBY */
    { 0x02B1E9, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 9: KRABBY / SEEL */
    { 0x02B1EB, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 10: SEEL / KRABBY */
    { 0x02B1F9, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 17: SEEL / KRABBY */
    { 0x02B1FD, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 19: SEEL / GOLBAT */
    { 0x02B1FF, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 20: SEEL / GOLBAT */
    { 0x02B14E, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 2: KRABBY / SEEL */
    { 0x02B150, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 3: SEEL / KRABBY */
    { 0x02B15C, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 9: KRABBY / SEEL */
    { 0x02B15E, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 10: SEEL / KRABBY */
    { 0x02B16C, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 17: SEEL / KRABBY */
    { 0x02B170, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 19: SEEL / GOLBAT */
    { 0x02B172, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 20: SEEL / GOLBAT */
    { 0x02B20A, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 2: KRABBY / SEEL */
    { 0x02B20C, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 3: SEEL / KRABBY */
    { 0x02B218, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 9: KRABBY / SEEL */
    { 0x02B21A, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 10: SEEL / KRABBY */
    { 0x02B228, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 17: SEEL / KRABBY */
    { 0x02B22C, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 19: SEEL / GOLBAT */
    { 0x02B22E, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 20: SEEL / GOLBAT */
    { 0x02B0F0, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 2: KRABBY / SEEL */
    { 0x02B0F2, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 3: SEEL / KRABBY */
    { 0x02B0FE, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 9: KRABBY / SEEL */
    { 0x02B100, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 10: SEEL / KRABBY */
    { 0x02B10E, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 17: SEEL / KRABBY */
    { 0x02B112, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 19: SEEL / GOLBAT */
    { 0x02B114, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 20: SEEL / GOLBAT */
    { 0x02B0C1, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 2: KRABBY / SEEL */
    { 0x02B0C3, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 3: SEEL / KRABBY */
    { 0x02B0CF, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 9: KRABBY / SEEL */
    { 0x02B0D1, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 10: SEEL / KRABBY */
    { 0x02B0DF, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 17: SEEL / KRABBY */
    { 0x02B0E3, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 19: SEEL / GOLBAT */
    { 0x02B0E5, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 20: SEEL / GOLBAT */
    { 0x02B17D, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 2: KRABBY / SEEL */
    { 0x02B17F, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 3: SEEL / KRABBY */
    { 0x02B18B, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 9: KRABBY / SEEL */
    { 0x02B18D, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 10: SEEL / KRABBY */
    { 0x02B19B, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 17: SEEL / KRABBY */
    { 0x02B19F, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 19: SEEL / GOLBAT */
    { 0x02B1A1, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 20: SEEL / GOLBAT */
    { 0x02B11F, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 2: KRABBY / SEEL */
    { 0x02B121, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 3: SEEL / KRABBY */
    { 0x02B12D, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 9: KRABBY / SEEL */
    { 0x02B12F, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 10: SEEL / KRABBY */
    { 0x02B13D, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 17: SEEL / KRABBY */
    { 0x02B141, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 19: SEEL / GOLBAT */
    { 0x02B143, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 20: SEEL / GOLBAT */
    { 0x02B7F9, 2, {  27,  41,   0 } },  /* KantoGrassWildMons MOUNT_MOON slot 2: SANDSHREW / ZUBAT */
    { 0x02B7FD, 2, {  28,  74,   0 } },  /* KantoGrassWildMons MOUNT_MOON slot 4: SANDSLASH / GEODUDE */
    { 0x02B807, 2, {  27,  41,   0 } },  /* KantoGrassWildMons MOUNT_MOON slot 9: SANDSHREW / ZUBAT */
    { 0x02B80B, 2, {  28,  74,   0 } },  /* KantoGrassWildMons MOUNT_MOON slot 11: SANDSLASH / GEODUDE */
    { 0x02B815, 3, {  27,  41,  35 } },  /* KantoGrassWildMons MOUNT_MOON slot 16: SANDSHREW / ZUBAT / CLEFAIRY */
    { 0x02B819, 2, {  28,  74,   0 } },  /* KantoGrassWildMons MOUNT_MOON slot 18: SANDSLASH / GEODUDE */
    { 0x02B82E, 2, { 104, 105,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 5: CUBONE / MAROWAK */
    { 0x02B830, 2, { 104, 105,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 6: CUBONE / MAROWAK */
    { 0x02B83C, 2, { 104, 105,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 12: CUBONE / MAROWAK */
    { 0x02B83E, 2, { 104, 105,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 13: CUBONE / MAROWAK */
    { 0x02B840, 2, { 104,  41,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 14: CUBONE / ZUBAT */
    { 0x02B844, 2, {  66,  74,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 16: MACHOP / GEODUDE */
    { 0x02B846, 2, {  41,  93,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 17: ZUBAT / HAUNTER */
    { 0x02B848, 2, {  67,  41,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 18: MACHOKE / ZUBAT */
    { 0x02B84A, 2, { 104,  41,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 19: CUBONE / ZUBAT */
    { 0x02B84C, 2, { 104,  41,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 20: CUBONE / ZUBAT */
    { 0x02B86F, 2, { 104,  41,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_B1F slot 14: CUBONE / ZUBAT */
    { 0x02B877, 2, { 105,  93,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_B1F slot 18: MAROWAK / HAUNTER */
    { 0x02B879, 2, { 115,  42,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_B1F slot 19: KANGASKHAN / GOLBAT */
    { 0x02B87B, 2, { 115,  42,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_B1F slot 20: KANGASKHAN / GOLBAT */
    { 0x02B904, 2, {  19,  20,   0 } },  /* KantoGrassWildMons ROUTE_1 slot 18: RATTATA / RATICATE */
    { 0x02BA8F, 2, { 195, 105,   0 } },  /* KantoGrassWildMons ROUTE_10_NORTH slot 4: QUAGSIRE / MAROWAK */
    { 0x02BA9D, 2, { 125, 105,   0 } },  /* KantoGrassWildMons ROUTE_10_NORTH slot 11: ELECTABUZZ / MAROWAK */
    { 0x02BAA3, 2, { 195,  48,   0 } },  /* KantoGrassWildMons ROUTE_10_NORTH slot 14: QUAGSIRE / VENONAT */
    { 0x02BAA9, 2, { 195,  49,   0 } },  /* KantoGrassWildMons ROUTE_10_NORTH slot 17: QUAGSIRE / VENOMOTH */
    { 0x02BAAB, 2, {  20,  41,   0 } },  /* KantoGrassWildMons ROUTE_10_NORTH slot 18: RATICATE / ZUBAT */
    { 0x02BAB6, 2, {  96, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 0: DROWZEE / HOPPIP */
    { 0x02BAB8, 2, {  19,  20,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 1: RATTATA / RATICATE */
    { 0x02BABC, 2, {  96,  17,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 3: DROWZEE / PIDGEOTTO */
    { 0x02BABE, 2, {  97,  19,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 4: HYPNO / RATTATA */
    { 0x02BAC0, 2, {  97, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 5: HYPNO / HOPPIP */
    { 0x02BAC2, 2, {  97, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 6: HYPNO / HOPPIP */
    { 0x02BAC4, 2, {  96, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 7: DROWZEE / HOPPIP */
    { 0x02BAC6, 2, {  19,  20,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 8: RATTATA / RATICATE */
    { 0x02BACA, 2, {  96,  17,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 10: DROWZEE / PIDGEOTTO */
    { 0x02BACC, 2, {  97,  19,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 11: HYPNO / RATTATA */
    { 0x02BACE, 2, {  97, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 12: HYPNO / HOPPIP */
    { 0x02BAD0, 2, {  97, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 13: HYPNO / HOPPIP */
    { 0x02BAD4, 2, {  19,  52,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 15: RATTATA / MEOWTH */
    { 0x02BAD8, 2, {  96, 164,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 17: DROWZEE / NOCTOWL */
    { 0x02BADA, 2, {  97,  20,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 18: HYPNO / RATICATE */
    { 0x02BAE5, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 0: NIDORINA / NIDORINO */
    { 0x02BAE7, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 1: NIDORINO / NIDORINA */
    { 0x02BAEF, 2, { 195, 187,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 5: QUAGSIRE / HOPPIP */
    { 0x02BAF3, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 7: NIDORINA / NIDORINO */
    { 0x02BAF5, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 8: NIDORINO / NIDORINA */
    { 0x02BB01, 3, {  30,  33,  48 } },  /* KantoGrassWildMons ROUTE_13 slot 14: NIDORINA / NIDORINO / VENONAT */
    { 0x02BB03, 3, {  33,  30, 195 } },  /* KantoGrassWildMons ROUTE_13 slot 15: NIDORINO / NIDORINA / QUAGSIRE */
    { 0x02BB07, 2, { 195,  49,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 17: QUAGSIRE / VENOMOTH */
    { 0x02BB14, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 0: NIDORINA / NIDORINO */
    { 0x02BB16, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 1: NIDORINO / NIDORINA */
    { 0x02BB1E, 2, { 195, 188,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 5: QUAGSIRE / SKIPLOOM */
    { 0x02BB22, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 7: NIDORINA / NIDORINO */
    { 0x02BB24, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 8: NIDORINO / NIDORINA */
    { 0x02BB30, 3, {  30,  33,  48 } },  /* KantoGrassWildMons ROUTE_14 slot 14: NIDORINA / NIDORINO / VENONAT */
    { 0x02BB32, 3, {  33,  30, 195 } },  /* KantoGrassWildMons ROUTE_14 slot 15: NIDORINO / NIDORINA / QUAGSIRE */
    { 0x02BB36, 2, { 195,  49,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 17: QUAGSIRE / VENOMOTH */
    { 0x02BB43, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 0: NIDORINA / NIDORINO */
    { 0x02BB45, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 1: NIDORINO / NIDORINA */
    { 0x02BB4D, 2, { 195, 187,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 5: QUAGSIRE / HOPPIP */
    { 0x02BB51, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 7: NIDORINA / NIDORINO */
    { 0x02BB53, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 8: NIDORINO / NIDORINA */
    { 0x02BB5F, 3, {  30,  33,  48 } },  /* KantoGrassWildMons ROUTE_15 slot 14: NIDORINA / NIDORINO / VENONAT */
    { 0x02BB61, 3, {  33,  30, 195 } },  /* KantoGrassWildMons ROUTE_15 slot 15: NIDORINO / NIDORINA / QUAGSIRE */
    { 0x02BB65, 2, { 195,  49,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 17: QUAGSIRE / VENOMOTH */
    { 0x02BB7A, 2, { 218,  22,   0 } },  /* KantoGrassWildMons ROUTE_16 slot 4: SLUGMA / FEAROW */
    { 0x02BB96, 2, { 218, 198,   0 } },  /* KantoGrassWildMons ROUTE_16 slot 18: SLUGMA / MURKROW */
    { 0x02BBA9, 2, { 218,  88,   0 } },  /* KantoGrassWildMons ROUTE_17 slot 4: SLUGMA / GRIMER */
    { 0x02BBC3, 2, {  89,  88,   0 } },  /* KantoGrassWildMons ROUTE_17 slot 17: MUK / GRIMER */
    { 0x02BBC5, 2, { 218,  88,   0 } },  /* KantoGrassWildMons ROUTE_17 slot 18: SLUGMA / GRIMER */
    { 0x02BBD8, 2, { 218,  22,   0 } },  /* KantoGrassWildMons ROUTE_18 slot 4: SLUGMA / FEAROW */
    { 0x02BBF2, 2, {  89,  88,   0 } },  /* KantoGrassWildMons ROUTE_18 slot 17: MUK / GRIMER */
    { 0x02BBF4, 2, { 218,  88,   0 } },  /* KantoGrassWildMons ROUTE_18 slot 18: SLUGMA / GRIMER */
    { 0x02B90F, 2, {  10,  13,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 0: CATERPIE / WEEDLE */
    { 0x02B911, 2, {  16, 165,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 1: PIDGEY / LEDYBA */
    { 0x02B913, 3, {  11,  14,  16 } },  /* KantoGrassWildMons ROUTE_2 slot 2: METAPOD / KAKUNA / PIDGEY */
    { 0x02B915, 2, {  12,  15,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 3: BUTTERFREE / BEEDRILL */
    { 0x02B917, 2, {  17, 166,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 4: PIDGEOTTO / LEDIAN */
    { 0x02B91D, 2, {  10,  13,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 7: CATERPIE / WEEDLE */
    { 0x02B921, 3, {  11,  14,  16 } },  /* KantoGrassWildMons ROUTE_2 slot 9: METAPOD / KAKUNA / PIDGEY */
    { 0x02B923, 2, {  16,  12,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 10: PIDGEY / BUTTERFREE */
    { 0x02B92D, 2, { 167, 163,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 15: SPINARAK / HOOTHOOT */
    { 0x02B933, 2, { 168, 164,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 18: ARIADOS / NOCTOWL */
    { 0x02B935, 2, {  25, 164,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 19: PIKACHU / NOCTOWL */
    { 0x02B937, 2, {  25, 164,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 20: PIKACHU / NOCTOWL */
    { 0x02BC01, 2, { 114,  19,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 1: TANGELA / RATTATA */
    { 0x02BC05, 2, { 114,  20,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 3: TANGELA / RATICATE */
    { 0x02BC07, 2, { 114, 122,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 4: TANGELA / MR__MIME */
    { 0x02BC0F, 2, { 114,  19,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 8: TANGELA / RATTATA */
    { 0x02BC13, 2, { 114,  20,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 10: TANGELA / RATICATE */
    { 0x02BC1D, 2, { 114,  19,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 15: TANGELA / RATTATA */
    { 0x02BC21, 2, { 114,  20,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 17: TANGELA / RATICATE */
    { 0x02BC25, 2, { 122, 114,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 19: MR__MIME / TANGELA */
    { 0x02BC27, 2, { 122, 114,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 20: MR__MIME / TANGELA */
    { 0x02BC4C, 2, {  19,  60,   0 } },  /* KantoGrassWildMons ROUTE_22 slot 15: RATTATA / POLIWAG */
    { 0x02BC50, 2, {  19,  60,   0 } },  /* KantoGrassWildMons ROUTE_22 slot 17: RATTATA / POLIWAG */
    { 0x02BC52, 2, {  77,  19,   0 } },  /* KantoGrassWildMons ROUTE_22 slot 18: PONYTA / RATTATA */
    { 0x02BC5D, 2, {  69,  10,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 0: BELLSPROUT / CATERPIE */
    { 0x02BC5F, 2, {  69,  10,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 1: BELLSPROUT / CATERPIE */
    { 0x02BC61, 2, {  63,  11,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 2: ABRA / METAPOD */
    { 0x02BC63, 2, {  70,  63,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 3: WEEPINBELL / ABRA */
    { 0x02BC65, 2, {  48,  69,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 4: VENONAT / BELLSPROUT */
    { 0x02BC67, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 5: WEEPINBELL / BUTTERFREE */
    { 0x02BC69, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 6: WEEPINBELL / BUTTERFREE */
    { 0x02BC6B, 2, {  69,  10,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 7: BELLSPROUT / CATERPIE */
    { 0x02BC6F, 2, {  63,  10,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 9: ABRA / CATERPIE */
    { 0x02BC71, 2, {  70,  63,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 10: WEEPINBELL / ABRA */
    { 0x02BC75, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 12: WEEPINBELL / BUTTERFREE */
    { 0x02BC77, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 13: WEEPINBELL / BUTTERFREE */
    { 0x02BC7D, 2, {  63,  43,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 16: ABRA / ODDISH */
    { 0x02BC7F, 2, {  70,  63,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 17: WEEPINBELL / ABRA */
    { 0x02BC83, 2, {  49,  44,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 19: VENOMOTH / GLOOM */
    { 0x02BC85, 2, {  49,  44,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 20: VENOMOTH / GLOOM */
    { 0x02BC8C, 2, {  16,  10,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 0: PIDGEY / CATERPIE */
    { 0x02BC8E, 2, {  69,  16,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 1: BELLSPROUT / PIDGEY */
    { 0x02BC90, 2, {  48,  17,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 2: VENONAT / PIDGEOTTO */
    { 0x02BC92, 2, {  63,  11,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 3: ABRA / METAPOD */
    { 0x02BC94, 2, {  17,  69,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 4: PIDGEOTTO / BELLSPROUT */
    { 0x02BC96, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 5: WEEPINBELL / BUTTERFREE */
    { 0x02BC98, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 6: WEEPINBELL / BUTTERFREE */
    { 0x02BC9A, 2, {  16,  10,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 7: PIDGEY / CATERPIE */
    { 0x02BC9C, 2, {  69,  16,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 8: BELLSPROUT / PIDGEY */
    { 0x02BC9E, 2, {  16,  17,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 9: PIDGEY / PIDGEOTTO */
    { 0x02BCA0, 2, {  63,  11,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 10: ABRA / METAPOD */
    { 0x02BCA2, 2, {  17,  69,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 11: PIDGEOTTO / BELLSPROUT */
    { 0x02BCA4, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 12: WEEPINBELL / BUTTERFREE */
    { 0x02BCA6, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 13: WEEPINBELL / BUTTERFREE */
    { 0x02BCA8, 2, {  48,  43,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 14: VENONAT / ODDISH */
    { 0x02BCAA, 2, {  43, 163,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 15: ODDISH / HOOTHOOT */
    { 0x02BCAC, 2, {  49,  48,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 16: VENOMOTH / VENONAT */
    { 0x02BCAE, 2, {  63, 164,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 17: ABRA / NOCTOWL */
    { 0x02BCB0, 2, {  70,  69,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 18: WEEPINBELL / BELLSPROUT */
    { 0x02BCB2, 2, {  69, 164,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 19: BELLSPROUT / NOCTOWL */
    { 0x02BCB4, 2, {  69, 164,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 20: BELLSPROUT / NOCTOWL */
    { 0x02BCBD, 2, {  28,  20,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 1: SANDSLASH / RATICATE */
    { 0x02BCC1, 2, {  84,  20,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 3: DODUO / RATICATE */
    { 0x02BCC3, 3, {  85,  24,  84 } },  /* KantoGrassWildMons ROUTE_26 slot 4: DODRIO / ARBOK / DODUO */
    { 0x02BCC5, 2, {  20,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 5: RATICATE / ARBOK */
    { 0x02BCC7, 2, { 195,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 6: QUAGSIRE / ARBOK */
    { 0x02BCCB, 2, {  28,  20,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 8: SANDSLASH / RATICATE */
    { 0x02BCCF, 2, {  84,  20,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 10: DODUO / RATICATE */
    { 0x02BCD1, 2, {  20,  84,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 11: RATICATE / DODUO */
    { 0x02BCD3, 2, {  85,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 12: DODRIO / ARBOK */
    { 0x02BCD5, 2, {  85,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 13: DODRIO / ARBOK */
    { 0x02BCD7, 2, {  20, 164,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 14: RATICATE / NOCTOWL */
    { 0x02BCD9, 2, {  28,  20,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 15: SANDSLASH / RATICATE */
    { 0x02BCDB, 2, {  77, 164,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 16: PONYTA / NOCTOWL */
    { 0x02BCE1, 2, { 195,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 19: QUAGSIRE / ARBOK */
    { 0x02BCE3, 2, { 195,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 20: QUAGSIRE / ARBOK */
    { 0x02BCEC, 2, {  20,  24,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 1: RATICATE / ARBOK */
    { 0x02BCEE, 2, {  84,  20,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 2: DODUO / RATICATE */
    { 0x02BCF0, 2, { 195,  84,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 3: QUAGSIRE / DODUO */
    { 0x02BCF4, 2, {  28,  85,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 5: SANDSLASH / DODRIO */
    { 0x02BCF6, 2, {  28,  85,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 6: SANDSLASH / DODRIO */
    { 0x02BCFA, 2, {  20,  24,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 8: RATICATE / ARBOK */
    { 0x02BCFC, 2, {  84,  20,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 9: DODUO / RATICATE */
    { 0x02BCFE, 2, {  20,  84,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 10: RATICATE / DODUO */
    { 0x02BD02, 2, {  28,  85,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 12: SANDSLASH / DODRIO */
    { 0x02BD04, 2, {  28,  85,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 13: SANDSLASH / DODRIO */
    { 0x02BD08, 3, {  20,  24, 164 } },  /* KantoGrassWildMons ROUTE_27 slot 15: RATICATE / ARBOK / NOCTOWL */
    { 0x02BD0A, 2, { 195,  20,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 16: QUAGSIRE / RATICATE */
    { 0x02BD0C, 2, {  20, 195,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 17: RATICATE / QUAGSIRE */
    { 0x02BD0E, 2, {  77, 164,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 18: PONYTA / NOCTOWL */
    { 0x02BD10, 3, {  28, 195, 164 } },  /* KantoGrassWildMons ROUTE_27 slot 19: SANDSLASH / QUAGSIRE / NOCTOWL */
    { 0x02BD12, 3, {  28, 195, 164 } },  /* KantoGrassWildMons ROUTE_27 slot 20: SANDSLASH / QUAGSIRE / NOCTOWL */
    { 0x02BD1D, 3, { 217, 232,  78 } },  /* KantoGrassWildMons ROUTE_28 slot 2: URSARING / DONPHAN / RAPIDASH */
    { 0x02BD1F, 2, {  78,  24,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 3: RAPIDASH / ARBOK */
    { 0x02BD2B, 3, { 217, 232,  78 } },  /* KantoGrassWildMons ROUTE_28 slot 9: URSARING / DONPHAN / RAPIDASH */
    { 0x02BD2D, 2, {  78,  24,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 10: RAPIDASH / ARBOK */
    { 0x02BD37, 2, {  77,  61,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 15: PONYTA / POLIWHIRL */
    { 0x02BD39, 3, { 217, 232,  42 } },  /* KantoGrassWildMons ROUTE_28 slot 16: URSARING / DONPHAN / GOLBAT */
    { 0x02BD3B, 2, { 215,  61,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 17: SNEASEL / POLIWHIRL */
    { 0x02BD3D, 2, {  78,  42,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 18: RAPIDASH / GOLBAT */
    { 0x02BD3F, 2, {  78,  42,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 19: RAPIDASH / GOLBAT */
    { 0x02BD41, 2, {  78,  42,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 20: RAPIDASH / GOLBAT */
    { 0x02B942, 2, {  21,  23,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 2: SPEAROW / EKANS */
    { 0x02B944, 2, {  39,  20,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 3: JIGGLYPUFF / RATICATE */
    { 0x02B946, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 4: RATTATA / ARBOK */
    { 0x02B948, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 5: SPEAROW / SANDSHREW */
    { 0x02B94A, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 6: SPEAROW / SANDSHREW */
    { 0x02B950, 2, {  21,  23,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 9: SPEAROW / EKANS */
    { 0x02B952, 2, {  39,  20,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 10: JIGGLYPUFF / RATICATE */
    { 0x02B954, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 11: RATTATA / ARBOK */
    { 0x02B956, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 12: SPEAROW / SANDSHREW */
    { 0x02B958, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 13: SPEAROW / SANDSHREW */
    { 0x02B95C, 2, {  41,  19,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 15: ZUBAT / RATTATA */
    { 0x02B95E, 3, {  19,  23,  20 } },  /* KantoGrassWildMons ROUTE_3 slot 16: RATTATA / EKANS / RATICATE */
    { 0x02B960, 2, {  39,  41,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 17: JIGGLYPUFF / ZUBAT */
    { 0x02B962, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 18: RATTATA / ARBOK */
    { 0x02B964, 2, {  19,  35,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 19: RATTATA / CLEFAIRY */
    { 0x02B966, 2, {  19,  35,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 20: RATTATA / CLEFAIRY */
    { 0x02B971, 2, {  21,  23,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 2: SPEAROW / EKANS */
    { 0x02B973, 2, {  39,  20,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 3: JIGGLYPUFF / RATICATE */
    { 0x02B975, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 4: RATTATA / ARBOK */
    { 0x02B977, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 5: SPEAROW / SANDSHREW */
    { 0x02B979, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 6: SPEAROW / SANDSHREW */
    { 0x02B97F, 2, {  21,  23,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 9: SPEAROW / EKANS */
    { 0x02B981, 2, {  39,  20,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 10: JIGGLYPUFF / RATICATE */
    { 0x02B983, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 11: RATTATA / ARBOK */
    { 0x02B985, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 12: SPEAROW / SANDSHREW */
    { 0x02B987, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 13: SPEAROW / SANDSHREW */
    { 0x02B989, 2, {  21,  19,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 14: SPEAROW / RATTATA */
    { 0x02B98B, 2, {  41,  19,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 15: ZUBAT / RATTATA */
    { 0x02B98D, 3, {  19,  23,  20 } },  /* KantoGrassWildMons ROUTE_4 slot 16: RATTATA / EKANS / RATICATE */
    { 0x02B98F, 2, {  39,  41,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 17: JIGGLYPUFF / ZUBAT */
    { 0x02B991, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 18: RATTATA / ARBOK */
    { 0x02B993, 2, {  19,  35,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 19: RATTATA / CLEFAIRY */
    { 0x02B995, 2, {  19,  35,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 20: RATTATA / CLEFAIRY */
    { 0x02B99E, 2, {  69, 209,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 1: BELLSPROUT / SNUBBULL */
    { 0x02B9A0, 3, {  16,  52,  17 } },  /* KantoGrassWildMons ROUTE_5 slot 2: PIDGEY / MEOWTH / PIDGEOTTO */
    { 0x02B9A2, 2, {  16,  63,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 3: PIDGEY / ABRA */
    { 0x02B9A4, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 4: ABRA / JIGGLYPUFF */
    { 0x02B9AC, 2, {  69, 209,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 8: BELLSPROUT / SNUBBULL */
    { 0x02B9AE, 3, {  16,  52,  17 } },  /* KantoGrassWildMons ROUTE_5 slot 9: PIDGEY / MEOWTH / PIDGEOTTO */
    { 0x02B9B0, 2, {  16,  63,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 10: PIDGEY / ABRA */
    { 0x02B9B2, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 11: ABRA / JIGGLYPUFF */
    { 0x02B9B8, 2, {  43, 163,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 14: ODDISH / HOOTHOOT */
    { 0x02B9BA, 2, {  43,  52,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 15: ODDISH / MEOWTH */
    { 0x02B9BC, 2, {  69, 164,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 16: BELLSPROUT / NOCTOWL */
    { 0x02B9BE, 2, {  44,  63,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 17: GLOOM / ABRA */
    { 0x02B9C0, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 18: ABRA / JIGGLYPUFF */
    { 0x02B9CB, 2, {  16,  19,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 0: PIDGEY / RATTATA */
    { 0x02B9CD, 2, {  69, 209,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 1: BELLSPROUT / SNUBBULL */
    { 0x02B9CF, 3, {  16,  52,  81 } },  /* KantoGrassWildMons ROUTE_6 slot 2: PIDGEY / MEOWTH / MAGNEMITE */
    { 0x02B9D1, 2, {  81,  20,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 3: MAGNEMITE / RATICATE */
    { 0x02B9D3, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 4: ABRA / JIGGLYPUFF */
    { 0x02B9D5, 2, {  63, 210,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 5: ABRA / GRANBULL */
    { 0x02B9D7, 2, {  63, 210,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 6: ABRA / GRANBULL */
    { 0x02B9D9, 2, {  16,  19,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 7: PIDGEY / RATTATA */
    { 0x02B9DB, 2, {  69, 209,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 8: BELLSPROUT / SNUBBULL */
    { 0x02B9DD, 3, {  16,  52,  81 } },  /* KantoGrassWildMons ROUTE_6 slot 9: PIDGEY / MEOWTH / MAGNEMITE */
    { 0x02B9DF, 2, {  81,  20,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 10: MAGNEMITE / RATICATE */
    { 0x02B9E1, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 11: ABRA / JIGGLYPUFF */
    { 0x02B9E3, 2, {  63, 210,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 12: ABRA / GRANBULL */
    { 0x02B9E5, 2, {  63, 210,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 13: ABRA / GRANBULL */
    { 0x02B9E7, 2, {  43,  52,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 14: ODDISH / MEOWTH */
    { 0x02B9E9, 3, {  43,  52,  96 } },  /* KantoGrassWildMons ROUTE_6 slot 15: ODDISH / MEOWTH / DROWZEE */
    { 0x02B9EB, 2, {  69,  81,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 16: BELLSPROUT / MAGNEMITE */
    { 0x02B9ED, 2, {  81,  54,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 17: MAGNEMITE / PSYDUCK */
    { 0x02B9EF, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 18: ABRA / JIGGLYPUFF */
    { 0x02B9F1, 2, {  63,  20,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 19: ABRA / RATICATE */
    { 0x02B9F3, 2, {  63,  20,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 20: ABRA / RATICATE */
    { 0x02B9FA, 2, {  19,  52,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 0: RATTATA / MEOWTH */
    { 0x02B9FE, 3, {  58,  37, 209 } },  /* KantoGrassWildMons ROUTE_7 slot 2: GROWLITHE / VULPIX / SNUBBULL */
    { 0x02BA02, 3, {  19,  53,  39 } },  /* KantoGrassWildMons ROUTE_7 slot 4: RATTATA / PERSIAN / JIGGLYPUFF */
    { 0x02BA04, 2, {  19,  63,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 5: RATTATA / ABRA */
    { 0x02BA06, 2, {  19,  63,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 6: RATTATA / ABRA */
    { 0x02BA08, 2, {  19,  52,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 7: RATTATA / MEOWTH */
    { 0x02BA0C, 3, {  58,  37, 209 } },  /* KantoGrassWildMons ROUTE_7 slot 9: GROWLITHE / VULPIX / SNUBBULL */
    { 0x02BA10, 3, {  19,  53,  39 } },  /* KantoGrassWildMons ROUTE_7 slot 11: RATTATA / PERSIAN / JIGGLYPUFF */
    { 0x02BA12, 3, {  58,  37,  63 } },  /* KantoGrassWildMons ROUTE_7 slot 12: GROWLITHE / VULPIX / ABRA */
    { 0x02BA14, 3, {  58,  37,  63 } },  /* KantoGrassWildMons ROUTE_7 slot 13: GROWLITHE / VULPIX / ABRA */
    { 0x02BA16, 2, {  19,  52,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 14: RATTATA / MEOWTH */
    { 0x02BA1A, 3, {  58,  37, 228 } },  /* KantoGrassWildMons ROUTE_7 slot 16: GROWLITHE / VULPIX / HOUNDOUR */
    { 0x02BA1C, 2, {  20,  53,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 17: RATICATE / PERSIAN */
    { 0x02BA1E, 3, { 198,  53,  39 } },  /* KantoGrassWildMons ROUTE_7 slot 18: MURKROW / PERSIAN / JIGGLYPUFF */
    { 0x02BA20, 2, { 228,  63,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 19: HOUNDOUR / ABRA */
    { 0x02BA22, 2, { 228,  63,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 20: HOUNDOUR / ABRA */
    { 0x02BA29, 3, {  17,  52, 209 } },  /* KantoGrassWildMons ROUTE_8 slot 0: PIDGEOTTO / MEOWTH / SNUBBULL */
    { 0x02BA2F, 2, {  58,  37,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 3: GROWLITHE / VULPIX */
    { 0x02BA31, 2, {  17,  39,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 4: PIDGEOTTO / JIGGLYPUFF */
    { 0x02BA37, 3, {  17,  52, 209 } },  /* KantoGrassWildMons ROUTE_8 slot 7: PIDGEOTTO / MEOWTH / SNUBBULL */
    { 0x02BA3D, 2, {  58,  37,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 10: GROWLITHE / VULPIX */
    { 0x02BA3F, 2, {  17,  39,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 11: PIDGEOTTO / JIGGLYPUFF */
    { 0x02BA45, 2, { 164,  52,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 14: NOCTOWL / MEOWTH */
    { 0x02BA47, 2, {  93, 164,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 15: HAUNTER / NOCTOWL */
    { 0x02BA4B, 2, { 164,  93,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 17: NOCTOWL / HAUNTER */
    { 0x02BA4D, 3, {  58,  37,  39 } },  /* KantoGrassWildMons ROUTE_8 slot 18: GROWLITHE / VULPIX / JIGGLYPUFF */
    { 0x02BA58, 2, {  56,  19,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 0: MANKEY / RATTATA */
    { 0x02BA5A, 2, {  19,  21,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 1: RATTATA / SPEAROW */
    { 0x02BA5C, 2, {  21,  20,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 2: SPEAROW / RATICATE */
    { 0x02BA5E, 2, {  20,  22,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 3: RATICATE / FEAROW */
    { 0x02BA62, 3, {  57,  20, 105 } },  /* KantoGrassWildMons ROUTE_9 slot 5: PRIMEAPE / RATICATE / MAROWAK */
    { 0x02BA64, 3, {  57,  20, 105 } },  /* KantoGrassWildMons ROUTE_9 slot 6: PRIMEAPE / RATICATE / MAROWAK */
    { 0x02BA66, 2, {  56,  19,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 7: MANKEY / RATTATA */
    { 0x02BA68, 2, {  19,  21,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 8: RATTATA / SPEAROW */
    { 0x02BA6A, 2, {  21,  20,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 9: SPEAROW / RATICATE */
    { 0x02BA6C, 2, {  20,  22,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 10: RATICATE / FEAROW */
    { 0x02BA70, 3, {  57,  20, 105 } },  /* KantoGrassWildMons ROUTE_9 slot 12: PRIMEAPE / RATICATE / MAROWAK */
    { 0x02BA72, 3, {  57,  20, 105 } },  /* KantoGrassWildMons ROUTE_9 slot 13: PRIMEAPE / RATICATE / MAROWAK */
    { 0x02BA74, 2, {  56,  19,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 14: MANKEY / RATTATA */
    { 0x02BA76, 2, {  19,  48,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 15: RATTATA / VENONAT */
    { 0x02BA7A, 2, {  19,  49,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 17: RATTATA / VENOMOTH */
    { 0x02BA7C, 2, {  20,  41,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 18: RATICATE / ZUBAT */
    { 0x02BA7E, 2, {  57,  20,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 19: PRIMEAPE / RATICATE */
    { 0x02BA80, 2, {  57,  20,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 20: PRIMEAPE / RATICATE */
    { 0x02B884, 2, {  42, 111,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 1: GOLBAT / RHYHORN */
    { 0x02B886, 3, { 217, 232,  95 } },  /* KantoGrassWildMons VICTORY_ROAD slot 2: URSARING / DONPHAN / ONIX */
    { 0x02B888, 2, {  95,  42,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 3: ONIX / GOLBAT */
    { 0x02B88A, 2, {  95,  28,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 4: ONIX / SANDSLASH */
    { 0x02B88C, 2, { 111, 112,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 5: RHYHORN / RHYDON */
    { 0x02B88E, 2, { 111, 112,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 6: RHYHORN / RHYDON */
    { 0x02B892, 2, {  42, 111,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 8: GOLBAT / RHYHORN */
    { 0x02B894, 3, { 217, 232,  95 } },  /* KantoGrassWildMons VICTORY_ROAD slot 9: URSARING / DONPHAN / ONIX */
    { 0x02B896, 2, {  95,  42,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 10: ONIX / GOLBAT */
    { 0x02B898, 2, {  95,  28,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 11: ONIX / SANDSLASH */
    { 0x02B89A, 2, { 111, 112,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 12: RHYHORN / RHYDON */
    { 0x02B89C, 2, { 111, 112,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 13: RHYHORN / RHYDON */
    { 0x02B89E, 2, {  75,  42,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 14: GRAVELER / GOLBAT */
    { 0x02B8A0, 2, {  42,  75,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 15: GOLBAT / GRAVELER */
    { 0x02B8A2, 3, { 217, 232,  95 } },  /* KantoGrassWildMons VICTORY_ROAD slot 16: URSARING / DONPHAN / ONIX */
    { 0x02B8A4, 2, {  95,  75,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 17: ONIX / GRAVELER */
    { 0x02B8A6, 2, {  95,  75,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 18: ONIX / GRAVELER */
    { 0x02B8A8, 2, { 111,  75,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 19: RHYHORN / GRAVELER */
    { 0x02B8AA, 2, { 111,  75,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 20: RHYHORN / GRAVELER */
    { 0x02B6AE, 2, { 118, 183,   0 } },  /* JohtoWaterWildMons MOUNT_MORTAR_1F_OUTSIDE slot 1: GOLDEEN / MARILL */
    { 0x02B6B7, 2, { 118, 183,   0 } },  /* JohtoWaterWildMons MOUNT_MORTAR_2F_INSIDE slot 1: GOLDEEN / MARILL */
    { 0x02B6C0, 2, { 118, 183,   0 } },  /* JohtoWaterWildMons MOUNT_MORTAR_B1F slot 1: GOLDEEN / MARILL */
    { 0x02B740, 2, { 226,  72,   0 } },  /* JohtoWaterWildMons ROUTE_41 slot 2: MANTINE / TENTACOOL */
    { 0x02B6E4, 2, { 119,  55,   0 } },  /* JohtoWaterWildMons SILVER_CAVE_ROOM_2 slot 1: SEAKING / GOLDUCK */
};

#endif /* GEN2_WILD_DIFFS_GS_GEN_H */
