/* AUTO-GENERATED by runtime/tools/generate_wild_diffs_gen2.py.
 * Source: pret/pokecrystal-decomp.
 * Do not edit by hand. Re-run the script if pret
 * sources change. */

#ifndef GEN2_WILD_DIFFS_CRYSTAL_GEN_H
#define GEN2_WILD_DIFFS_CRYSTAL_GEN_H

#include <stdint.h>

#ifndef GBGEN2_WILDDIFF_STRUCT_DEFINED
#define GBGEN2_WILDDIFF_STRUCT_DEFINED
typedef struct {
    uint32_t rom_offset;
    uint8_t  count;
    uint8_t  species[3];
} GBGen2WildDiff;
#endif

#define GEN2_WILD_DIFFS_CRYSTAL_COUNT  859

static const GBGen2WildDiff GEN2_WILD_DIFFS_CRYSTAL[GEN2_WILD_DIFFS_CRYSTAL_COUNT] = {
    { 0x02A7CD, 2, { 109,  19,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_1F slot 4: KOFFING / RATTATA */
    { 0x02A7DB, 2, { 109,  19,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_1F slot 11: KOFFING / RATTATA */
    { 0x02A7E9, 2, { 109,  19,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_1F slot 18: KOFFING / RATTATA */
    { 0x02A7FA, 2, {  19,  41,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 3: RATTATA / ZUBAT */
    { 0x02A7FC, 2, {  41, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 4: ZUBAT / KOFFING */
    { 0x02A7FE, 2, { 126, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 5: MAGMAR / KOFFING */
    { 0x02A800, 2, { 126, 110,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 6: MAGMAR / WEEZING */
    { 0x02A808, 2, { 126,  41,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 10: MAGMAR / ZUBAT */
    { 0x02A80A, 2, {  41, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 11: ZUBAT / KOFFING */
    { 0x02A80C, 2, {  19, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 12: RATTATA / KOFFING */
    { 0x02A80E, 2, {  19, 110,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 13: RATTATA / WEEZING */
    { 0x02A816, 2, {  19,  41,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 17: RATTATA / ZUBAT */
    { 0x02A818, 2, {  41, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 18: ZUBAT / KOFFING */
    { 0x02A81A, 2, { 126, 109,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 19: MAGMAR / KOFFING */
    { 0x02A81C, 2, { 126, 110,   0 } },  /* JohtoGrassWildMons BURNED_TOWER_B1F slot 20: MAGMAR / WEEZING */
    { 0x02ADDA, 2, { 202, 217,   0 } },  /* JohtoGrassWildMons DARK_CAVE_BLACKTHORN_ENTRANCE slot 3: WOBBUFFET / URSARING */
    { 0x02ADDC, 2, { 202, 216,   0 } },  /* JohtoGrassWildMons DARK_CAVE_BLACKTHORN_ENTRANCE slot 4: WOBBUFFET / TEDDIURSA */
    { 0x02ADE8, 2, { 202, 217,   0 } },  /* JohtoGrassWildMons DARK_CAVE_BLACKTHORN_ENTRANCE slot 10: WOBBUFFET / URSARING */
    { 0x02ADEA, 2, { 202, 217,   0 } },  /* JohtoGrassWildMons DARK_CAVE_BLACKTHORN_ENTRANCE slot 11: WOBBUFFET / URSARING */
    { 0x02ADAD, 2, {  41, 216,   0 } },  /* JohtoGrassWildMons DARK_CAVE_VIOLET_ENTRANCE slot 4: ZUBAT / TEDDIURSA */
    { 0x02AA88, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 1: GOLBAT / ZUBAT */
    { 0x02AA8A, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 2: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AA8E, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 4: ZUBAT / GOLBAT */
    { 0x02AA90, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 5: JYNX / GOLBAT */
    { 0x02AA92, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 6: JYNX / GOLBAT */
    { 0x02AA96, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 8: GOLBAT / ZUBAT */
    { 0x02AA98, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 9: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AA9C, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 11: JYNX / GOLBAT */
    { 0x02AA9E, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 12: JYNX / GOLBAT */
    { 0x02AAA0, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 13: JYNX / GOLBAT */
    { 0x02AAA2, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 14: SWINUB / DELIBIRD */
    { 0x02AAA4, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 15: GOLBAT / ZUBAT */
    { 0x02AAA6, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 16: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AAA8, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 17: SWINUB / DELIBIRD */
    { 0x02AAAA, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 18: ZUBAT / GOLBAT */
    { 0x02AAAC, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 19: JYNX / GOLBAT */
    { 0x02AAAE, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_1F slot 20: JYNX / GOLBAT */
    { 0x02AAB7, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 1: GOLBAT / ZUBAT */
    { 0x02AAB9, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 2: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AABD, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 4: ZUBAT / GOLBAT */
    { 0x02AABF, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 5: JYNX / GOLBAT */
    { 0x02AAC5, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 8: GOLBAT / ZUBAT */
    { 0x02AAC7, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 9: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AACB, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 11: JYNX / GOLBAT */
    { 0x02AACD, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 12: JYNX / GOLBAT */
    { 0x02AAD1, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 14: SWINUB / DELIBIRD */
    { 0x02AAD3, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 15: GOLBAT / ZUBAT */
    { 0x02AAD5, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 16: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AAD7, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 17: SWINUB / DELIBIRD */
    { 0x02AAD9, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 18: ZUBAT / GOLBAT */
    { 0x02AADB, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 19: JYNX / GOLBAT */
    { 0x02AADD, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B1F slot 20: JYNX / SNEASEL */
    { 0x02AB15, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 1: GOLBAT / ZUBAT */
    { 0x02AB17, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 2: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AB1B, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 4: ZUBAT / GOLBAT */
    { 0x02AB23, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 8: GOLBAT / ZUBAT */
    { 0x02AB25, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 9: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AB29, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 11: JYNX / GOLBAT */
    { 0x02AB2F, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 14: SWINUB / DELIBIRD */
    { 0x02AB31, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 15: GOLBAT / ZUBAT */
    { 0x02AB33, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 16: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AB35, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 17: SWINUB / DELIBIRD */
    { 0x02AB37, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 18: ZUBAT / GOLBAT */
    { 0x02AB39, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 19: JYNX / SNEASEL */
    { 0x02AB3B, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_BLACKTHORN_SIDE slot 20: JYNX / SNEASEL */
    { 0x02AAE6, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 1: GOLBAT / ZUBAT */
    { 0x02AAE8, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 2: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AAEC, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 4: ZUBAT / GOLBAT */
    { 0x02AAF4, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 8: GOLBAT / ZUBAT */
    { 0x02AAF6, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 9: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AAFA, 2, { 124,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 11: JYNX / GOLBAT */
    { 0x02AB00, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 14: SWINUB / DELIBIRD */
    { 0x02AB02, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 15: GOLBAT / ZUBAT */
    { 0x02AB04, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 16: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AB06, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 17: SWINUB / DELIBIRD */
    { 0x02AB08, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 18: ZUBAT / GOLBAT */
    { 0x02AB0A, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 19: JYNX / SNEASEL */
    { 0x02AB0C, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B2F_MAHOGANY_SIDE slot 20: JYNX / SNEASEL */
    { 0x02AB44, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 1: GOLBAT / ZUBAT */
    { 0x02AB46, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 2: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AB4A, 2, {  41, 124,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 4: ZUBAT / JYNX */
    { 0x02AB52, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 8: GOLBAT / ZUBAT */
    { 0x02AB54, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 9: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AB5E, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 14: SWINUB / DELIBIRD */
    { 0x02AB60, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 15: GOLBAT / ZUBAT */
    { 0x02AB62, 3, {  41, 225,  42 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 16: ZUBAT / DELIBIRD / GOLBAT */
    { 0x02AB64, 2, { 220, 225,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 17: SWINUB / DELIBIRD */
    { 0x02AB66, 2, {  41, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 18: ZUBAT / SNEASEL */
    { 0x02AB68, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 19: JYNX / SNEASEL */
    { 0x02AB6A, 2, { 124, 215,   0 } },  /* JohtoGrassWildMons ICE_PATH_B3F slot 20: JYNX / SNEASEL */
    { 0x02A99B, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 0: CATERPIE / WEEDLE */
    { 0x02A99D, 3, {  11,  14,  13 } },  /* JohtoGrassWildMons ILEX_FOREST slot 1: METAPOD / KAKUNA / WEEDLE */
    { 0x02A99F, 3, {  10,  13,  11 } },  /* JohtoGrassWildMons ILEX_FOREST slot 2: CATERPIE / WEEDLE / METAPOD */
    { 0x02A9A1, 2, {  46,  14,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 3: PARAS / KAKUNA */
    { 0x02A9A3, 2, {  41,  16,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 4: ZUBAT / PIDGEY */
    { 0x02A9A9, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 7: CATERPIE / WEEDLE */
    { 0x02A9AB, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 8: CATERPIE / WEEDLE */
    { 0x02A9AD, 2, {  11,  14,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 9: METAPOD / KAKUNA */
    { 0x02A9AF, 2, {  11,  14,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 10: METAPOD / KAKUNA */
    { 0x02A9B1, 2, {  41,  16,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 11: ZUBAT / PIDGEY */
    { 0x02A9B9, 2, {  43,  48,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 15: ODDISH / VENONAT */
    { 0x02A9BB, 2, {  41,  43,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 16: ZUBAT / ODDISH */
    { 0x02A9BD, 2, {  46,  54,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 17: PARAS / PSYDUCK */
    { 0x02A9BF, 2, {  41, 163,   0 } },  /* JohtoGrassWildMons ILEX_FOREST slot 18: ZUBAT / HOOTHOOT */
    { 0x02A9FB, 2, {  66,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 1: MACHOP / RATTATA */
    { 0x02A9FD, 2, {  74,  66,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 2: GEODUDE / MACHOP */
    { 0x02A9FF, 2, {  19,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 3: RATTATA / RATICATE */
    { 0x02AA01, 2, {  66,  41,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 4: MACHOP / ZUBAT */
    { 0x02AA03, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 5: ZUBAT / GOLBAT */
    { 0x02AA05, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 6: ZUBAT / GOLBAT */
    { 0x02AA09, 2, {  66,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 8: MACHOP / RATTATA */
    { 0x02AA0B, 2, {  74,  66,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 9: GEODUDE / MACHOP */
    { 0x02AA0D, 2, {  19,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 10: RATTATA / RATICATE */
    { 0x02AA0F, 2, {  66,  41,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 11: MACHOP / ZUBAT */
    { 0x02AA11, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 12: ZUBAT / GOLBAT */
    { 0x02AA13, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 13: ZUBAT / GOLBAT */
    { 0x02AA17, 2, {  66,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 15: MACHOP / RATTATA */
    { 0x02AA19, 2, {  74,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 16: GEODUDE / RATICATE */
    { 0x02AA1B, 2, {  19,  41,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 17: RATTATA / ZUBAT */
    { 0x02AA1D, 2, {  66, 183,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 18: MACHOP / MARILL */
    { 0x02AA1F, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 19: ZUBAT / GOLBAT */
    { 0x02AA21, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_INSIDE slot 20: ZUBAT / GOLBAT */
    { 0x02A9CA, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 0: ZUBAT / RATTATA */
    { 0x02A9D0, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 3: RATTATA / GOLBAT */
    { 0x02A9D4, 2, {  19,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 5: RATTATA / RATICATE */
    { 0x02A9D6, 2, { 183,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 6: MARILL / RATICATE */
    { 0x02A9D8, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 7: ZUBAT / RATTATA */
    { 0x02A9DE, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 10: RATTATA / GOLBAT */
    { 0x02A9E2, 2, {  19,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 12: RATTATA / RATICATE */
    { 0x02A9E4, 2, { 183,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 13: MARILL / RATICATE */
    { 0x02A9E6, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 14: ZUBAT / RATTATA */
    { 0x02A9EA, 2, {  66, 183,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 16: MACHOP / MARILL */
    { 0x02A9EC, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 17: RATTATA / GOLBAT */
    { 0x02A9F0, 2, {  19,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 19: RATTATA / RATICATE */
    { 0x02A9F2, 2, { 183,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_1F_OUTSIDE slot 20: MARILL / RATICATE */
    { 0x02AA46, 2, {  67,  74,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_2F_INSIDE slot 15: MACHOKE / GEODUDE */
    { 0x02AA48, 2, {  74,  20,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_2F_INSIDE slot 16: GEODUDE / RATICATE */
    { 0x02AA4A, 2, {  20,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_2F_INSIDE slot 17: RATICATE / GOLBAT */
    { 0x02AA4C, 2, {  66, 183,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_2F_INSIDE slot 18: MACHOP / MARILL */
    { 0x02AA5B, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_B1F slot 2: RATTATA / GOLBAT */
    { 0x02AA69, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_B1F slot 9: RATTATA / GOLBAT */
    { 0x02AA77, 2, {  19,  42,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_B1F slot 16: RATTATA / GOLBAT */
    { 0x02AA79, 2, {  66, 183,   0 } },  /* JohtoGrassWildMons MOUNT_MORTAR_B1F slot 17: MACHOP / MARILL */
    { 0x02A823, 3, {  10,  13,  32 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 0: CATERPIE / WEEDLE / NIDORAN_M */
    { 0x02A825, 3, {  11,  14,  29 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 1: METAPOD / KAKUNA / NIDORAN_F */
    { 0x02A827, 3, {  10,  13, 165 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 2: CATERPIE / WEEDLE / LEDYBA */
    { 0x02A82B, 2, {  16,  10,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 4: PIDGEY / CATERPIE */
    { 0x02A82D, 2, {  16,  13,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 5: PIDGEY / WEEDLE */
    { 0x02A82F, 2, {  16,  13,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 6: PIDGEY / WEEDLE */
    { 0x02A831, 3, {  10,  13,  29 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 7: CATERPIE / WEEDLE / NIDORAN_F */
    { 0x02A833, 3, {  11,  14,  32 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 8: METAPOD / KAKUNA / NIDORAN_M */
    { 0x02A839, 2, { 191,  10,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 11: SUNKERN / CATERPIE */
    { 0x02A83B, 2, {  16,  13,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 12: PIDGEY / WEEDLE */
    { 0x02A83D, 2, {  16,  13,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 13: PIDGEY / WEEDLE */
    { 0x02A83F, 2, { 163,  54,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 14: HOOTHOOT / PSYDUCK */
    { 0x02A843, 2, { 163, 167,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 16: HOOTHOOT / SPINARAK */
    { 0x02A847, 2, { 163,  48,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 18: HOOTHOOT / VENONAT */
    { 0x02A849, 2, { 163,  48,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 19: HOOTHOOT / VENONAT */
    { 0x02A84B, 2, { 163,  48,   0 } },  /* JohtoGrassWildMons NATIONAL_PARK slot 20: HOOTHOOT / VENONAT */
    { 0x02AE0D, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_29 slot 5: PIDGEY / HOPPIP */
    { 0x02AE0F, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_29 slot 6: PIDGEY / HOPPIP */
    { 0x02AE1B, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_29 slot 12: PIDGEY / HOPPIP */
    { 0x02AE1D, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_29 slot 13: PIDGEY / HOPPIP */
    { 0x02AE21, 2, { 163,  19,   0 } },  /* JohtoGrassWildMons ROUTE_29 slot 15: HOOTHOOT / RATTATA */
    { 0x02AE32, 2, {  16, 165,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 0: PIDGEY / LEDYBA */
    { 0x02AE34, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 1: CATERPIE / WEEDLE */
    { 0x02AE36, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 2: CATERPIE / WEEDLE */
    { 0x02AE38, 3, {  11,  14,  16 } },  /* JohtoGrassWildMons ROUTE_30 slot 3: METAPOD / KAKUNA / PIDGEY */
    { 0x02AE3A, 2, {  16,  13,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 4: PIDGEY / WEEDLE */
    { 0x02AE3C, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 5: PIDGEY / HOPPIP */
    { 0x02AE3E, 2, {  16, 187,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 6: PIDGEY / HOPPIP */
    { 0x02AE42, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 8: CATERPIE / WEEDLE */
    { 0x02AE44, 2, {  16,  10,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 9: PIDGEY / CATERPIE */
    { 0x02AE46, 3, {  11,  14,  16 } },  /* JohtoGrassWildMons ROUTE_30 slot 10: METAPOD / KAKUNA / PIDGEY */
    { 0x02AE48, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 11: CATERPIE / WEEDLE */
    { 0x02AE4A, 3, {  11,  14, 187 } },  /* JohtoGrassWildMons ROUTE_30 slot 12: METAPOD / KAKUNA / HOPPIP */
    { 0x02AE4C, 3, {  11,  14, 187 } },  /* JohtoGrassWildMons ROUTE_30 slot 13: METAPOD / KAKUNA / HOPPIP */
    { 0x02AE4E, 2, { 167, 163,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 14: SPINARAK / HOOTHOOT */
    { 0x02AE50, 2, {  19, 163,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 15: RATTATA / HOOTHOOT */
    { 0x02AE52, 2, { 163,  60,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 16: HOOTHOOT / POLIWAG */
    { 0x02AE54, 2, {  19, 163,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 17: RATTATA / HOOTHOOT */
    { 0x02AE56, 2, { 163,  41,   0 } },  /* JohtoGrassWildMons ROUTE_30 slot 18: HOOTHOOT / ZUBAT */
    { 0x02AE61, 2, {  16, 165,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 0: PIDGEY / LEDYBA */
    { 0x02AE63, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 1: CATERPIE / WEEDLE */
    { 0x02AE67, 3, {  11,  14,  16 } },  /* JohtoGrassWildMons ROUTE_31 slot 3: METAPOD / KAKUNA / PIDGEY */
    { 0x02AE69, 3, {  10,  16,  13 } },  /* JohtoGrassWildMons ROUTE_31 slot 4: CATERPIE / PIDGEY / WEEDLE */
    { 0x02AE6B, 3, {  11,  16, 187 } },  /* JohtoGrassWildMons ROUTE_31 slot 5: METAPOD / PIDGEY / HOPPIP */
    { 0x02AE6D, 3, {  11,  16, 187 } },  /* JohtoGrassWildMons ROUTE_31 slot 6: METAPOD / PIDGEY / HOPPIP */
    { 0x02AE71, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 8: CATERPIE / WEEDLE */
    { 0x02AE75, 3, {  11,  14,  16 } },  /* JohtoGrassWildMons ROUTE_31 slot 10: METAPOD / KAKUNA / PIDGEY */
    { 0x02AE77, 2, {  10,  13,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 11: CATERPIE / WEEDLE */
    { 0x02AE79, 3, {  11,  14, 187 } },  /* JohtoGrassWildMons ROUTE_31 slot 12: METAPOD / KAKUNA / HOPPIP */
    { 0x02AE7B, 3, {  11,  14, 187 } },  /* JohtoGrassWildMons ROUTE_31 slot 13: METAPOD / KAKUNA / HOPPIP */
    { 0x02AE7D, 2, { 167, 163,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 14: SPINARAK / HOOTHOOT */
    { 0x02AE7F, 2, {  19,  60,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 15: RATTATA / POLIWAG */
    { 0x02AE83, 2, {  19, 163,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 17: RATTATA / HOOTHOOT */
    { 0x02AE85, 2, { 163,  41,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 18: HOOTHOOT / ZUBAT */
    { 0x02AE87, 2, { 163,  92,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 19: HOOTHOOT / GASTLY */
    { 0x02AE89, 2, { 163,  92,   0 } },  /* JohtoGrassWildMons ROUTE_31 slot 20: HOOTHOOT / GASTLY */
    { 0x02AE90, 2, {  69,  23,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 0: BELLSPROUT / EKANS */
    { 0x02AE92, 2, {  19,  23,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 1: RATTATA / EKANS */
    { 0x02AE94, 2, { 179,  69,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 2: MAREEP / BELLSPROUT */
    { 0x02AE98, 2, {  19,  16,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 4: RATTATA / PIDGEY */
    { 0x02AE9A, 2, { 194, 187,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 5: WOOPER / HOPPIP */
    { 0x02AE9C, 2, {  41, 187,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 6: ZUBAT / HOPPIP */
    { 0x02AE9E, 2, {  69,  23,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 7: BELLSPROUT / EKANS */
    { 0x02AEA0, 2, {  19,  23,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 8: RATTATA / EKANS */
    { 0x02AEA2, 2, { 179,  69,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 9: MAREEP / BELLSPROUT */
    { 0x02AEA6, 2, {  19,  16,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 11: RATTATA / PIDGEY */
    { 0x02AEA8, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 12: RATTATA / HOPPIP */
    { 0x02AEAA, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 13: RATTATA / HOPPIP */
    { 0x02AEAE, 2, {  19,  23,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 15: RATTATA / EKANS */
    { 0x02AEB2, 2, { 179,  41,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 17: MAREEP / ZUBAT */
    { 0x02AEB4, 2, { 194, 163,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 18: WOOPER / HOOTHOOT */
    { 0x02AEB6, 2, {  41,  92,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 19: ZUBAT / GASTLY */
    { 0x02AEB8, 2, {  41,  92,   0 } },  /* JohtoGrassWildMons ROUTE_32 slot 20: ZUBAT / GASTLY */
    { 0x02AEBF, 2, { 187,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 0: HOPPIP / RATTATA */
    { 0x02AEC1, 3, {  19,  23,  21 } },  /* JohtoGrassWildMons ROUTE_33 slot 1: RATTATA / EKANS / SPEAROW */
    { 0x02AEC3, 2, {  21,  74,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 2: SPEAROW / GEODUDE */
    { 0x02AEC5, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 3: RATTATA / HOPPIP */
    { 0x02AEC7, 2, { 187,  23,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 4: HOPPIP / EKANS */
    { 0x02AEC9, 2, {  41, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 5: ZUBAT / HOPPIP */
    { 0x02AECB, 2, {  41, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 6: ZUBAT / HOPPIP */
    { 0x02AECD, 2, { 187,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 7: HOPPIP / RATTATA */
    { 0x02AECF, 3, {  19,  23,  21 } },  /* JohtoGrassWildMons ROUTE_33 slot 8: RATTATA / EKANS / SPEAROW */
    { 0x02AED1, 2, {  21,  74,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 9: SPEAROW / GEODUDE */
    { 0x02AED3, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 10: RATTATA / HOPPIP */
    { 0x02AED5, 2, { 187,  23,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 11: HOPPIP / EKANS */
    { 0x02AED7, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 12: RATTATA / HOPPIP */
    { 0x02AED9, 2, {  19, 187,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 13: RATTATA / HOPPIP */
    { 0x02AEDB, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 14: ZUBAT / RATTATA */
    { 0x02AEDD, 3, {  19,  23,  41 } },  /* JohtoGrassWildMons ROUTE_33 slot 15: RATTATA / EKANS / ZUBAT */
    { 0x02AEDF, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 16: RATTATA / GEODUDE */
    { 0x02AEE1, 2, {  19,  41,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 17: RATTATA / ZUBAT */
    { 0x02AEE3, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 18: ZUBAT / RATTATA */
    { 0x02AEE5, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 19: ZUBAT / RATTATA */
    { 0x02AEE7, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons ROUTE_33 slot 20: ZUBAT / RATTATA */
    { 0x02AEEE, 2, {  96, 209,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 0: DROWZEE / SNUBBULL */
    { 0x02AEF2, 2, {  96,  16,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 2: DROWZEE / PIDGEY */
    { 0x02AEF6, 2, {  19,  39,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 4: RATTATA / JIGGLYPUFF */
    { 0x02AEFC, 2, {  96, 209,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 7: DROWZEE / SNUBBULL */
    { 0x02AF00, 2, {  96,  16,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 9: DROWZEE / PIDGEY */
    { 0x02AF04, 2, {  19,  39,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 11: RATTATA / JIGGLYPUFF */
    { 0x02AF0E, 2, {  96, 163,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 16: DROWZEE / HOOTHOOT */
    { 0x02AF12, 2, {  19,  39,   0 } },  /* JohtoGrassWildMons ROUTE_34 slot 18: RATTATA / JIGGLYPUFF */
    { 0x02AF1D, 3, {  32,  29, 209 } },  /* JohtoGrassWildMons ROUTE_35 slot 0: NIDORAN_M / NIDORAN_F / SNUBBULL */
    { 0x02AF1F, 3, {  29,  32,  16 } },  /* JohtoGrassWildMons ROUTE_35 slot 1: NIDORAN_F / NIDORAN_M / PIDGEY */
    { 0x02AF21, 2, {  96,  58,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 2: DROWZEE / GROWLITHE */
    { 0x02AF25, 2, {  16,  39,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 4: PIDGEY / JIGGLYPUFF */
    { 0x02AF2B, 3, {  32,  29, 209 } },  /* JohtoGrassWildMons ROUTE_35 slot 7: NIDORAN_M / NIDORAN_F / SNUBBULL */
    { 0x02AF2D, 3, {  29,  32,  16 } },  /* JohtoGrassWildMons ROUTE_35 slot 8: NIDORAN_F / NIDORAN_M / PIDGEY */
    { 0x02AF2F, 2, {  96,  58,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 9: DROWZEE / GROWLITHE */
    { 0x02AF33, 2, {  16,  39,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 11: PIDGEY / JIGGLYPUFF */
    { 0x02AF39, 3, {  32,  29,  96 } },  /* JohtoGrassWildMons ROUTE_35 slot 14: NIDORAN_M / NIDORAN_F / DROWZEE */
    { 0x02AF3B, 3, {  29,  32, 163 } },  /* JohtoGrassWildMons ROUTE_35 slot 15: NIDORAN_F / NIDORAN_M / HOOTHOOT */
    { 0x02AF3D, 2, {  96,  54,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 16: DROWZEE / PSYDUCK */
    { 0x02AF41, 2, { 163,  39,   0 } },  /* JohtoGrassWildMons ROUTE_35 slot 18: HOOTHOOT / JIGGLYPUFF */
    { 0x02AF4C, 3, {  32,  29, 165 } },  /* JohtoGrassWildMons ROUTE_36 slot 0: NIDORAN_M / NIDORAN_F / LEDYBA */
    { 0x02AF4E, 3, {  29,  32,  16 } },  /* JohtoGrassWildMons ROUTE_36 slot 1: NIDORAN_F / NIDORAN_M / PIDGEY */
    { 0x02AF50, 2, {  16,  69,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 2: PIDGEY / BELLSPROUT */
    { 0x02AF52, 2, {  58,  37,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 3: GROWLITHE / VULPIX */
    { 0x02AF54, 2, { 234,  16,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 4: STANTLER / PIDGEY */
    { 0x02AF5A, 3, {  32,  29,  16 } },  /* JohtoGrassWildMons ROUTE_36 slot 7: NIDORAN_M / NIDORAN_F / PIDGEY */
    { 0x02AF5C, 3, {  29,  32,  16 } },  /* JohtoGrassWildMons ROUTE_36 slot 8: NIDORAN_F / NIDORAN_M / PIDGEY */
    { 0x02AF5E, 2, {  16,  69,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 9: PIDGEY / BELLSPROUT */
    { 0x02AF60, 2, {  58,  37,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 10: GROWLITHE / VULPIX */
    { 0x02AF62, 2, { 234,  16,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 11: STANTLER / PIDGEY */
    { 0x02AF64, 3, {  58,  37,  16 } },  /* JohtoGrassWildMons ROUTE_36 slot 12: GROWLITHE / VULPIX / PIDGEY */
    { 0x02AF66, 3, {  58,  37,  16 } },  /* JohtoGrassWildMons ROUTE_36 slot 13: GROWLITHE / VULPIX / PIDGEY */
    { 0x02AF68, 3, {  32,  29, 167 } },  /* JohtoGrassWildMons ROUTE_36 slot 14: NIDORAN_M / NIDORAN_F / SPINARAK */
    { 0x02AF6A, 3, {  29,  32, 163 } },  /* JohtoGrassWildMons ROUTE_36 slot 15: NIDORAN_F / NIDORAN_M / HOOTHOOT */
    { 0x02AF6C, 2, { 163,  69,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 16: HOOTHOOT / BELLSPROUT */
    { 0x02AF6E, 3, {  58,  37, 163 } },  /* JohtoGrassWildMons ROUTE_36 slot 17: GROWLITHE / VULPIX / HOOTHOOT */
    { 0x02AF70, 2, { 234, 163,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 18: STANTLER / HOOTHOOT */
    { 0x02AF72, 2, { 163,  92,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 19: HOOTHOOT / GASTLY */
    { 0x02AF74, 2, { 163,  92,   0 } },  /* JohtoGrassWildMons ROUTE_36 slot 20: HOOTHOOT / GASTLY */
    { 0x02AF7B, 2, {  16, 165,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 0: PIDGEY / LEDYBA */
    { 0x02AF7D, 2, { 234,  58,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 1: STANTLER / GROWLITHE */
    { 0x02AF81, 2, {  58,  37,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 3: GROWLITHE / VULPIX */
    { 0x02AF83, 3, {  16, 165,  17 } },  /* JohtoGrassWildMons ROUTE_37 slot 4: PIDGEY / LEDYBA / PIDGEOTTO */
    { 0x02AF85, 3, {  16, 165, 166 } },  /* JohtoGrassWildMons ROUTE_37 slot 5: PIDGEY / LEDYBA / LEDIAN */
    { 0x02AF87, 3, {  16, 165, 166 } },  /* JohtoGrassWildMons ROUTE_37 slot 6: PIDGEY / LEDYBA / LEDIAN */
    { 0x02AF8B, 2, { 234,  58,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 8: STANTLER / GROWLITHE */
    { 0x02AF8F, 2, {  58,  37,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 10: GROWLITHE / VULPIX */
    { 0x02AF93, 3, {  58,  37,  16 } },  /* JohtoGrassWildMons ROUTE_37 slot 12: GROWLITHE / VULPIX / PIDGEY */
    { 0x02AF95, 3, {  58,  37,  16 } },  /* JohtoGrassWildMons ROUTE_37 slot 13: GROWLITHE / VULPIX / PIDGEY */
    { 0x02AF97, 2, { 167, 163,   0 } },  /* JohtoGrassWildMons ROUTE_37 slot 14: SPINARAK / HOOTHOOT */
    { 0x02AF9D, 3, {  58,  37, 234 } },  /* JohtoGrassWildMons ROUTE_37 slot 17: GROWLITHE / VULPIX / STANTLER */
    { 0x02AF9F, 3, { 167, 163, 164 } },  /* JohtoGrassWildMons ROUTE_37 slot 18: SPINARAK / HOOTHOOT / NOCTOWL */
    { 0x02AFA1, 3, { 167, 163, 168 } },  /* JohtoGrassWildMons ROUTE_37 slot 19: SPINARAK / HOOTHOOT / ARIADOS */
    { 0x02AFA3, 3, { 167, 163, 168 } },  /* JohtoGrassWildMons ROUTE_37 slot 20: SPINARAK / HOOTHOOT / ARIADOS */
    { 0x02AFAA, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 0: RATTATA / MEOWTH */
    { 0x02AFB0, 2, {  83,  17,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 3: FARFETCH_D / PIDGEOTTO */
    { 0x02AFB2, 2, { 241, 128,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 4: MILTANK / TAUROS */
    { 0x02AFB4, 2, { 128, 241,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 5: TAUROS / MILTANK */
    { 0x02AFB6, 2, { 209, 241,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 6: SNUBBULL / MILTANK */
    { 0x02AFB8, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 7: RATTATA / MEOWTH */
    { 0x02AFBE, 2, {  83,  17,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 10: FARFETCH_D / PIDGEOTTO */
    { 0x02AFC0, 2, { 241, 128,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 11: MILTANK / TAUROS */
    { 0x02AFC2, 2, { 128, 241,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 12: TAUROS / MILTANK */
    { 0x02AFC4, 2, { 209, 241,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 13: SNUBBULL / MILTANK */
    { 0x02AFC6, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 14: RATTATA / MEOWTH */
    { 0x02AFCC, 3, {  19,  52, 164 } },  /* JohtoGrassWildMons ROUTE_38 slot 17: RATTATA / MEOWTH / NOCTOWL */
    { 0x02AFCE, 2, { 241,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 18: MILTANK / MEOWTH */
    { 0x02AFD0, 2, { 128,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 19: TAUROS / MEOWTH */
    { 0x02AFD2, 2, { 209,  52,   0 } },  /* JohtoGrassWildMons ROUTE_38 slot 20: SNUBBULL / MEOWTH */
    { 0x02AFD9, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 0: RATTATA / MEOWTH */
    { 0x02AFDF, 2, {  83,  17,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 3: FARFETCH_D / PIDGEOTTO */
    { 0x02AFE7, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 7: RATTATA / MEOWTH */
    { 0x02AFED, 2, {  83,  17,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 10: FARFETCH_D / PIDGEOTTO */
    { 0x02AFF5, 2, {  19,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 14: RATTATA / MEOWTH */
    { 0x02AFFB, 3, {  19,  52, 164 } },  /* JohtoGrassWildMons ROUTE_39 slot 17: RATTATA / MEOWTH / NOCTOWL */
    { 0x02AFFD, 2, { 241,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 18: MILTANK / MEOWTH */
    { 0x02AFFF, 2, { 128,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 19: TAUROS / MEOWTH */
    { 0x02B001, 2, { 128,  52,   0 } },  /* JohtoGrassWildMons ROUTE_39 slot 20: TAUROS / MEOWTH */
    { 0x02B008, 3, {  56, 179,  23 } },  /* JohtoGrassWildMons ROUTE_42 slot 0: MANKEY / MAREEP / EKANS */
    { 0x02B00A, 2, { 179,  21,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 1: MAREEP / SPEAROW */
    { 0x02B00C, 3, {  21, 179,  19 } },  /* JohtoGrassWildMons ROUTE_42 slot 2: SPEAROW / MAREEP / RATTATA */
    { 0x02B00E, 2, {  21,  20,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 3: SPEAROW / RATICATE */
    { 0x02B010, 2, { 180,  24,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 4: FLAAFFY / ARBOK */
    { 0x02B012, 2, { 180,  22,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 5: FLAAFFY / FEAROW */
    { 0x02B014, 2, { 180,  22,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 6: FLAAFFY / FEAROW */
    { 0x02B016, 3, {  56, 179,  23 } },  /* JohtoGrassWildMons ROUTE_42 slot 7: MANKEY / MAREEP / EKANS */
    { 0x02B018, 2, { 179,  21,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 8: MAREEP / SPEAROW */
    { 0x02B01A, 3, {  21, 179,  19 } },  /* JohtoGrassWildMons ROUTE_42 slot 9: SPEAROW / MAREEP / RATTATA */
    { 0x02B01C, 2, {  21,  20,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 10: SPEAROW / RATICATE */
    { 0x02B01E, 2, { 180,  24,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 11: FLAAFFY / ARBOK */
    { 0x02B020, 2, { 180,  22,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 12: FLAAFFY / FEAROW */
    { 0x02B022, 2, { 180,  22,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 13: FLAAFFY / FEAROW */
    { 0x02B024, 3, {  56, 179,  19 } },  /* JohtoGrassWildMons ROUTE_42 slot 14: MANKEY / MAREEP / RATTATA */
    { 0x02B026, 2, { 179,  41,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 15: MAREEP / ZUBAT */
    { 0x02B028, 3, {  41, 179,  20 } },  /* JohtoGrassWildMons ROUTE_42 slot 16: ZUBAT / MAREEP / RATICATE */
    { 0x02B02A, 2, {  41,  42,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 17: ZUBAT / GOLBAT */
    { 0x02B02C, 2, { 180, 183,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 18: FLAAFFY / MARILL */
    { 0x02B02E, 2, { 180,  42,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 19: FLAAFFY / GOLBAT */
    { 0x02B030, 2, { 180,  42,   0 } },  /* JohtoGrassWildMons ROUTE_42 slot 20: FLAAFFY / GOLBAT */
    { 0x02B037, 2, { 180, 161,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 0: FLAAFFY / SENTRET */
    { 0x02B039, 2, { 203,  17,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 1: GIRAFARIG / PIDGEOTTO */
    { 0x02B03B, 2, {  17,  83,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 2: PIDGEOTTO / FARFETCH_D */
    { 0x02B03D, 2, { 179, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 3: MAREEP / FURRET */
    { 0x02B03F, 2, {  48,  20,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 4: VENONAT / RATICATE */
    { 0x02B041, 2, {  17, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 5: PIDGEOTTO / FURRET */
    { 0x02B043, 2, {  17, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 6: PIDGEOTTO / FURRET */
    { 0x02B045, 2, { 180, 161,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 7: FLAAFFY / SENTRET */
    { 0x02B047, 2, { 203,  17,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 8: GIRAFARIG / PIDGEOTTO */
    { 0x02B049, 2, {  17,  83,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 9: PIDGEOTTO / FARFETCH_D */
    { 0x02B04B, 2, { 179, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 10: MAREEP / FURRET */
    { 0x02B04D, 2, { 180,  20,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 11: FLAAFFY / RATICATE */
    { 0x02B04F, 2, { 180, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 12: FLAAFFY / FURRET */
    { 0x02B051, 2, { 180, 162,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 13: FLAAFFY / FURRET */
    { 0x02B053, 2, { 180,  48,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 14: FLAAFFY / VENONAT */
    { 0x02B055, 2, { 203, 164,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 15: GIRAFARIG / NOCTOWL */
    { 0x02B057, 2, { 164,  20,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 16: NOCTOWL / RATICATE */
    { 0x02B05B, 2, { 179,  20,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 18: MAREEP / RATICATE */
    { 0x02B05D, 2, {  48,  49,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 19: VENONAT / VENOMOTH */
    { 0x02B05F, 2, {  48,  49,   0 } },  /* JohtoGrassWildMons ROUTE_43 slot 20: VENONAT / VENOMOTH */
    { 0x02B068, 2, {  70, 108,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 1: WEEPINBELL / LICKITUNG */
    { 0x02B06C, 2, { 108,  70,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 3: LICKITUNG / WEEPINBELL */
    { 0x02B06E, 2, {  70, 108,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 4: WEEPINBELL / LICKITUNG */
    { 0x02B076, 2, {  70, 108,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 8: WEEPINBELL / LICKITUNG */
    { 0x02B07A, 2, { 108,  70,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 10: LICKITUNG / WEEPINBELL */
    { 0x02B07C, 2, {  70, 108,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 11: WEEPINBELL / LICKITUNG */
    { 0x02B084, 2, {  70,  60,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 15: WEEPINBELL / POLIWAG */
    { 0x02B088, 2, { 108,  70,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 17: LICKITUNG / WEEPINBELL */
    { 0x02B08A, 2, {  70,  61,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 18: WEEPINBELL / POLIWHIRL */
    { 0x02B08C, 2, { 108,  61,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 19: LICKITUNG / POLIWHIRL */
    { 0x02B08E, 2, { 108,  61,   0 } },  /* JohtoGrassWildMons ROUTE_44 slot 20: LICKITUNG / POLIWHIRL */
    { 0x02B099, 2, { 207,  75,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 2: GLIGAR / GRAVELER */
    { 0x02B09B, 3, { 216, 231, 232 } },  /* JohtoGrassWildMons ROUTE_45 slot 3: TEDDIURSA / PHANPY / DONPHAN */
    { 0x02B09D, 2, {  75, 231,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 4: GRAVELER / PHANPY */
    { 0x02B09F, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 5: GRAVELER / SKARMORY */
    { 0x02B0A1, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 6: GRAVELER / SKARMORY */
    { 0x02B0A7, 2, { 207,  75,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 9: GLIGAR / GRAVELER */
    { 0x02B0A9, 3, { 216, 231, 232 } },  /* JohtoGrassWildMons ROUTE_45 slot 10: TEDDIURSA / PHANPY / DONPHAN */
    { 0x02B0AB, 2, {  75, 232,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 11: GRAVELER / DONPHAN */
    { 0x02B0AD, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 12: GRAVELER / SKARMORY */
    { 0x02B0AF, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 13: GRAVELER / SKARMORY */
    { 0x02B0B5, 2, { 207,  75,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 16: GLIGAR / GRAVELER */
    { 0x02B0B7, 3, { 216, 231,  75 } },  /* JohtoGrassWildMons ROUTE_45 slot 17: TEDDIURSA / PHANPY / GRAVELER */
    { 0x02B0BB, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 19: GRAVELER / SKARMORY */
    { 0x02B0BD, 2, {  75, 227,   0 } },  /* JohtoGrassWildMons ROUTE_45 slot 20: GRAVELER / SKARMORY */
    { 0x02B0C8, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 2: RATTATA / GEODUDE */
    { 0x02B0CA, 2, {  74,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 3: GEODUDE / RATTATA */
    { 0x02B0CC, 2, {  21, 231,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 4: SPEAROW / PHANPY */
    { 0x02B0CE, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 5: JIGGLYPUFF / RATTATA */
    { 0x02B0D0, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 6: JIGGLYPUFF / RATTATA */
    { 0x02B0D6, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 9: RATTATA / GEODUDE */
    { 0x02B0D8, 2, {  74,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 10: GEODUDE / RATTATA */
    { 0x02B0DA, 2, {  21,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 11: SPEAROW / RATTATA */
    { 0x02B0DC, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 12: JIGGLYPUFF / RATTATA */
    { 0x02B0DE, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 13: JIGGLYPUFF / RATTATA */
    { 0x02B0E4, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 16: RATTATA / GEODUDE */
    { 0x02B0E6, 2, {  74,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 17: GEODUDE / RATTATA */
    { 0x02B0E8, 2, {  74,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 18: GEODUDE / RATTATA */
    { 0x02B0EA, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 19: JIGGLYPUFF / RATTATA */
    { 0x02B0EC, 2, {  39,  19,   0 } },  /* JohtoGrassWildMons ROUTE_46 slot 20: JIGGLYPUFF / RATTATA */
    { 0x02A876, 2, { 235, 194,   0 } },  /* JohtoGrassWildMons RUINS_OF_ALPH_OUTSIDE slot 18: SMEARGLE / WOOPER */
    { 0x02A878, 2, { 235, 195,   0 } },  /* JohtoGrassWildMons RUINS_OF_ALPH_OUTSIDE slot 19: SMEARGLE / QUAGSIRE */
    { 0x02A87A, 2, { 235, 195,   0 } },  /* JohtoGrassWildMons RUINS_OF_ALPH_OUTSIDE slot 20: SMEARGLE / QUAGSIRE */
    { 0x02AD76, 2, { 195,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 0: QUAGSIRE / GOLBAT */
    { 0x02AD78, 2, {  55,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 1: GOLDUCK / GOLBAT */
    { 0x02AD7A, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 2: URSARING / DONPHAN / GOLBAT */
    { 0x02AD7C, 2, { 195,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 3: QUAGSIRE / PARASECT */
    { 0x02AD7E, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 4: GOLBAT / PARASECT */
    { 0x02AD80, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 5: LARVITAR / PARASECT */
    { 0x02AD82, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 6: LARVITAR / PARASECT */
    { 0x02AD84, 2, { 195,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 7: QUAGSIRE / GOLBAT */
    { 0x02AD86, 2, {  55,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 8: GOLDUCK / GOLBAT */
    { 0x02AD88, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 9: URSARING / DONPHAN / GOLBAT */
    { 0x02AD8A, 2, { 195,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 10: QUAGSIRE / PARASECT */
    { 0x02AD8C, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 11: GOLBAT / PARASECT */
    { 0x02AD8E, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 12: LARVITAR / PARASECT */
    { 0x02AD90, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 13: LARVITAR / PARASECT */
    { 0x02AD94, 2, {  55,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 15: GOLDUCK / GOLBAT */
    { 0x02AD96, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 16: URSARING / DONPHAN / GOLBAT */
    { 0x02AD98, 2, { 195,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 17: QUAGSIRE / PARASECT */
    { 0x02AD9A, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 18: GOLBAT / PARASECT */
    { 0x02AD9C, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 19: LARVITAR / PARASECT */
    { 0x02AD9E, 2, { 246,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ITEM_ROOMS slot 20: LARVITAR / PARASECT */
    { 0x02B0F7, 3, { 217, 232,  24 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 2: URSARING / DONPHAN / ARBOK */
    { 0x02B105, 3, { 217, 232,  24 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 9: URSARING / DONPHAN / ARBOK */
    { 0x02B111, 2, {  77,  61,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 15: PONYTA / POLIWHIRL */
    { 0x02B113, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 16: URSARING / DONPHAN / GOLBAT */
    { 0x02B115, 2, {  78,  61,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 17: RAPIDASH / POLIWHIRL */
    { 0x02B117, 2, { 215,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 18: SNEASEL / GOLBAT */
    { 0x02B119, 2, { 215,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 19: SNEASEL / GOLBAT */
    { 0x02B11B, 2, { 215,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_OUTSIDE slot 20: SNEASEL / GOLBAT */
    { 0x02ACE9, 2, {  95,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 0: ONIX / GRAVELER */
    { 0x02ACEB, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 1: URSARING / DONPHAN */
    { 0x02ACED, 2, {  75,  95,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 2: GRAVELER / ONIX */
    { 0x02ACEF, 2, {  75, 126,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 3: GRAVELER / MAGMAR */
    { 0x02ACF7, 2, {  95,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 7: ONIX / GRAVELER */
    { 0x02ACF9, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 8: URSARING / DONPHAN */
    { 0x02ACFB, 2, {  75,  95,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 9: GRAVELER / ONIX */
    { 0x02ACFD, 2, {  75, 126,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 10: GRAVELER / MAGMAR */
    { 0x02AD05, 2, {  95,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 14: ONIX / GRAVELER */
    { 0x02AD07, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 15: URSARING / DONPHAN / GOLBAT */
    { 0x02AD09, 2, {  75,  95,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 16: GRAVELER / ONIX */
    { 0x02AD0B, 2, {  75,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 17: GRAVELER / GOLBAT */
    { 0x02AD0D, 2, {  42,  55,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 18: GOLBAT / GOLDUCK */
    { 0x02AD0F, 2, { 246,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 19: LARVITAR / GOLBAT */
    { 0x02AD11, 2, { 246,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_1 slot 20: LARVITAR / GOLBAT */
    { 0x02AD18, 2, { 195,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 0: QUAGSIRE / GOLBAT */
    { 0x02AD1A, 2, {  55,  67,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 1: GOLDUCK / MACHOKE */
    { 0x02AD1C, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 2: URSARING / DONPHAN */
    { 0x02AD1E, 2, { 195,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 3: QUAGSIRE / PARASECT */
    { 0x02AD20, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 4: GOLBAT / PARASECT */
    { 0x02AD26, 2, { 195,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 7: QUAGSIRE / GOLBAT */
    { 0x02AD28, 2, {  55,  67,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 8: GOLDUCK / MACHOKE */
    { 0x02AD2A, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 9: URSARING / DONPHAN */
    { 0x02AD2C, 2, { 195,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 10: QUAGSIRE / PARASECT */
    { 0x02AD2E, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 11: GOLBAT / PARASECT */
    { 0x02AD34, 2, { 195,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 14: QUAGSIRE / GOLBAT */
    { 0x02AD38, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 16: URSARING / DONPHAN / GOLBAT */
    { 0x02AD3A, 2, { 200,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 17: MISDREAVUS / PARASECT */
    { 0x02AD3C, 2, {  42,  47,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 18: GOLBAT / PARASECT */
    { 0x02AD3E, 2, { 246, 200,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 19: LARVITAR / MISDREAVUS */
    { 0x02AD40, 2, { 246, 200,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_2 slot 20: LARVITAR / MISDREAVUS */
    { 0x02AD4B, 2, {  42,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 2: GOLBAT / GRAVELER */
    { 0x02AD4D, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 3: URSARING / DONPHAN */
    { 0x02AD4F, 2, {  55, 246,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 4: GOLDUCK / LARVITAR */
    { 0x02AD53, 2, { 246, 247,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 6: LARVITAR / PUPITAR */
    { 0x02AD59, 2, {  42,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 9: GOLBAT / GRAVELER */
    { 0x02AD5B, 2, { 217, 232,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 10: URSARING / DONPHAN */
    { 0x02AD5D, 2, {  55, 246,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 11: GOLDUCK / LARVITAR */
    { 0x02AD61, 2, { 246, 247,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 13: LARVITAR / PUPITAR */
    { 0x02AD67, 2, {  42,  75,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 16: GOLBAT / GRAVELER */
    { 0x02AD69, 3, { 217, 232,  42 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 17: URSARING / DONPHAN / GOLBAT */
    { 0x02AD6D, 2, { 246,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 19: LARVITAR / GOLBAT */
    { 0x02AD6F, 2, { 246,  42,   0 } },  /* JohtoGrassWildMons SILVER_CAVE_ROOM_3 slot 20: LARVITAR / GOLBAT */
    { 0x02A8B2, 2, {  27,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_1F slot 1: SANDSHREW / RATTATA */
    { 0x02A8C0, 2, {  27,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_1F slot 8: SANDSHREW / RATTATA */
    { 0x02A8CE, 2, {  27,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_1F slot 15: SANDSHREW / RATTATA */
    { 0x02A8D0, 2, {  41, 194,   0 } },  /* JohtoGrassWildMons UNION_CAVE_1F slot 16: ZUBAT / WOOPER */
    { 0x02A8E1, 3, {  27,  19,  41 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 1: SANDSHREW / RATTATA / ZUBAT */
    { 0x02A8E7, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 4: ZUBAT / RATTATA */
    { 0x02A8EF, 3, {  27,  19,  41 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 8: SANDSHREW / RATTATA / ZUBAT */
    { 0x02A8F5, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 11: ZUBAT / RATTATA */
    { 0x02A8FD, 3, {  27,  19,  41 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 15: SANDSHREW / RATTATA / ZUBAT */
    { 0x02A8FF, 2, {  41, 194,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 16: ZUBAT / WOOPER */
    { 0x02A903, 2, {  41,  19,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B1F slot 18: ZUBAT / RATTATA */
    { 0x02A910, 2, {  20,  42,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 1: RATICATE / GOLBAT */
    { 0x02A912, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 2: GOLBAT / ZUBAT */
    { 0x02A914, 2, {  74,  20,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 3: GEODUDE / RATICATE */
    { 0x02A916, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 4: RATTATA / GEODUDE */
    { 0x02A91E, 2, {  20,  42,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 8: RATICATE / GOLBAT */
    { 0x02A920, 2, {  42,  41,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 9: GOLBAT / ZUBAT */
    { 0x02A922, 2, {  74,  20,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 10: GEODUDE / RATICATE */
    { 0x02A924, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 11: RATTATA / GEODUDE */
    { 0x02A92C, 2, {  20,  42,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 15: RATICATE / GOLBAT */
    { 0x02A92E, 2, {  42, 195,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 16: GOLBAT / QUAGSIRE */
    { 0x02A930, 2, {  74,  20,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 17: GEODUDE / RATICATE */
    { 0x02A932, 2, {  19,  74,   0 } },  /* JohtoGrassWildMons UNION_CAVE_B2F slot 18: RATTATA / GEODUDE */
    { 0x02AC60, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 2: KRABBY / SEEL */
    { 0x02AC62, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 3: SEEL / KRABBY */
    { 0x02AC6E, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 9: KRABBY / SEEL */
    { 0x02AC70, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 10: SEEL / KRABBY */
    { 0x02AC7E, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 17: SEEL / KRABBY */
    { 0x02AC82, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 19: SEEL / GOLBAT */
    { 0x02AC84, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B1F slot 20: SEEL / GOLBAT */
    { 0x02AC8F, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 2: KRABBY / SEEL */
    { 0x02AC91, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 3: SEEL / KRABBY */
    { 0x02AC9D, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 9: KRABBY / SEEL */
    { 0x02AC9F, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 10: SEEL / KRABBY */
    { 0x02ACAD, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 17: SEEL / KRABBY */
    { 0x02ACB1, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 19: SEEL / GOLBAT */
    { 0x02ACB3, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_B2F slot 20: SEEL / GOLBAT */
    { 0x02AC02, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 2: KRABBY / SEEL */
    { 0x02AC04, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 3: SEEL / KRABBY */
    { 0x02AC10, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 9: KRABBY / SEEL */
    { 0x02AC12, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 10: SEEL / KRABBY */
    { 0x02AC20, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 17: SEEL / KRABBY */
    { 0x02AC24, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 19: SEEL / GOLBAT */
    { 0x02AC26, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_CAVE slot 20: SEEL / GOLBAT */
    { 0x02ACBE, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 2: KRABBY / SEEL */
    { 0x02ACC0, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 3: SEEL / KRABBY */
    { 0x02ACCC, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 9: KRABBY / SEEL */
    { 0x02ACCE, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 10: SEEL / KRABBY */
    { 0x02ACDC, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 17: SEEL / KRABBY */
    { 0x02ACE0, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 19: SEEL / GOLBAT */
    { 0x02ACE2, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_LUGIA_CHAMBER slot 20: SEEL / GOLBAT */
    { 0x02ABA4, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 2: KRABBY / SEEL */
    { 0x02ABA6, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 3: SEEL / KRABBY */
    { 0x02ABB2, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 9: KRABBY / SEEL */
    { 0x02ABB4, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 10: SEEL / KRABBY */
    { 0x02ABC2, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 17: SEEL / KRABBY */
    { 0x02ABC6, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 19: SEEL / GOLBAT */
    { 0x02ABC8, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NE slot 20: SEEL / GOLBAT */
    { 0x02AB75, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 2: KRABBY / SEEL */
    { 0x02AB77, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 3: SEEL / KRABBY */
    { 0x02AB83, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 9: KRABBY / SEEL */
    { 0x02AB85, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 10: SEEL / KRABBY */
    { 0x02AB93, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 17: SEEL / KRABBY */
    { 0x02AB97, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 19: SEEL / GOLBAT */
    { 0x02AB99, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_NW slot 20: SEEL / GOLBAT */
    { 0x02AC31, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 2: KRABBY / SEEL */
    { 0x02AC33, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 3: SEEL / KRABBY */
    { 0x02AC3F, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 9: KRABBY / SEEL */
    { 0x02AC41, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 10: SEEL / KRABBY */
    { 0x02AC4F, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 17: SEEL / KRABBY */
    { 0x02AC53, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 19: SEEL / GOLBAT */
    { 0x02AC55, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SE slot 20: SEEL / GOLBAT */
    { 0x02ABD3, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 2: KRABBY / SEEL */
    { 0x02ABD5, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 3: SEEL / KRABBY */
    { 0x02ABE1, 2, {  98,  86,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 9: KRABBY / SEEL */
    { 0x02ABE3, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 10: SEEL / KRABBY */
    { 0x02ABF1, 2, {  86,  98,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 17: SEEL / KRABBY */
    { 0x02ABF5, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 19: SEEL / GOLBAT */
    { 0x02ABF7, 2, {  86,  42,   0 } },  /* JohtoGrassWildMons WHIRL_ISLAND_SW slot 20: SEEL / GOLBAT */
    { 0x02B2AD, 2, {  27,  41,   0 } },  /* KantoGrassWildMons MOUNT_MOON slot 2: SANDSHREW / ZUBAT */
    { 0x02B2B1, 2, {  28,  74,   0 } },  /* KantoGrassWildMons MOUNT_MOON slot 4: SANDSLASH / GEODUDE */
    { 0x02B2BB, 2, {  27,  41,   0 } },  /* KantoGrassWildMons MOUNT_MOON slot 9: SANDSHREW / ZUBAT */
    { 0x02B2BF, 2, {  28,  74,   0 } },  /* KantoGrassWildMons MOUNT_MOON slot 11: SANDSLASH / GEODUDE */
    { 0x02B2C9, 3, {  27,  41,  35 } },  /* KantoGrassWildMons MOUNT_MOON slot 16: SANDSHREW / ZUBAT / CLEFAIRY */
    { 0x02B2CD, 2, {  28,  74,   0 } },  /* KantoGrassWildMons MOUNT_MOON slot 18: SANDSLASH / GEODUDE */
    { 0x02B2E2, 2, { 104, 105,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 5: CUBONE / MAROWAK */
    { 0x02B2E4, 2, { 104, 105,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 6: CUBONE / MAROWAK */
    { 0x02B2F0, 2, { 104, 105,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 12: CUBONE / MAROWAK */
    { 0x02B2F2, 2, { 104, 105,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 13: CUBONE / MAROWAK */
    { 0x02B2F4, 2, { 104,  41,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 14: CUBONE / ZUBAT */
    { 0x02B2F8, 2, {  66,  74,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 16: MACHOP / GEODUDE */
    { 0x02B2FA, 2, {  41,  93,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 17: ZUBAT / HAUNTER */
    { 0x02B2FC, 2, {  67,  41,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 18: MACHOKE / ZUBAT */
    { 0x02B2FE, 2, { 104,  41,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 19: CUBONE / ZUBAT */
    { 0x02B300, 2, { 104,  41,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_1F slot 20: CUBONE / ZUBAT */
    { 0x02B323, 2, { 104,  41,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_B1F slot 14: CUBONE / ZUBAT */
    { 0x02B32B, 2, { 105,  93,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_B1F slot 18: MAROWAK / HAUNTER */
    { 0x02B32D, 2, { 115,  42,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_B1F slot 19: KANGASKHAN / GOLBAT */
    { 0x02B32F, 2, { 115,  42,   0 } },  /* KantoGrassWildMons ROCK_TUNNEL_B1F slot 20: KANGASKHAN / GOLBAT */
    { 0x02B3B8, 2, {  19,  20,   0 } },  /* KantoGrassWildMons ROUTE_1 slot 18: RATTATA / RATICATE */
    { 0x02B543, 2, { 195, 105,   0 } },  /* KantoGrassWildMons ROUTE_10_NORTH slot 4: QUAGSIRE / MAROWAK */
    { 0x02B551, 2, { 125, 105,   0 } },  /* KantoGrassWildMons ROUTE_10_NORTH slot 11: ELECTABUZZ / MAROWAK */
    { 0x02B557, 2, { 195,  48,   0 } },  /* KantoGrassWildMons ROUTE_10_NORTH slot 14: QUAGSIRE / VENONAT */
    { 0x02B55D, 2, { 195,  49,   0 } },  /* KantoGrassWildMons ROUTE_10_NORTH slot 17: QUAGSIRE / VENOMOTH */
    { 0x02B55F, 2, {  20,  41,   0 } },  /* KantoGrassWildMons ROUTE_10_NORTH slot 18: RATICATE / ZUBAT */
    { 0x02B56A, 2, {  96, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 0: DROWZEE / HOPPIP */
    { 0x02B56C, 2, {  19,  20,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 1: RATTATA / RATICATE */
    { 0x02B570, 2, {  96,  17,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 3: DROWZEE / PIDGEOTTO */
    { 0x02B572, 2, {  97,  19,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 4: HYPNO / RATTATA */
    { 0x02B574, 2, {  97, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 5: HYPNO / HOPPIP */
    { 0x02B576, 2, {  97, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 6: HYPNO / HOPPIP */
    { 0x02B578, 2, {  96, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 7: DROWZEE / HOPPIP */
    { 0x02B57A, 2, {  19,  20,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 8: RATTATA / RATICATE */
    { 0x02B57E, 2, {  96,  17,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 10: DROWZEE / PIDGEOTTO */
    { 0x02B580, 2, {  97,  19,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 11: HYPNO / RATTATA */
    { 0x02B582, 2, {  97, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 12: HYPNO / HOPPIP */
    { 0x02B584, 2, {  97, 187,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 13: HYPNO / HOPPIP */
    { 0x02B588, 2, {  19,  52,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 15: RATTATA / MEOWTH */
    { 0x02B58C, 2, {  96, 164,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 17: DROWZEE / NOCTOWL */
    { 0x02B58E, 2, {  97,  20,   0 } },  /* KantoGrassWildMons ROUTE_11 slot 18: HYPNO / RATICATE */
    { 0x02B599, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 0: NIDORINA / NIDORINO */
    { 0x02B59B, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 1: NIDORINO / NIDORINA */
    { 0x02B5A3, 2, { 195, 187,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 5: QUAGSIRE / HOPPIP */
    { 0x02B5A7, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 7: NIDORINA / NIDORINO */
    { 0x02B5A9, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 8: NIDORINO / NIDORINA */
    { 0x02B5B5, 3, {  30,  33,  48 } },  /* KantoGrassWildMons ROUTE_13 slot 14: NIDORINA / NIDORINO / VENONAT */
    { 0x02B5B7, 3, {  33,  30, 195 } },  /* KantoGrassWildMons ROUTE_13 slot 15: NIDORINO / NIDORINA / QUAGSIRE */
    { 0x02B5BB, 2, { 195,  49,   0 } },  /* KantoGrassWildMons ROUTE_13 slot 17: QUAGSIRE / VENOMOTH */
    { 0x02B5C8, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 0: NIDORINA / NIDORINO */
    { 0x02B5CA, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 1: NIDORINO / NIDORINA */
    { 0x02B5D2, 2, { 195, 188,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 5: QUAGSIRE / SKIPLOOM */
    { 0x02B5D6, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 7: NIDORINA / NIDORINO */
    { 0x02B5D8, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 8: NIDORINO / NIDORINA */
    { 0x02B5E4, 3, {  30,  33,  48 } },  /* KantoGrassWildMons ROUTE_14 slot 14: NIDORINA / NIDORINO / VENONAT */
    { 0x02B5E6, 3, {  33,  30, 195 } },  /* KantoGrassWildMons ROUTE_14 slot 15: NIDORINO / NIDORINA / QUAGSIRE */
    { 0x02B5EA, 2, { 195,  49,   0 } },  /* KantoGrassWildMons ROUTE_14 slot 17: QUAGSIRE / VENOMOTH */
    { 0x02B5F7, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 0: NIDORINA / NIDORINO */
    { 0x02B5F9, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 1: NIDORINO / NIDORINA */
    { 0x02B601, 2, { 195, 187,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 5: QUAGSIRE / HOPPIP */
    { 0x02B605, 2, {  30,  33,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 7: NIDORINA / NIDORINO */
    { 0x02B607, 2, {  33,  30,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 8: NIDORINO / NIDORINA */
    { 0x02B613, 3, {  30,  33,  48 } },  /* KantoGrassWildMons ROUTE_15 slot 14: NIDORINA / NIDORINO / VENONAT */
    { 0x02B615, 3, {  33,  30, 195 } },  /* KantoGrassWildMons ROUTE_15 slot 15: NIDORINO / NIDORINA / QUAGSIRE */
    { 0x02B619, 2, { 195,  49,   0 } },  /* KantoGrassWildMons ROUTE_15 slot 17: QUAGSIRE / VENOMOTH */
    { 0x02B62E, 2, { 218,  22,   0 } },  /* KantoGrassWildMons ROUTE_16 slot 4: SLUGMA / FEAROW */
    { 0x02B64A, 2, { 218, 198,   0 } },  /* KantoGrassWildMons ROUTE_16 slot 18: SLUGMA / MURKROW */
    { 0x02B65D, 2, { 218,  88,   0 } },  /* KantoGrassWildMons ROUTE_17 slot 4: SLUGMA / GRIMER */
    { 0x02B677, 2, {  89,  88,   0 } },  /* KantoGrassWildMons ROUTE_17 slot 17: MUK / GRIMER */
    { 0x02B679, 2, { 218,  88,   0 } },  /* KantoGrassWildMons ROUTE_17 slot 18: SLUGMA / GRIMER */
    { 0x02B68C, 2, { 218,  22,   0 } },  /* KantoGrassWildMons ROUTE_18 slot 4: SLUGMA / FEAROW */
    { 0x02B6A6, 2, {  89,  88,   0 } },  /* KantoGrassWildMons ROUTE_18 slot 17: MUK / GRIMER */
    { 0x02B6A8, 2, { 218,  88,   0 } },  /* KantoGrassWildMons ROUTE_18 slot 18: SLUGMA / GRIMER */
    { 0x02B3C3, 2, {  10,  13,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 0: CATERPIE / WEEDLE */
    { 0x02B3C5, 2, {  16, 165,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 1: PIDGEY / LEDYBA */
    { 0x02B3C7, 3, {  11,  14,  16 } },  /* KantoGrassWildMons ROUTE_2 slot 2: METAPOD / KAKUNA / PIDGEY */
    { 0x02B3C9, 2, {  12,  15,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 3: BUTTERFREE / BEEDRILL */
    { 0x02B3CB, 2, {  17, 166,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 4: PIDGEOTTO / LEDIAN */
    { 0x02B3D1, 2, {  10,  13,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 7: CATERPIE / WEEDLE */
    { 0x02B3D5, 3, {  11,  14,  16 } },  /* KantoGrassWildMons ROUTE_2 slot 9: METAPOD / KAKUNA / PIDGEY */
    { 0x02B3D7, 2, {  16,  12,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 10: PIDGEY / BUTTERFREE */
    { 0x02B3E1, 2, { 167, 163,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 15: SPINARAK / HOOTHOOT */
    { 0x02B3E7, 2, { 168, 164,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 18: ARIADOS / NOCTOWL */
    { 0x02B3E9, 2, {  25, 164,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 19: PIKACHU / NOCTOWL */
    { 0x02B3EB, 2, {  25, 164,   0 } },  /* KantoGrassWildMons ROUTE_2 slot 20: PIKACHU / NOCTOWL */
    { 0x02B6B5, 2, { 114,  19,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 1: TANGELA / RATTATA */
    { 0x02B6B9, 2, { 114,  20,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 3: TANGELA / RATICATE */
    { 0x02B6BB, 2, { 114, 122,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 4: TANGELA / MR__MIME */
    { 0x02B6C3, 2, { 114,  19,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 8: TANGELA / RATTATA */
    { 0x02B6C7, 2, { 114,  20,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 10: TANGELA / RATICATE */
    { 0x02B6D1, 2, { 114,  19,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 15: TANGELA / RATTATA */
    { 0x02B6D5, 2, { 114,  20,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 17: TANGELA / RATICATE */
    { 0x02B6D9, 2, { 122, 114,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 19: MR__MIME / TANGELA */
    { 0x02B6DB, 2, { 122, 114,   0 } },  /* KantoGrassWildMons ROUTE_21 slot 20: MR__MIME / TANGELA */
    { 0x02B700, 2, {  19,  60,   0 } },  /* KantoGrassWildMons ROUTE_22 slot 15: RATTATA / POLIWAG */
    { 0x02B704, 2, {  19,  60,   0 } },  /* KantoGrassWildMons ROUTE_22 slot 17: RATTATA / POLIWAG */
    { 0x02B706, 2, {  77,  19,   0 } },  /* KantoGrassWildMons ROUTE_22 slot 18: PONYTA / RATTATA */
    { 0x02B711, 2, {  69,  10,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 0: BELLSPROUT / CATERPIE */
    { 0x02B713, 2, {  69,  10,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 1: BELLSPROUT / CATERPIE */
    { 0x02B715, 2, {  63,  11,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 2: ABRA / METAPOD */
    { 0x02B717, 2, {  70,  63,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 3: WEEPINBELL / ABRA */
    { 0x02B719, 2, {  48,  69,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 4: VENONAT / BELLSPROUT */
    { 0x02B71B, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 5: WEEPINBELL / BUTTERFREE */
    { 0x02B71D, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 6: WEEPINBELL / BUTTERFREE */
    { 0x02B71F, 2, {  69,  10,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 7: BELLSPROUT / CATERPIE */
    { 0x02B723, 2, {  63,  10,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 9: ABRA / CATERPIE */
    { 0x02B725, 2, {  70,  63,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 10: WEEPINBELL / ABRA */
    { 0x02B729, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 12: WEEPINBELL / BUTTERFREE */
    { 0x02B72B, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 13: WEEPINBELL / BUTTERFREE */
    { 0x02B731, 2, {  63,  43,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 16: ABRA / ODDISH */
    { 0x02B733, 2, {  70,  63,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 17: WEEPINBELL / ABRA */
    { 0x02B737, 2, {  49,  44,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 19: VENOMOTH / GLOOM */
    { 0x02B739, 2, {  49,  44,   0 } },  /* KantoGrassWildMons ROUTE_24 slot 20: VENOMOTH / GLOOM */
    { 0x02B740, 2, {  16,  10,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 0: PIDGEY / CATERPIE */
    { 0x02B742, 2, {  69,  16,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 1: BELLSPROUT / PIDGEY */
    { 0x02B744, 2, {  48,  17,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 2: VENONAT / PIDGEOTTO */
    { 0x02B746, 2, {  63,  11,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 3: ABRA / METAPOD */
    { 0x02B748, 2, {  17,  69,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 4: PIDGEOTTO / BELLSPROUT */
    { 0x02B74A, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 5: WEEPINBELL / BUTTERFREE */
    { 0x02B74C, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 6: WEEPINBELL / BUTTERFREE */
    { 0x02B74E, 2, {  16,  10,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 7: PIDGEY / CATERPIE */
    { 0x02B750, 2, {  69,  16,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 8: BELLSPROUT / PIDGEY */
    { 0x02B752, 2, {  16,  17,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 9: PIDGEY / PIDGEOTTO */
    { 0x02B754, 2, {  63,  11,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 10: ABRA / METAPOD */
    { 0x02B756, 2, {  17,  69,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 11: PIDGEOTTO / BELLSPROUT */
    { 0x02B758, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 12: WEEPINBELL / BUTTERFREE */
    { 0x02B75A, 2, {  70,  12,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 13: WEEPINBELL / BUTTERFREE */
    { 0x02B75C, 2, {  48,  43,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 14: VENONAT / ODDISH */
    { 0x02B75E, 2, {  43, 163,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 15: ODDISH / HOOTHOOT */
    { 0x02B760, 2, {  49,  48,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 16: VENOMOTH / VENONAT */
    { 0x02B762, 2, {  63, 164,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 17: ABRA / NOCTOWL */
    { 0x02B764, 2, {  70,  69,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 18: WEEPINBELL / BELLSPROUT */
    { 0x02B766, 2, {  69, 164,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 19: BELLSPROUT / NOCTOWL */
    { 0x02B768, 2, {  69, 164,   0 } },  /* KantoGrassWildMons ROUTE_25 slot 20: BELLSPROUT / NOCTOWL */
    { 0x02B771, 2, {  28,  20,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 1: SANDSLASH / RATICATE */
    { 0x02B775, 2, {  84,  20,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 3: DODUO / RATICATE */
    { 0x02B777, 3, {  85,  24,  84 } },  /* KantoGrassWildMons ROUTE_26 slot 4: DODRIO / ARBOK / DODUO */
    { 0x02B779, 2, {  20,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 5: RATICATE / ARBOK */
    { 0x02B77B, 2, { 195,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 6: QUAGSIRE / ARBOK */
    { 0x02B77F, 2, {  28,  20,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 8: SANDSLASH / RATICATE */
    { 0x02B783, 2, {  84,  20,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 10: DODUO / RATICATE */
    { 0x02B785, 2, {  20,  84,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 11: RATICATE / DODUO */
    { 0x02B787, 2, {  85,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 12: DODRIO / ARBOK */
    { 0x02B789, 2, {  85,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 13: DODRIO / ARBOK */
    { 0x02B78B, 2, {  20, 164,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 14: RATICATE / NOCTOWL */
    { 0x02B78D, 2, {  28,  20,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 15: SANDSLASH / RATICATE */
    { 0x02B78F, 2, {  77, 164,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 16: PONYTA / NOCTOWL */
    { 0x02B795, 2, { 195,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 19: QUAGSIRE / ARBOK */
    { 0x02B797, 2, { 195,  24,   0 } },  /* KantoGrassWildMons ROUTE_26 slot 20: QUAGSIRE / ARBOK */
    { 0x02B7A0, 2, {  20,  24,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 1: RATICATE / ARBOK */
    { 0x02B7A2, 2, {  84,  20,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 2: DODUO / RATICATE */
    { 0x02B7A4, 2, { 195,  84,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 3: QUAGSIRE / DODUO */
    { 0x02B7A8, 2, {  28,  85,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 5: SANDSLASH / DODRIO */
    { 0x02B7AA, 2, {  28,  85,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 6: SANDSLASH / DODRIO */
    { 0x02B7AE, 2, {  20,  24,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 8: RATICATE / ARBOK */
    { 0x02B7B0, 2, {  84,  20,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 9: DODUO / RATICATE */
    { 0x02B7B2, 2, {  20,  84,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 10: RATICATE / DODUO */
    { 0x02B7B6, 2, {  28,  85,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 12: SANDSLASH / DODRIO */
    { 0x02B7B8, 2, {  28,  85,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 13: SANDSLASH / DODRIO */
    { 0x02B7BC, 3, {  20,  24, 164 } },  /* KantoGrassWildMons ROUTE_27 slot 15: RATICATE / ARBOK / NOCTOWL */
    { 0x02B7BE, 2, { 195,  20,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 16: QUAGSIRE / RATICATE */
    { 0x02B7C0, 2, {  20, 195,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 17: RATICATE / QUAGSIRE */
    { 0x02B7C2, 2, {  77, 164,   0 } },  /* KantoGrassWildMons ROUTE_27 slot 18: PONYTA / NOCTOWL */
    { 0x02B7C4, 3, {  28, 195, 164 } },  /* KantoGrassWildMons ROUTE_27 slot 19: SANDSLASH / QUAGSIRE / NOCTOWL */
    { 0x02B7C6, 3, {  28, 195, 164 } },  /* KantoGrassWildMons ROUTE_27 slot 20: SANDSLASH / QUAGSIRE / NOCTOWL */
    { 0x02B7D1, 3, { 217, 232,  78 } },  /* KantoGrassWildMons ROUTE_28 slot 2: URSARING / DONPHAN / RAPIDASH */
    { 0x02B7D3, 2, {  78,  24,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 3: RAPIDASH / ARBOK */
    { 0x02B7DF, 3, { 217, 232,  78 } },  /* KantoGrassWildMons ROUTE_28 slot 9: URSARING / DONPHAN / RAPIDASH */
    { 0x02B7E1, 2, {  78,  24,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 10: RAPIDASH / ARBOK */
    { 0x02B7EB, 2, {  77,  61,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 15: PONYTA / POLIWHIRL */
    { 0x02B7ED, 3, { 217, 232,  42 } },  /* KantoGrassWildMons ROUTE_28 slot 16: URSARING / DONPHAN / GOLBAT */
    { 0x02B7EF, 2, { 215,  61,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 17: SNEASEL / POLIWHIRL */
    { 0x02B7F1, 2, {  78,  42,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 18: RAPIDASH / GOLBAT */
    { 0x02B7F3, 2, {  78,  42,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 19: RAPIDASH / GOLBAT */
    { 0x02B7F5, 2, {  78,  42,   0 } },  /* KantoGrassWildMons ROUTE_28 slot 20: RAPIDASH / GOLBAT */
    { 0x02B3F6, 2, {  21,  23,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 2: SPEAROW / EKANS */
    { 0x02B3F8, 2, {  39,  20,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 3: JIGGLYPUFF / RATICATE */
    { 0x02B3FA, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 4: RATTATA / ARBOK */
    { 0x02B3FC, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 5: SPEAROW / SANDSHREW */
    { 0x02B3FE, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 6: SPEAROW / SANDSHREW */
    { 0x02B404, 2, {  21,  23,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 9: SPEAROW / EKANS */
    { 0x02B406, 2, {  39,  20,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 10: JIGGLYPUFF / RATICATE */
    { 0x02B408, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 11: RATTATA / ARBOK */
    { 0x02B40A, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 12: SPEAROW / SANDSHREW */
    { 0x02B40C, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 13: SPEAROW / SANDSHREW */
    { 0x02B410, 2, {  41,  19,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 15: ZUBAT / RATTATA */
    { 0x02B412, 3, {  19,  23,  20 } },  /* KantoGrassWildMons ROUTE_3 slot 16: RATTATA / EKANS / RATICATE */
    { 0x02B414, 2, {  39,  41,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 17: JIGGLYPUFF / ZUBAT */
    { 0x02B416, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 18: RATTATA / ARBOK */
    { 0x02B418, 2, {  19,  35,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 19: RATTATA / CLEFAIRY */
    { 0x02B41A, 2, {  19,  35,   0 } },  /* KantoGrassWildMons ROUTE_3 slot 20: RATTATA / CLEFAIRY */
    { 0x02B425, 2, {  21,  23,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 2: SPEAROW / EKANS */
    { 0x02B427, 2, {  39,  20,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 3: JIGGLYPUFF / RATICATE */
    { 0x02B429, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 4: RATTATA / ARBOK */
    { 0x02B42B, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 5: SPEAROW / SANDSHREW */
    { 0x02B42D, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 6: SPEAROW / SANDSHREW */
    { 0x02B433, 2, {  21,  23,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 9: SPEAROW / EKANS */
    { 0x02B435, 2, {  39,  20,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 10: JIGGLYPUFF / RATICATE */
    { 0x02B437, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 11: RATTATA / ARBOK */
    { 0x02B439, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 12: SPEAROW / SANDSHREW */
    { 0x02B43B, 2, {  21,  27,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 13: SPEAROW / SANDSHREW */
    { 0x02B43D, 2, {  21,  19,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 14: SPEAROW / RATTATA */
    { 0x02B43F, 2, {  41,  19,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 15: ZUBAT / RATTATA */
    { 0x02B441, 3, {  19,  23,  20 } },  /* KantoGrassWildMons ROUTE_4 slot 16: RATTATA / EKANS / RATICATE */
    { 0x02B443, 2, {  39,  41,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 17: JIGGLYPUFF / ZUBAT */
    { 0x02B445, 2, {  19,  24,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 18: RATTATA / ARBOK */
    { 0x02B447, 2, {  19,  35,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 19: RATTATA / CLEFAIRY */
    { 0x02B449, 2, {  19,  35,   0 } },  /* KantoGrassWildMons ROUTE_4 slot 20: RATTATA / CLEFAIRY */
    { 0x02B452, 2, {  69, 209,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 1: BELLSPROUT / SNUBBULL */
    { 0x02B454, 3, {  16,  52,  17 } },  /* KantoGrassWildMons ROUTE_5 slot 2: PIDGEY / MEOWTH / PIDGEOTTO */
    { 0x02B456, 2, {  16,  63,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 3: PIDGEY / ABRA */
    { 0x02B458, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 4: ABRA / JIGGLYPUFF */
    { 0x02B460, 2, {  69, 209,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 8: BELLSPROUT / SNUBBULL */
    { 0x02B462, 3, {  16,  52,  17 } },  /* KantoGrassWildMons ROUTE_5 slot 9: PIDGEY / MEOWTH / PIDGEOTTO */
    { 0x02B464, 2, {  16,  63,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 10: PIDGEY / ABRA */
    { 0x02B466, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 11: ABRA / JIGGLYPUFF */
    { 0x02B46C, 2, {  43, 163,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 14: ODDISH / HOOTHOOT */
    { 0x02B46E, 2, {  43,  52,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 15: ODDISH / MEOWTH */
    { 0x02B470, 2, {  69, 164,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 16: BELLSPROUT / NOCTOWL */
    { 0x02B472, 2, {  44,  63,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 17: GLOOM / ABRA */
    { 0x02B474, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_5 slot 18: ABRA / JIGGLYPUFF */
    { 0x02B47F, 2, {  16,  19,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 0: PIDGEY / RATTATA */
    { 0x02B481, 2, {  69, 209,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 1: BELLSPROUT / SNUBBULL */
    { 0x02B483, 3, {  16,  52,  81 } },  /* KantoGrassWildMons ROUTE_6 slot 2: PIDGEY / MEOWTH / MAGNEMITE */
    { 0x02B485, 2, {  81,  20,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 3: MAGNEMITE / RATICATE */
    { 0x02B487, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 4: ABRA / JIGGLYPUFF */
    { 0x02B489, 2, {  63, 210,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 5: ABRA / GRANBULL */
    { 0x02B48B, 2, {  63, 210,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 6: ABRA / GRANBULL */
    { 0x02B48D, 2, {  16,  19,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 7: PIDGEY / RATTATA */
    { 0x02B48F, 2, {  69, 209,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 8: BELLSPROUT / SNUBBULL */
    { 0x02B491, 3, {  16,  52,  81 } },  /* KantoGrassWildMons ROUTE_6 slot 9: PIDGEY / MEOWTH / MAGNEMITE */
    { 0x02B493, 2, {  81,  20,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 10: MAGNEMITE / RATICATE */
    { 0x02B495, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 11: ABRA / JIGGLYPUFF */
    { 0x02B497, 2, {  63, 210,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 12: ABRA / GRANBULL */
    { 0x02B499, 2, {  63, 210,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 13: ABRA / GRANBULL */
    { 0x02B49B, 2, {  43,  52,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 14: ODDISH / MEOWTH */
    { 0x02B49D, 3, {  43,  52,  96 } },  /* KantoGrassWildMons ROUTE_6 slot 15: ODDISH / MEOWTH / DROWZEE */
    { 0x02B49F, 2, {  69,  81,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 16: BELLSPROUT / MAGNEMITE */
    { 0x02B4A1, 2, {  81,  54,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 17: MAGNEMITE / PSYDUCK */
    { 0x02B4A3, 2, {  63,  39,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 18: ABRA / JIGGLYPUFF */
    { 0x02B4A5, 2, {  63,  20,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 19: ABRA / RATICATE */
    { 0x02B4A7, 2, {  63,  20,   0 } },  /* KantoGrassWildMons ROUTE_6 slot 20: ABRA / RATICATE */
    { 0x02B4AE, 2, {  19,  52,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 0: RATTATA / MEOWTH */
    { 0x02B4B2, 3, {  58,  37, 209 } },  /* KantoGrassWildMons ROUTE_7 slot 2: GROWLITHE / VULPIX / SNUBBULL */
    { 0x02B4B6, 3, {  19,  53,  39 } },  /* KantoGrassWildMons ROUTE_7 slot 4: RATTATA / PERSIAN / JIGGLYPUFF */
    { 0x02B4B8, 2, {  19,  63,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 5: RATTATA / ABRA */
    { 0x02B4BA, 2, {  19,  63,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 6: RATTATA / ABRA */
    { 0x02B4BC, 2, {  19,  52,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 7: RATTATA / MEOWTH */
    { 0x02B4C0, 3, {  58,  37, 209 } },  /* KantoGrassWildMons ROUTE_7 slot 9: GROWLITHE / VULPIX / SNUBBULL */
    { 0x02B4C4, 3, {  19,  53,  39 } },  /* KantoGrassWildMons ROUTE_7 slot 11: RATTATA / PERSIAN / JIGGLYPUFF */
    { 0x02B4C6, 3, {  58,  37,  63 } },  /* KantoGrassWildMons ROUTE_7 slot 12: GROWLITHE / VULPIX / ABRA */
    { 0x02B4C8, 3, {  58,  37,  63 } },  /* KantoGrassWildMons ROUTE_7 slot 13: GROWLITHE / VULPIX / ABRA */
    { 0x02B4CA, 2, {  19,  52,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 14: RATTATA / MEOWTH */
    { 0x02B4CE, 3, {  58,  37, 228 } },  /* KantoGrassWildMons ROUTE_7 slot 16: GROWLITHE / VULPIX / HOUNDOUR */
    { 0x02B4D0, 2, {  20,  53,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 17: RATICATE / PERSIAN */
    { 0x02B4D2, 3, { 198,  53,  39 } },  /* KantoGrassWildMons ROUTE_7 slot 18: MURKROW / PERSIAN / JIGGLYPUFF */
    { 0x02B4D4, 2, { 228,  63,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 19: HOUNDOUR / ABRA */
    { 0x02B4D6, 2, { 228,  63,   0 } },  /* KantoGrassWildMons ROUTE_7 slot 20: HOUNDOUR / ABRA */
    { 0x02B4DD, 3, {  17,  52, 209 } },  /* KantoGrassWildMons ROUTE_8 slot 0: PIDGEOTTO / MEOWTH / SNUBBULL */
    { 0x02B4E3, 2, {  58,  37,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 3: GROWLITHE / VULPIX */
    { 0x02B4E5, 2, {  17,  39,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 4: PIDGEOTTO / JIGGLYPUFF */
    { 0x02B4EB, 3, {  17,  52, 209 } },  /* KantoGrassWildMons ROUTE_8 slot 7: PIDGEOTTO / MEOWTH / SNUBBULL */
    { 0x02B4F1, 2, {  58,  37,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 10: GROWLITHE / VULPIX */
    { 0x02B4F3, 2, {  17,  39,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 11: PIDGEOTTO / JIGGLYPUFF */
    { 0x02B4F9, 2, { 164,  52,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 14: NOCTOWL / MEOWTH */
    { 0x02B4FB, 2, {  93, 164,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 15: HAUNTER / NOCTOWL */
    { 0x02B4FF, 2, { 164,  93,   0 } },  /* KantoGrassWildMons ROUTE_8 slot 17: NOCTOWL / HAUNTER */
    { 0x02B501, 3, {  58,  37,  39 } },  /* KantoGrassWildMons ROUTE_8 slot 18: GROWLITHE / VULPIX / JIGGLYPUFF */
    { 0x02B50C, 2, {  56,  19,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 0: MANKEY / RATTATA */
    { 0x02B50E, 2, {  19,  21,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 1: RATTATA / SPEAROW */
    { 0x02B510, 2, {  21,  20,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 2: SPEAROW / RATICATE */
    { 0x02B512, 2, {  20,  22,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 3: RATICATE / FEAROW */
    { 0x02B516, 3, {  57,  20, 105 } },  /* KantoGrassWildMons ROUTE_9 slot 5: PRIMEAPE / RATICATE / MAROWAK */
    { 0x02B518, 3, {  57,  20, 105 } },  /* KantoGrassWildMons ROUTE_9 slot 6: PRIMEAPE / RATICATE / MAROWAK */
    { 0x02B51A, 2, {  56,  19,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 7: MANKEY / RATTATA */
    { 0x02B51C, 2, {  19,  21,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 8: RATTATA / SPEAROW */
    { 0x02B51E, 2, {  21,  20,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 9: SPEAROW / RATICATE */
    { 0x02B520, 2, {  20,  22,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 10: RATICATE / FEAROW */
    { 0x02B524, 3, {  57,  20, 105 } },  /* KantoGrassWildMons ROUTE_9 slot 12: PRIMEAPE / RATICATE / MAROWAK */
    { 0x02B526, 3, {  57,  20, 105 } },  /* KantoGrassWildMons ROUTE_9 slot 13: PRIMEAPE / RATICATE / MAROWAK */
    { 0x02B528, 2, {  56,  19,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 14: MANKEY / RATTATA */
    { 0x02B52A, 2, {  19,  48,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 15: RATTATA / VENONAT */
    { 0x02B52E, 2, {  19,  49,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 17: RATTATA / VENOMOTH */
    { 0x02B530, 2, {  20,  41,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 18: RATICATE / ZUBAT */
    { 0x02B532, 2, {  57,  20,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 19: PRIMEAPE / RATICATE */
    { 0x02B534, 2, {  57,  20,   0 } },  /* KantoGrassWildMons ROUTE_9 slot 20: PRIMEAPE / RATICATE */
    { 0x02B338, 2, {  42, 111,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 1: GOLBAT / RHYHORN */
    { 0x02B33A, 3, { 217, 232,  95 } },  /* KantoGrassWildMons VICTORY_ROAD slot 2: URSARING / DONPHAN / ONIX */
    { 0x02B33C, 2, {  95,  42,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 3: ONIX / GOLBAT */
    { 0x02B33E, 2, {  95,  28,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 4: ONIX / SANDSLASH */
    { 0x02B340, 2, { 111, 112,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 5: RHYHORN / RHYDON */
    { 0x02B342, 2, { 111, 112,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 6: RHYHORN / RHYDON */
    { 0x02B346, 2, {  42, 111,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 8: GOLBAT / RHYHORN */
    { 0x02B348, 3, { 217, 232,  95 } },  /* KantoGrassWildMons VICTORY_ROAD slot 9: URSARING / DONPHAN / ONIX */
    { 0x02B34A, 2, {  95,  42,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 10: ONIX / GOLBAT */
    { 0x02B34C, 2, {  95,  28,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 11: ONIX / SANDSLASH */
    { 0x02B34E, 2, { 111, 112,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 12: RHYHORN / RHYDON */
    { 0x02B350, 2, { 111, 112,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 13: RHYHORN / RHYDON */
    { 0x02B352, 2, {  75,  42,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 14: GRAVELER / GOLBAT */
    { 0x02B354, 2, {  42,  75,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 15: GOLBAT / GRAVELER */
    { 0x02B356, 3, { 217, 232,  95 } },  /* KantoGrassWildMons VICTORY_ROAD slot 16: URSARING / DONPHAN / ONIX */
    { 0x02B358, 2, {  95,  75,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 17: ONIX / GRAVELER */
    { 0x02B35A, 2, {  95,  75,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 18: ONIX / GRAVELER */
    { 0x02B35C, 2, { 111,  75,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 19: RHYHORN / GRAVELER */
    { 0x02B35E, 2, { 111,  75,   0 } },  /* KantoGrassWildMons VICTORY_ROAD slot 20: RHYHORN / GRAVELER */
    { 0x02B162, 2, { 118, 183,   0 } },  /* JohtoWaterWildMons MOUNT_MORTAR_1F_OUTSIDE slot 1: GOLDEEN / MARILL */
    { 0x02B16B, 2, { 118, 183,   0 } },  /* JohtoWaterWildMons MOUNT_MORTAR_2F_INSIDE slot 1: GOLDEEN / MARILL */
    { 0x02B174, 2, { 118, 183,   0 } },  /* JohtoWaterWildMons MOUNT_MORTAR_B1F slot 1: GOLDEEN / MARILL */
    { 0x02B1FD, 2, { 226,  72,   0 } },  /* JohtoWaterWildMons ROUTE_41 slot 2: MANTINE / TENTACOOL */
    { 0x02B198, 2, { 119,  55,   0 } },  /* JohtoWaterWildMons SILVER_CAVE_ROOM_2 slot 1: SEAKING / GOLDUCK */
};

#endif /* GEN2_WILD_DIFFS_CRYSTAL_GEN_H */
